"use client";

import { useMemo } from "react";
import { NewsFilterChip } from "@/components/news/news-toolbar";
import { ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
type VisibilityValue = "PUBLIC" | "RESIDENT_ONLY";
type SortValue = "newest" | "oldest";
type Props = { keyword: string; selectedVisibilities: VisibilityValue[]; sort: SortValue; suggestionTitles: string[] };
const visibilityOptions: Array<{ value: VisibilityValue; label: string }> = [{ value: "RESIDENT_ONLY", label: "ลูกบ้าน" }, { value: "PUBLIC", label: "สาธารณะ" }];
function href({ visibilities, sort, keyword }: { visibilities: VisibilityValue[]; sort: SortValue; keyword: string }) { const query = new URLSearchParams(); const values = Array.from(new Set(visibilities)).sort(); if (values.length) query.set("visibility", values.join(",")); if (sort !== "newest") query.set("sort", sort); if (keyword.trim()) query.set("q", keyword.trim()); return query.size ? `/resident/downloads?${query}` : "/resident/downloads"; }
export function ResidentDownloadsToolbar({ keyword, selectedVisibilities, sort, suggestionTitles }: Props) { const visibilitySet = useMemo(() => new Set(selectedVisibilities), [selectedVisibilities]); const toggle = (value: VisibilityValue) => href({ visibilities: visibilitySet.has(value) ? selectedVisibilities.filter((item) => item !== value) : [...selectedVisibilities, value], sort, keyword }); return <ResidentPageToolbar namespace="resident-downloads" title="เอกสารดาวน์โหลด" search={{ keyword, placeholder: "พิมพ์ชื่อเอกสาร", label: "ค้นหาเอกสาร", suggestions: suggestionTitles }} activeFilterCount={selectedVisibilities.length + Number(sort !== "newest")} filters={<><span className="text-xs font-semibold text-gray-500">การมองเห็น</span>{visibilityOptions.map((option) => <NewsFilterChip key={option.value} href={toggle(option.value)} active={visibilitySet.has(option.value)}>{option.label}</NewsFilterChip>)}<span className="ml-1 text-xs font-semibold text-gray-500">เรียง</span>{([['newest','ล่าสุดก่อน'],['oldest','เก่าก่อน']] as const).map(([value,label]) => <NewsFilterChip key={value} href={href({ visibilities: selectedVisibilities, sort: value, keyword })} active={sort === value}>{label}</NewsFilterChip>)}<NewsFilterChip href="/resident/downloads" active={false}>ล้างตัวกรอง</NewsFilterChip></>} />; }
