"use client";

import { useMemo } from "react";
import { NewsFilterChip } from "@/components/news/news-toolbar";
import { ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
type Visibility = "PUBLIC" | "RESIDENT_ONLY";
type Sort = "newest" | "oldest";
type Props = { keyword: string; selectedVisibilities: Visibility[]; sort: Sort; suggestionTitles: string[]; hasResidentAccess: boolean };
function makeHref(visibilities: Visibility[], sort: Sort, keyword: string, hasResidentAccess: boolean) { const query = new URLSearchParams(); if (hasResidentAccess && visibilities.length) query.set("visibility", [...new Set(visibilities)].sort().join(",")); if (sort !== "newest") query.set("sort", sort); if (keyword.trim()) query.set("q", keyword.trim()); return query.size ? `/resident/downloads?${query}` : "/resident/downloads"; }
export function ResidentDownloadsToolbar({ keyword, selectedVisibilities, sort, suggestionTitles, hasResidentAccess }: Props) { const visibilitySet = useMemo(() => new Set(selectedVisibilities), [selectedVisibilities]); const toggle = (value: Visibility) => makeHref(visibilitySet.has(value) ? selectedVisibilities.filter((item) => item !== value) : [...selectedVisibilities, value], sort, keyword, hasResidentAccess); const count = Number(sort !== "newest") + (hasResidentAccess ? selectedVisibilities.length : 0); return <ResidentPageToolbar namespace="resident-downloads" title="เอกสารดาวน์โหลด" search={{ keyword, placeholder: "พิมพ์ชื่อเอกสาร", label: "ค้นหาเอกสาร", suggestions: suggestionTitles }} activeFilterCount={count} filters={<>{hasResidentAccess ? <><span className="text-xs font-semibold text-gray-500">การมองเห็น</span>{([['RESIDENT_ONLY','ลูกบ้าน'],['PUBLIC','สาธารณะ']] as const).map(([value,label]) => <NewsFilterChip key={value} href={toggle(value)} active={visibilitySet.has(value)}>{label}</NewsFilterChip>)}</> : null}<span className="ml-1 text-xs font-semibold text-gray-500">เรียง</span>{([['newest','ล่าสุดก่อน'],['oldest','เก่าก่อน']] as const).map(([value,label]) => <NewsFilterChip key={value} href={makeHref(selectedVisibilities, value, keyword, hasResidentAccess)} active={sort === value}>{label}</NewsFilterChip>)}<NewsFilterChip href="/resident/downloads" active={false}>ล้างตัวกรอง</NewsFilterChip></>} />; }
