import Link from "next/link";
import { ArrowLeft, Pencil } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { NEWS_VISIBILITY_LABELS, TRANSPARENCY_STAGE_LABELS } from "@/lib/constants";
import { prisma } from "@/lib/prisma";
import { SuperAdminDeleteTransparencyButton } from "../superadmin-transparency-form";

const stageVariant: Record<string, "default" | "success" | "warning"> = { DRAFT: "warning", PUBLISHED: "success", ARCHIVED: "default" };

export default async function SuperAdminTransparencyDetailPage({ params }: { params: Promise<{ villageId: string; transparencyId: string }> }) {
  const { villageId, transparencyId } = await params; const record = await prisma.transparencyRecord.findFirst({ where: { id: transparencyId, villageId } }); if (!record) notFound();
  return <div className="mx-auto w-full max-w-4xl space-y-5"><SuperAdminPageHeaderRegistration priority={1} context={{ title: record.title, description: "รายละเอียดข้อมูลความโปร่งใส" }} /><div className="flex flex-wrap items-center justify-between gap-3"><Link href={`/superadmin/villages/${villageId}/transparency`} className="inline-flex min-h-9 items-center gap-1.5 px-1 text-sm text-gray-500 hover:text-gray-700"><ArrowLeft className="h-4 w-4" />กลับรายการความโปร่งใส</Link><div className="flex flex-wrap gap-2"><Link href={`/superadmin/villages/${villageId}/transparency/${record.id}/edit`} className="inline-flex min-h-9 items-center rounded-lg border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"><Pencil className="mr-1 h-4 w-4" />แก้ไข</Link><SuperAdminDeleteTransparencyButton villageId={villageId} recordId={record.id} title={record.title} /></div></div><article className="space-y-5 rounded-xl border border-gray-200 bg-white p-5 sm:p-8"><div className="flex flex-wrap items-center gap-2"><Badge variant={stageVariant[record.stage] ?? "default"}>{TRANSPARENCY_STAGE_LABELS[record.stage] ?? record.stage}</Badge><Badge variant="outline">{NEWS_VISIBILITY_LABELS[record.visibility] ?? record.visibility}</Badge>{record.fiscalYear ? <Badge variant="outline">ปี {record.fiscalYear}</Badge> : null}</div><h1 className="break-words text-2xl font-bold text-gray-900">{record.title}</h1>{record.stage === "ARCHIVED" ? <p className="rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-600">รายการนี้ถูกซ่อนจากผู้ใช้งานทั่วไป แต่ยังสามารถนำกลับมาเผยแพร่ได้</p> : null}<dl className="grid grid-cols-1 gap-4 text-sm text-gray-600 md:grid-cols-2"><div><dt className="text-gray-500">สถานะ</dt><dd>{TRANSPARENCY_STAGE_LABELS[record.stage]}</dd></div><div><dt className="text-gray-500">การมองเห็น</dt><dd>{NEWS_VISIBILITY_LABELS[record.visibility]}</dd></div><div><dt className="text-gray-500">หมวดหมู่</dt><dd>{record.category || "-"}</dd></div><div><dt className="text-gray-500">จำนวนเงิน</dt><dd>{record.amount != null ? `${record.amount.toLocaleString("th-TH")} บาท` : "-"}</dd></div><div><dt className="text-gray-500">ปีงบประมาณ</dt><dd>{record.fiscalYear || "-"}</dd></div><div><dt className="text-gray-500">วันที่สร้าง</dt><dd>{record.createdAt.toLocaleDateString("th-TH")}</dd></div><div><dt className="text-gray-500">วันที่เผยแพร่</dt><dd>{record.publishedAt?.toLocaleDateString("th-TH") ?? "-"}</dd></div></dl>{record.description ? <div className="border-t border-gray-100 pt-5"><h2 className="mb-2 font-semibold text-gray-900">รายละเอียด</h2><p className="whitespace-pre-wrap break-words leading-7 text-gray-700">{record.description}</p></div> : null}</article></div>;
}
