import Link from "next/link";
import { Building2, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { prisma } from "@/lib/prisma";
import { VILLAGE_PLACE_CATEGORY_LABELS } from "@/lib/constants";
import { orderedPlaceImages } from "@/lib/place-image";
import { SupportNotice } from "../public-content-ui";
export default async function SuperAdminVillagePlacesPage({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; category?: string; visibility?: string; sort?: string; page?: string }> }) {
  const { villageId }=await params; const query=await searchParams; const q=query.q?.trim()??""; const category=query.category??"ALL"; const visibility=query.visibility??"ALL"; const page=Math.max(1,Number(query.page)||1); const pageSize=9; const where={villageId,...(category!=="ALL"?{category}:{}),...(visibility!=="ALL"?{isPublic:visibility==="PUBLIC"}:{}),...(q?{OR:[{name:{contains:q,mode:"insensitive" as const}},{description:{contains:q,mode:"insensitive" as const}},{address:{contains:q,mode:"insensitive" as const}}]}:{})};
  const [village,rows,total]=await Promise.all([prisma.village.findUnique({where:{id:villageId},select:{name:true}}),prisma.villagePlace.findMany({where,orderBy:query.sort==="oldest"?{createdAt:"asc"}:{createdAt:"desc"},skip:(page-1)*pageSize,take:pageSize,select:{id:true,name:true,category:true,address:true,imageUrls:true,images:{orderBy:{sortOrder:"asc"},select:{id:true,url:true,fileKey:true,sortOrder:true,isCover:true}},isPublic:true,isFeatured:true,createdAt:true}}),prisma.villagePlace.count({where})]); const base=`/superadmin/villages/${villageId}/places`; const href=(extra:Record<string,string>)=>{const params=new URLSearchParams({...(q?{q}:{}),...(category!=="ALL"?{category}:{}),...(visibility!=="ALL"?{visibility}:{}),...(query.sort?{sort:query.sort}:{}),...extra});return `${base}?${params}`};
  return <div className="space-y-4"><SupportNotice villageName={village?.name??"-"} /><AdminListToolbar sticky title="สถานที่" description={`จัดการข้อมูลสถานที่ของ ${village?.name??"หมู่บ้าน"} เพื่อการสนับสนุนงานหมู่บ้าน`} searchAction={base} clearHref={base} keyword={q} searchPlaceholder="ค้นหาชื่อสถานที่ ที่อยู่ หรือรายละเอียด" hiddenInputs={{category:category==="ALL"?"":category,visibility:visibility==="ALL"?"":visibility,sort:query.sort??""}} groups={[{label:"หมวดหมู่",options:[{label:"ทั้งหมด",href:base,active:category==="ALL"},...Object.entries(VILLAGE_PLACE_CATEGORY_LABELS).map(([value,label])=>({label,href:href({category:value}),active:category===value}))]},{label:"การมองเห็น",options:[{label:"ทั้งหมด",href:base,active:visibility==="ALL"},{label:"สาธารณะ",href:href({visibility:"PUBLIC"}),active:visibility==="PUBLIC"},{label:"เฉพาะลูกบ้าน",href:href({visibility:"RESIDENT"}),active:visibility==="RESIDENT"}]},{label:"เรียงลำดับ",options:[{label:"ล่าสุด",href:base,active:query.sort!=="oldest"},{label:"เก่าก่อน",href:href({sort:"oldest"}),active:query.sort==="oldest"}]}]} actions={<Link href={`${base}/new`} className="inline-flex min-h-10 items-center justify-center rounded-lg bg-green-600 px-3 text-sm text-white"><Plus className="mr-1 h-4 w-4"/>เพิ่มสถานที่</Link>} />{rows.length===0?<div className="rounded-xl border border-dashed bg-white p-10 text-center"><Building2 className="mx-auto mb-3 h-10 w-10 text-gray-300"/><p className="text-gray-600">ยังไม่มีสถานที่ที่ตรงกับเงื่อนไข</p></div>:<div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">{rows.map(place=>{const image=orderedPlaceImages(place.images,place.imageUrls)[0];return <Link key={place.id} href={`${base}/${place.id}`} className="min-w-0 overflow-hidden rounded-xl border bg-white hover:shadow-md"><div className="aspect-video bg-gray-100">{image?<img src={image.url} alt={place.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-sm text-gray-400">ไม่มีรูปภาพ</div>}</div><div className="space-y-2 p-4"><div className="flex flex-wrap gap-2"><Badge variant="outline">{VILLAGE_PLACE_CATEGORY_LABELS[place.category]??place.category}</Badge><Badge variant={place.isPublic?"success":"info"}>{place.isPublic?"สาธารณะ":"เฉพาะลูกบ้าน"}</Badge>{place.isFeatured?<Badge variant="warning">สำคัญ</Badge>:null}</div><p className="truncate font-medium">{place.name}</p><p className="line-clamp-2 text-sm text-gray-600">{place.address??"ไม่มีที่อยู่"}</p></div></Link>})}</div>}{total>pageSize?<div className="flex justify-end gap-2">{page>1?<Link className="rounded border px-3 py-2 text-sm" href={href({page:String(page-1)})}>ก่อนหน้า</Link>:null}{page*pageSize<total?<Link className="rounded border px-3 py-2 text-sm" href={href({page:String(page+1)})}>ถัดไป</Link>:null}</div>:null}</div>;
}
