"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { PlaceImageManager } from "@/components/places/place-image-manager";
import type { PlaceImageInput, PlaceImageView } from "@/lib/place-image";
import { VILLAGE_PLACE_CATEGORY_LABELS } from "@/lib/constants";
import { VILLAGE_PLACE_CATEGORIES } from "@/lib/village-place";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { ActionReasonDialog } from "@/components/admin/action-reason-dialog";
import { useToast } from "@/components/ui/toast";
import { superAdminSavePlaceDataAction } from "../public-content-actions";

type PlaceData = { name: string; category: string; description: string; address: string; openingHours: string; contactPhone: string; mapUrl: string; latitude: string; longitude: string; isPublic: boolean; isFeatured: boolean; images: PlaceImageInput[] };

function SettingSwitch({ label, helper, name, defaultChecked }: { label: string; helper: string; name: string; defaultChecked: boolean }) {
  return <label className="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-gray-200 px-4 py-3 transition hover:border-gray-300"><span><span className="block text-sm font-medium text-gray-900">{label}</span><span className="mt-1 block text-xs leading-5 text-gray-500">{helper}</span></span><span className="relative mt-0.5 inline-flex shrink-0"><input type="checkbox" name={name} defaultChecked={defaultChecked} className="peer sr-only" /><span aria-hidden className="h-6 w-11 rounded-full bg-gray-200 transition peer-checked:bg-green-700 peer-focus-visible:ring-2 peer-focus-visible:ring-green-500 after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:after:translate-x-5" /></span></label>;
}

export function SuperAdminPlaceForm({ villageId, placeId, initial }: { villageId: string; placeId?: string; initial?: Omit<PlaceData, "images"> & { images: PlaceImageView[] } }) {
  const router = useRouter(); const toast = useToast(); const [images, setImages] = useState<PlaceImageView[]>(initial?.images ?? []); const [draft, setDraft] = useState<PlaceData | null>(null); const [uploadBusy, setUploadBusy] = useState(false); const [pending, setPending] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (uploadBusy) return; const f = new FormData(event.currentTarget); setDraft({ name: String(f.get("name") ?? ""), category: String(f.get("category") ?? "OTHER"), description: String(f.get("description") ?? ""), address: String(f.get("address") ?? ""), openingHours: String(f.get("openingHours") ?? ""), contactPhone: String(f.get("contactPhone") ?? ""), mapUrl: String(f.get("mapUrl") ?? ""), latitude: String(f.get("latitude") ?? ""), longitude: String(f.get("longitude") ?? ""), isPublic: f.get("isPublic") === "on", isFeatured: f.get("isFeatured") === "on", images: images as PlaceImageInput[] }); };
  const confirm = async (reason: string) => { if (!draft) return; setPending(true); const result = await superAdminSavePlaceDataAction(villageId, placeId ?? null, draft, reason); setPending(false); if (!result.success) { toast.error(result.error); return; } toast.success(placeId ? "บันทึกการแก้ไขแล้ว" : "เพิ่มสถานที่แล้ว"); setDraft(null); router.replace(`/superadmin/villages/${villageId}/places/${"placeId" in result ? result.placeId : placeId}`); };
  const cancelHref = placeId ? `/superadmin/villages/${villageId}/places/${placeId}` : `/superadmin/villages/${villageId}/places`;
  return <><form onSubmit={submit} className="space-y-8 rounded-xl border border-gray-200 bg-white p-4 sm:p-6">
    <section className="space-y-4"><div><h2 className="font-semibold text-gray-900">ข้อมูลสถานที่</h2><p className="mt-1 text-sm text-gray-500">รายละเอียดที่ใช้ค้นหาและแสดงในรายการสถานที่</p></div><Input name="name" label="ชื่อสถานที่" defaultValue={initial?.name ?? ""} required /><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Select name="category" label="หมวดหมู่" defaultValue={initial?.category ?? "OTHER"} options={VILLAGE_PLACE_CATEGORIES.map((value) => ({ value, label: VILLAGE_PLACE_CATEGORY_LABELS[value] }))} /><Input name="contactPhone" label="เบอร์โทรศัพท์ติดต่อ" defaultValue={initial?.contactPhone ?? ""} /></div><Textarea name="description" label="รายละเอียด" rows={5} defaultValue={initial?.description ?? ""} /></section>
    <section className="space-y-4 border-t border-gray-100 pt-6"><div><h2 className="font-semibold text-gray-900">ข้อมูลติดต่อและตำแหน่ง</h2></div><Input name="address" label="ที่อยู่" defaultValue={initial?.address ?? ""} /><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Input name="openingHours" label="เวลาเปิด-ปิด" defaultValue={initial?.openingHours ?? ""} placeholder="เช่น ทุกวัน 08:00-17:00" /><Input name="mapUrl" label="ลิงก์แผนที่" defaultValue={initial?.mapUrl ?? ""} placeholder="https://maps.google.com/..." /></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Input name="latitude" label="Latitude" defaultValue={initial?.latitude ?? ""} placeholder="13.7563" /><Input name="longitude" label="Longitude" defaultValue={initial?.longitude ?? ""} placeholder="100.5018" /></div></section>
    <section className="space-y-3 border-t border-gray-100 pt-6"><h2 className="font-semibold text-gray-900">การแสดงผล</h2><SettingSwitch name="isPublic" label="เผยแพร่สาธารณะ" helper="เปิดเพื่อให้บุคคลทั่วไปสามารถเห็นสถานที่นี้ได้" defaultChecked={initial?.isPublic ?? true} /><SettingSwitch name="isFeatured" label="สถานที่สำคัญ" helper="ทำเครื่องหมายสถานที่ที่ควรแสดงเด่นหรือค้นหาได้ง่ายเป็นพิเศษ" defaultChecked={initial?.isFeatured ?? false} /></section>
    <section className="space-y-4 border-t border-gray-100 pt-6"><h2 className="font-semibold text-gray-900">รูปภาพสถานที่</h2><PlaceImageManager value={images} onChange={(next) => setImages(next as PlaceImageView[])} onBusyChange={setUploadBusy} disabled={pending || uploadBusy} uploadEndpoint={`/api/places/images?villageId=${encodeURIComponent(villageId)}`} /></section>
    <div className="flex flex-col-reverse gap-3 border-t border-gray-100 pt-5 sm:flex-row sm:items-center"><Button type="button" variant="outline" onClick={() => router.push(cancelHref)}>ยกเลิก</Button><Button type="submit" disabled={uploadBusy || pending} isLoading={pending}>บันทึก</Button></div>
  </form><ActionReasonDialog open={Boolean(draft)} action="content.archive" title={placeId ? "ยืนยันการแก้ไขสถานที่" : "ยืนยันการสร้างสถานที่"} description="ระบบจะบันทึก Audit Log และแจ้งผู้ดูแลหมู่บ้าน" reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => setDraft(null)} onSubmit={confirm} /></>;
}
