CREATE TYPE "HouseSourceType" AS ENUM ('ADMIN_CREATED', 'IMPORT', 'RESIDENT_REQUEST_VERIFIED', 'SUPERADMIN_CREATED', 'SEED');

ALTER TABLE "House"
  ADD COLUMN "sourceType" "HouseSourceType" NOT NULL DEFAULT 'ADMIN_CREATED',
  ADD COLUMN "sourceNote" TEXT,
  ADD COLUMN "verifiedByUserId" TEXT,
  ADD COLUMN "verifiedAt" TIMESTAMP(3);
