"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ActionReasonDialog } from "@/components/admin/action-reason-dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { reviewSuperAdminCalendarRequestAction } from "../../operational-actions";

function SettingSwitch({ label, helper, checked, onChange, disabled }: { label: string; helper: string; checked: boolean; onChange: (checked: boolean) => void; disabled: boolean }) {
  return <label className="flex min-w-0 cursor-pointer items-start justify-between gap-4 rounded-xl border border-gray-200 px-4 py-3 transition hover:border-gray-300 has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-green-500 has-[:disabled]:cursor-not-allowed has-[:disabled]:opacity-60"><span className="min-w-0"><span className="block text-sm font-medium text-gray-900">{label}</span><span className="mt-1 block break-words text-xs leading-5 text-gray-500">{helper}</span></span><span className="relative mt-0.5 inline-flex shrink-0"><input type="checkbox" className="peer sr-only" checked={checked} onChange={(event) => onChange(event.target.checked)} disabled={disabled} /><span aria-hidden="true" className="h-6 w-11 rounded-full bg-gray-200 transition peer-checked:bg-green-700 peer-focus-visible:ring-2 peer-focus-visible:ring-green-500 after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:after:translate-x-5" /></span></label>;
}

export function CalendarRequestReviewActions({ villageId, requestId, initialIsPublic }: { villageId: string; requestId: string; initialIsPublic: boolean }) {
  const router = useRouter(); const toast = useToast();
  const [decision, setDecision] = useState<"APPROVE" | "REJECT" | null>(null);
  const [isPublic, setIsPublic] = useState(initialIsPublic); const [businessReason, setBusinessReason] = useState(""); const [pending, startTransition] = useTransition();
  const confirm = (supportReason: string) => { if (!decision) return; const normalizedBusinessReason = businessReason.trim(); if (decision === "REJECT" && (normalizedBusinessReason.length < 5 || normalizedBusinessReason.length > 500)) { toast.error("กรุณาระบุเหตุผลปฏิเสธ", "ระบุ 5–500 ตัวอักษร"); return; } startTransition(async () => { const data = new FormData(); data.set("decision", decision); data.set("visibility", isPublic ? "PUBLIC" : "RESIDENT"); data.set("supportReason", supportReason); data.set("businessReason", normalizedBusinessReason); const result = await reviewSuperAdminCalendarRequestAction(villageId, requestId, data); if (!result.success) { toast.error("บันทึกผลการพิจารณาไม่สำเร็จ", result.error); return; } toast.success(result.message); setBusinessReason(""); setDecision(null); router.refresh(); }); };
  return <div className="space-y-4"><section className="space-y-3 border-t border-gray-100 pt-4"><h3 className="font-semibold text-gray-900">การตั้งค่าก่อนอนุมัติ</h3><SettingSwitch label="เผยแพร่สาธารณะ" helper="เปิดเพื่อให้บุคคลทั่วไปสามารถเห็นกิจกรรมนี้ได้" checked={isPublic} onChange={setIsPublic} disabled={pending} /></section><section className="flex flex-col gap-2 border-t border-gray-100 pt-4 sm:flex-row"><Button type="button" disabled={pending} onClick={() => setDecision("APPROVE")}>อนุมัติ</Button><Button type="button" variant="danger" disabled={pending} onClick={() => setDecision("REJECT")}>ปฏิเสธ</Button></section><ActionReasonDialog open={decision !== null} action="content.request.reject" title={decision === "APPROVE" ? "ยืนยันการอนุมัติคำขอกิจกรรม" : "ยืนยันการปฏิเสธคำขอกิจกรรม"} description="ระบบจะดำเนินการหลังยืนยันและแจ้งผู้ดูแลหมู่บ้าน" reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} submitLabel="ยืนยันดำเนินการ" loading={pending} onCancel={() => { setBusinessReason(""); setDecision(null); }} onSubmit={confirm}>{decision === "REJECT" ? <Textarea label="เหตุผลที่ปฏิเสธคำขอกิจกรรม" value={businessReason} onChange={(event) => setBusinessReason(event.target.value)} required minLength={5} maxLength={500} rows={4} helperText="เหตุผลนี้จะแสดงแก่ผู้ขอกิจกรรม" disabled={pending} /> : null}</ActionReasonDialog></div>;
}
