"use client";
import Link from "next/link";
import { FilePlus2, ListChecks } from "lucide-react";
import { ResidentFilterDropdown, ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
import { VILLAGE_PLACE_CATEGORY_LABELS } from "@/lib/constants";
type SortValue = "newest" | "oldest" | "name_asc" | "name_desc"; type Props = { keyword: string; category: string; featured: boolean; sort: SortValue; canSubmit: boolean };
const sortOptions: Array<{ value: SortValue; label: string }> = [{ value: "newest", label: "ล่าสุดก่อน" }, { value: "oldest", label: "เก่าสุดก่อน" }, { value: "name_asc", label: "ชื่อ ก-ฮ" }, { value: "name_desc", label: "ชื่อ ฮ-ก" }];
function href({ keyword, category, featured, sort }: { keyword: string; category: string; featured: boolean; sort: SortValue }) { const query = new URLSearchParams(); if (keyword.trim()) query.set("q", keyword.trim()); if (category !== "ALL") query.set("category", category); if (featured) query.set("featured", "1"); if (sort !== "newest") query.set("sort", sort); return query.size ? `/resident/places?${query}` : "/resident/places"; }
export function ResidentPlacesToolbar({ keyword, category, featured, sort, canSubmit }: Props) {
  const activeFilterCount = Number(category !== "ALL") + Number(featured);
  return <ResidentPageToolbar namespace="resident-places" title="สถานที่" registerHeader search={{ keyword, placeholder: "พิมพ์ชื่อสถานที่", label: "ค้นหาสถานที่" }} activeFilterCount={activeFilterCount} actions={canSubmit ? <><Link href="/resident/places/requests" aria-label="คำขอสถานที่ของฉัน" className="inline-flex h-10 items-center justify-center rounded-lg border border-gray-300 px-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 sm:px-3"><ListChecks className="h-4 w-4" aria-hidden="true" /><span className="hidden sm:ml-1.5 sm:inline">คำขอของฉัน</span></Link><Link href="/resident/places/requests/new" aria-label="ขอเพิ่มสถานที่" className="inline-flex h-10 items-center justify-center rounded-lg bg-green-600 px-2 text-sm font-medium text-white transition-colors hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 sm:px-3"><FilePlus2 className="h-4 w-4" aria-hidden="true" /><span className="hidden min-[390px]:ml-1 min-[390px]:inline">ขอเพิ่มสถานที่</span></Link></> : undefined} filters={<>
    <ResidentFilterDropdown label="หมวดหมู่" options={[{ label: "ทั้งหมด", href: href({ keyword, category: "ALL", featured, sort }), active: category === "ALL" }, ...Object.entries(VILLAGE_PLACE_CATEGORY_LABELS).map(([value, label]) => ({ label, href: href({ keyword, category: value, featured, sort }), active: category === value }))]} />
    <ResidentFilterDropdown label="ความสำคัญ" options={[{ label: "ทั้งหมด", href: href({ keyword, category, featured: false, sort }), active: !featured }, { label: "สถานที่สำคัญ", href: href({ keyword, category, featured: true, sort }), active: featured }]} />
    <ResidentFilterDropdown label="เรียง" options={sortOptions.map((option) => ({ ...option, href: href({ keyword, category, featured, sort: option.value }), active: sort === option.value }))} />
    {activeFilterCount > 0 ? <Link href={href({ keyword, category: "ALL", featured: false, sort })} className="inline-flex h-9 items-center rounded-md px-2 text-xs font-medium text-gray-600 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-green-500">ล้างตัวกรอง</Link> : null}
  </>} />;
}
