import Link from "next/link";
import { MembershipStatus } from "@prisma/client";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { HouseForm } from "@/features/population/components/house-form";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { maskNationalId } from "@/lib/utils";
import { updateSuperAdminHouseAction } from "../../population-actions";

export default async function Page({params}:{params:Promise<{villageId:string;houseId:string}>}){await requireSuperAdminPageSession();const {villageId,houseId}=await params;const house=await prisma.house.findFirst({where:{id:houseId,villageId},include:{village:{select:{name:true}},zone:{select:{name:true}},persons:{where:{villageId},orderBy:[{firstName:"asc"},{lastName:"asc"}]},memberships:{where:{villageId,status:MembershipStatus.ACTIVE},include:{user:{select:{name:true,phoneNumber:true}}},orderBy:{role:"asc"}}}});if(!house)notFound();const base=`/superadmin/villages/${villageId}`;return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><Link href={`${base}/houses`} className="text-sm text-slate-500 hover:text-slate-900">← กลับทะเบียนบ้าน</Link><h2 className="mt-2 text-2xl font-semibold">บ้านเลขที่ {house.houseNumber}</h2><p className="mt-1 text-sm text-slate-500">{house.village.name} · ตรวจสอบข้อมูลและช่วยแก้ไขแทนผู้ดูแลหมู่บ้าน</p></div></header>
 <HouseForm mode="edit" action={updateSuperAdminHouseAction.bind(null,villageId,houseId)} defaults={{houseNumber:house.houseNumber,address:house.address??"",reason:house.sourceNote??""}}/>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["ประชากร",`${house.persons.length} คน`],["สมาชิกระบบ",`${house.memberships.length} บัญชี`],["แหล่งข้อมูล",house.sourceType],["โซน",house.zone?.name??"-"]].map(([k,v])=><div key={k} className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">{k}</p><p className="mt-1 font-semibold">{v}</p></div>)}</section>
 <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b px-4 py-3 font-semibold">คนในทะเบียนบ้าน</div><div className="divide-y">{house.persons.map(p=><Link key={p.id} href={`${base}/people/${p.id}`} className="flex flex-col gap-1 px-4 py-3 hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><span className="font-medium">{p.firstName} {p.lastName}</span><span className="text-sm text-slate-500">{p.nationalId?maskNationalId(p.nationalId):"ไม่ระบุเลขบัตร"} · {p.status}</span></Link>)}{!house.persons.length?<p className="p-8 text-center text-sm text-slate-500">ยังไม่มีประชากรในบ้านนี้</p>:null}</div></section>
 <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b px-4 py-3 font-semibold">User / Membership ที่ผูกกับบ้าน</div><div className="divide-y">{house.memberships.map(m=><div key={m.id} className="flex flex-col gap-1 px-4 py-3 sm:flex-row sm:justify-between"><span className="font-medium">{m.user.name}</span><span className="text-sm text-slate-500">{m.user.phoneNumber} · {m.role} · {m.status}</span></div>)}{!house.memberships.length?<p className="p-8 text-center text-sm text-slate-500">ยังไม่มีบัญชีที่ผูกกับบ้านนี้</p>:null}</div></section>
 <section className="rounded-xl border bg-white p-4 text-sm"><h3 className="font-semibold">Metadata</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-slate-500">สร้างเมื่อ</dt><dd>{house.createdAt.toLocaleString("th-TH")}</dd></div><div><dt className="text-slate-500">แก้ไขล่าสุด</dt><dd>{house.updatedAt.toLocaleString("th-TH")}</dd></div><div><dt className="text-slate-500">ยืนยันเมื่อ</dt><dd>{house.verifiedAt?.toLocaleString("th-TH")??"-"}</dd></div><div><dt className="text-slate-500">หมายเหตุแหล่งข้อมูล</dt><dd>{house.sourceNote??"-"}</dd></div></dl></section></div>}
