import Link from "next/link";
import { ArrowLeft, FileClock, Plus } from "lucide-react";
import { redirect } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { VILLAGE_EVENT_SUBMISSION_STATUS_LABELS, VILLAGE_EVENT_VISIBILITY_LABELS } from "@/lib/constants";
import { getResidentMembership, getSessionContextFromServerCookies } from "@/lib/access-control";
import { prisma } from "@/lib/prisma";
type RequestItem = { id: string; status: string; isPublic: boolean; title: string; startsAt: Date; location: string | null; reviewNote: string | null; createdAt: Date };
type Delegate = { findMany(args: unknown): Promise<RequestItem[]> };
const variants: Record<string, "default" | "info" | "success" | "warning" | "danger"> = { PENDING: "warning", APPROVED: "success", REJECTED: "danger" };
export default async function ResidentCalendarRequestsPage({ searchParams }: { searchParams?: Promise<{ submitted?: string }> }) {
  const params = (searchParams ? await searchParams : {}) ?? {}; const session = await getSessionContextFromServerCookies(); if (!session?.id) redirect("/auth/login"); const membership = getResidentMembership(session); if (!membership) redirect("/resident/dashboard");
  const requests = await (prisma as unknown as { villageEventSubmission: Delegate }).villageEventSubmission.findMany({ where: { requesterId: session.id, villageId: membership.villageId }, orderBy: [{ createdAt: "desc" }] });
  return <div className="space-y-6"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">คำขอกิจกรรมของฉัน</h1><p className="mt-1 text-sm text-gray-500">ติดตามสถานะคำขอเพิ่มกิจกรรมหมู่บ้าน</p></div><div className="flex shrink-0 gap-2"><Link href="/resident/calendar" className="inline-flex h-9 items-center gap-1 rounded-lg border border-gray-300 px-2 text-sm text-gray-700 hover:bg-gray-50"><ArrowLeft className="h-4 w-4" /><span className="hidden sm:inline">กลับไปปฏิทิน</span></Link><Link href="/resident/calendar/requests/new"><Button size="sm"><Plus className="h-4 w-4" /><span className="hidden sm:ml-1 sm:inline">ส่งคำขอ</span></Button></Link></div></div>{params.submitted === "1" ? <div className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">ส่งคำขอเรียบร้อยแล้ว รอแอดมินพิจารณา</div> : null}{requests.length === 0 ? <div className="rounded-xl border border-gray-200 bg-white p-10 text-center"><FileClock className="mx-auto mb-3 h-10 w-10 text-gray-300" /><p className="text-gray-600">ยังไม่มีคำขอกิจกรรม</p></div> : <div className="space-y-3">{requests.map(request => <Link key={request.id} href={`/resident/calendar/requests/${request.id}`} className="block cursor-pointer rounded-xl border border-gray-200 bg-white p-5 transition-colors hover:border-green-300 hover:bg-green-50/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-600"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="mb-1 flex flex-wrap gap-2"><Badge variant={variants[request.status] ?? "default"}>{VILLAGE_EVENT_SUBMISSION_STATUS_LABELS[request.status] ?? request.status}</Badge><Badge variant="outline">{VILLAGE_EVENT_VISIBILITY_LABELS[request.isPublic ? "PUBLIC" : "RESIDENT"]}</Badge></div><p className="font-medium text-gray-900">{request.title}</p><p className="mt-1 text-sm text-gray-500">{request.startsAt.toLocaleString("th-TH")}{request.location ? ` · ${request.location}` : ""}</p>{request.reviewNote ? <p className="mt-2 text-sm text-gray-600">หมายเหตุ: {request.reviewNote}</p> : null}</div><p className="whitespace-nowrap text-xs text-gray-400">{request.createdAt.toLocaleDateString("th-TH")}</p></div></Link>)}</div>}</div>;
}
