import { BookOpen, ExternalLink, Landmark, MapPin, Route, Sprout, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { getCommunityProfile } from "@/features/public-village/server/community-profile";
import { getPublicVillageProfile } from "@/features/public-village/server/public-village-profile";
import { formatThaiDate } from "@/lib/utils";
interface PageProps { params: Promise<{ villageSlug: string }> }
export default async function VillageInfoPage({ params }: PageProps) {
  const { villageSlug } = await params; const profile = await getPublicVillageProfile(villageSlug); if (!profile) notFound();
  const { village } = profile; const catalog = village.catalogVillage; const community = getCommunityProfile(catalog?.officialCode); const villageName = `บ้าน${village.name}`;
  const location = [village.subdistrict && `ตำบล${village.subdistrict}`, village.district && `อำเภอ${village.district}`, village.province && `จังหวัด${village.province}`].filter(Boolean).join(" ");
  const history = village.description ? [village.description, community?.history[1]].filter(Boolean) : community?.history;
  const stats = [["ประชากรทั้งหมด", catalog?.populationTotal, "คน"], ["จำนวนครัวเรือน", catalog?.householdCount, "ครัวเรือน"], ["ประชากรชาย", catalog?.malePopulation, "คน"], ["ประชากรหญิง", catalog?.femalePopulation, "คน"]].filter((item): item is [string, number, string] => item[1] != null);
  const mapUrl = catalog?.latitude != null && catalog.longitude != null ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${catalog.latitude},${catalog.longitude}`)}` : null;
  return <div className="mx-auto max-w-4xl space-y-7 sm:space-y-8"><header><p className="text-sm font-medium text-emerald-700">ข้อมูลหมู่บ้าน</p><h1 className="mt-1 text-2xl font-bold text-gray-900 sm:text-3xl">{villageName}{village.moo ? ` หมู่ ${village.moo}` : ""}</h1><p className="mt-2 text-sm leading-6 text-gray-600">{location}</p></header>
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Users className="h-5 w-5 text-emerald-700" />ข้อมูลพื้นฐาน</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-3"><div><dt className="text-gray-500">ชื่อหมู่บ้าน</dt><dd className="font-medium">{villageName}</dd></div><div><dt className="text-gray-500">หมู่ที่</dt><dd className="font-medium">{village.moo ?? "-"}</dd></div><div><dt className="text-gray-500">รหัสหมู่บ้าน</dt><dd className="font-medium">{catalog?.officialCode ?? "-"}</dd></div><div><dt className="text-gray-500">ตำบล</dt><dd className="font-medium">{village.subdistrict ?? "-"}</dd></div><div><dt className="text-gray-500">อำเภอ</dt><dd className="font-medium">{village.district ?? "-"}</dd></div><div><dt className="text-gray-500">จังหวัด</dt><dd className="font-medium">{village.province ?? "-"}</dd></div></dl>{stats.length > 0 && <dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(([label, value, unit]) => <div key={label} className="rounded-xl bg-gray-50 p-3"><dt className="text-xs text-gray-500">{label}</dt><dd className="mt-1 text-lg font-bold text-gray-900">{value.toLocaleString("th-TH")} <span className="text-xs font-medium text-gray-600">{unit}</span></dd></div>)}</dl>}</section>
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><BookOpen className="h-5 w-5 text-emerald-700" />ประวัติชุมชน</h2><div className="mt-3 space-y-3 text-sm leading-7 text-gray-600">{history?.map((paragraph) => <p key={paragraph}>{paragraph}</p>) ?? <p>ยินดีต้อนรับสู่{villageName} แหล่งข้อมูลและบริการออนไลน์สำหรับชุมชน</p>}</div>{community && <p className="mt-3 text-xs leading-5 text-gray-500">{community.attribution}</p>}</section>
    {community && <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Landmark className="h-5 w-5 text-emerald-700" />จุดเด่นของชุมชน</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{community.highlights.map((item) => <article key={item.title} className="rounded-xl border border-gray-100 bg-white p-4"><Sprout className="h-5 w-5 text-emerald-700" /><h3 className="mt-3 font-semibold text-gray-900">{item.title}</h3><p className="mt-1 text-sm leading-6 text-gray-600">{item.description}</p></article>)}</div></section>}
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><MapPin className="h-5 w-5 text-emerald-700" />ที่ตั้งและการเดินทาง</h2><p className="mt-3 font-semibold text-gray-900">{villageName}</p><p className="mt-1 text-sm leading-6 text-gray-600">{location}</p>{community && <p className="mt-3 flex items-start gap-2 text-sm leading-6 text-gray-600"><Route className="mt-0.5 h-4 w-4 shrink-0 text-emerald-700" />{community.transport}</p>}{mapUrl && <a href={mapUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg border border-emerald-200 px-3 text-sm font-medium text-emerald-800 hover:bg-emerald-50">ดูแผนที่ <ExternalLink className="h-3.5 w-3.5" /></a>}</section>
    {(catalog?.sourceName || catalog?.sourceUpdatedAt) && <p className="text-xs leading-5 text-gray-500">{catalog.sourceName && <>แหล่งข้อมูล: {catalog.sourceUrl ? <a href={catalog.sourceUrl} target="_blank" rel="noreferrer" className="text-emerald-700 hover:underline">{catalog.sourceName}</a> : catalog.sourceName}</>}{catalog.sourceUpdatedAt && <><br />อัปเดตข้อมูล: {formatThaiDate(catalog.sourceUpdatedAt)}</>}</p>}
  </div>;
}
