import Link from "next/link";
import { Files, Plus } from "lucide-react";
import { Prisma } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { DownloadMetadata } from "@/components/downloads/download-metadata";
import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { Button } from "@/components/ui/button";
import { DOWNLOAD_CATEGORY_OPTIONS, DOWNLOAD_STAGE_LABELS } from "@/lib/downloads/constants";
import { formatFileSize } from "@/lib/utils";
import { prisma } from "@/lib/prisma";
import { WorkspaceListPage } from "../workspace-list-page";

export default async function Page({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; stage?: string; category?: string; visibility?: string; sort?: string }> }) {
  const { villageId } = await params; const query = await searchParams; const keyword = query.q?.trim() ?? ""; const stage = query.stage ?? "ALL"; const category = query.category ?? "ALL"; const visibility = query.visibility ?? "ALL"; const sort = query.sort ?? "newest";
  const village = await prisma.village.findUnique({ where: { id: villageId }, select: { name: true } }); if (!village) return null;
  const where: Prisma.DownloadFileWhereInput = { villageId }; if (["DRAFT", "PUBLISHED", "ARCHIVED"].includes(stage)) where.stage = stage as Prisma.DownloadFileWhereInput["stage"]; if (DOWNLOAD_CATEGORY_OPTIONS.some((item) => item.value === category)) where.category = category; if (["PUBLIC", "RESIDENT_ONLY"].includes(visibility)) where.visibility = visibility as Prisma.DownloadFileWhereInput["visibility"]; if (keyword) where.OR = [{ title: { contains: keyword, mode: "insensitive" } }, { description: { contains: keyword, mode: "insensitive" } }, { categoryLabel: { contains: keyword, mode: "insensitive" } }];
  const files = await prisma.downloadFile.findMany({ where, orderBy: { updatedAt: sort === "oldest" ? "asc" : "desc" }, include: { attachments: { orderBy: { sortOrder: "asc" } } } });
  if (sort === "downloads") files.sort((left, right) => right.downloadCount - left.downloadCount || right.updatedAt.getTime() - left.updatedAt.getTime());
  const href = (next: Record<string, string | undefined>) => { const p = new URLSearchParams(); const values = { q: keyword, stage, category, visibility, sort, ...next }; for (const [key, value] of Object.entries(values)) if (value && value !== "ALL" && value !== "newest") p.set(key, value); return `/superadmin/villages/${villageId}/downloads${p.size ? `?${p}` : ""}`; };
  const group = (label: string, values: Array<[string, string]>, key: string, active: string) => ({ label, options: values.map(([value, labelText], index) => ({ label: labelText, href: href({ [key]: value }), active: active === value, isDefault: index === 0 })) });
  return <WorkspaceListPage><div className="flex min-h-0 flex-col gap-3"><SuperAdminPageHeaderRegistration context={{ title: "เอกสารดาวน์โหลด", description: `จัดการเอกสารดาวน์โหลดของ ${village.name} เพื่อการสนับสนุนงานหมู่บ้าน` }} /><AdminListToolbar sticky hideHeading compact title="เอกสารดาวน์โหลด" description="ค้นหาและจัดการเอกสารของหมู่บ้าน" searchAction={`/superadmin/villages/${villageId}/downloads`} clearHref={`/superadmin/villages/${villageId}/downloads`} keyword={keyword} searchPlaceholder="ค้นหาชื่อเอกสารหรือรายละเอียด" suggestionTitles={files.map((file) => file.title).slice(0, 12)} hiddenInputs={{ stage: stage === "ALL" ? "" : stage, category: category === "ALL" ? "" : category, visibility: visibility === "ALL" ? "" : visibility, sort: sort === "newest" ? "" : sort }} groups={[group("สถานะ", [["ALL", "ทั้งหมด"], ["DRAFT", "ร่าง"], ["PUBLISHED", "เผยแพร่"], ["ARCHIVED", "จัดเก็บ"]], "stage", stage), group("หมวดหมู่", [["ALL", "ทั้งหมด"], ...DOWNLOAD_CATEGORY_OPTIONS.map((item) => [item.value, item.label] as [string, string])], "category", category), group("การมองเห็น", [["ALL", "ทั้งหมด"], ["PUBLIC", "สาธารณะ"], ["RESIDENT_ONLY", "เฉพาะลูกบ้าน"]], "visibility", visibility), group("เรียงลำดับ", [["newest", "ล่าสุดก่อน"], ["oldest", "เก่าก่อน"], ["downloads", "ดาวน์โหลดสูงสุด"]], "sort", sort)]} actions={<Link href={`/superadmin/villages/${villageId}/downloads/new`}><Button size="sm"><Plus className="mr-1 h-4 w-4" />เพิ่มเอกสาร</Button></Link>} />{files.length === 0 ? <div className="rounded-xl border border-gray-200 bg-white p-10 text-center"><Files className="mx-auto mb-3 h-10 w-10 text-gray-300" /><p className="text-gray-700">ไม่พบเอกสารตามเงื่อนไข</p></div> : <div className="space-y-2">{files.map((file) => { const size = file.attachments.reduce((sum, item) => sum + item.fileSize, 0); return <Link key={file.id} href={`/superadmin/villages/${villageId}/downloads/${file.id}`} className="block rounded-xl border border-gray-200 bg-white p-4 transition-shadow hover:shadow-md sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><Badge variant={file.stage === "PUBLISHED" ? "success" : file.stage === "DRAFT" ? "warning" : "default"}>{DOWNLOAD_STAGE_LABELS[file.stage]}</Badge><p className="mt-2 break-words text-base font-semibold text-gray-900">{file.title}</p>{file.description ? <p className="mt-1 line-clamp-2 break-words text-sm text-gray-500">{file.description}</p> : null}</div><time className="shrink-0 text-right text-xs text-gray-400">{(file.publishedAt ?? file.createdAt).toLocaleDateString("th-TH")}</time></div><div className="mt-3"><DownloadMetadata visibility={file.visibility} category={file.category} categoryLabel={file.categoryLabel} attachmentCount={file.attachments.length} totalSize={formatFileSize(size)} downloadCount={file.downloadCount} /></div></Link>; })}</div>}</div></WorkspaceListPage>;
}
