"use client";
import { useState } from "react";
import { Archive, Pencil, RotateCcw, Send, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { ActionReasonDialog } from "@/components/admin/action-reason-dialog";
import { useToast } from "@/components/ui/toast";
import { superAdminDeleteDownloadAction, superAdminTransitionDownloadAction } from "./actions";
export function SuperAdminDownloadActions({ villageId, fileId, stage }: { villageId: string; fileId: string; stage: "DRAFT" | "PUBLISHED" | "ARCHIVED" }) { const [action, setAction] = useState<"stage" | "delete" | null>(null); const [pending, setPending] = useState(false); const router = useRouter(); const toast = useToast(); const next = stage === "PUBLISHED" ? "ARCHIVED" : stage === "ARCHIVED" ? "DRAFT" : "PUBLISHED"; const run = async (reason: string) => { setPending(true); const result = action === "delete" ? await superAdminDeleteDownloadAction(villageId, fileId, reason) : await superAdminTransitionDownloadAction(villageId, fileId, next, reason); setPending(false); if (!result.success) { toast.error("ดำเนินการไม่สำเร็จ", result.error); return; } toast.success("ดำเนินการเรียบร้อยแล้ว"); setAction(null); if (action === "delete") router.replace(`/superadmin/villages/${villageId}/downloads`); else router.refresh(); }; return <><div className="flex flex-wrap justify-end gap-2"><Link href={`/superadmin/villages/${villageId}/downloads/${fileId}/edit`}><Button size="sm" variant="outline"><Pencil className="mr-1 h-4 w-4" />แก้ไข</Button></Link><Button size="sm" disabled={pending} onClick={() => setAction("stage")}>{stage === "PUBLISHED" ? <Archive className="mr-1 h-4 w-4" /> : stage === "ARCHIVED" ? <RotateCcw className="mr-1 h-4 w-4" /> : <Send className="mr-1 h-4 w-4" />}{stage === "PUBLISHED" ? "จัดเก็บ" : stage === "ARCHIVED" ? "คืนเป็นร่าง" : "เผยแพร่"}</Button><Button size="sm" variant="danger" disabled={pending} onClick={() => setAction("delete")}><Trash2 className="mr-1 h-4 w-4" />ลบ</Button></div><ActionReasonDialog open={Boolean(action)} action="content.archive" title={action === "delete" ? "ยืนยันการลบเอกสาร" : "ยืนยันการเปลี่ยนสถานะเอกสาร"} description="การดำเนินการนี้จะถูกบันทึกใน Audit Log และแจ้งผู้ดูแลหมู่บ้าน" submitLabel="ยืนยัน" reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => setAction(null)} onSubmit={run} /></>; }
