import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { ImageCarousel } from "@/components/ui/image-carousel";
import { AdminPageToolbar } from "@/components/ui/admin-page-toolbar";
import { prisma } from "@/lib/prisma";
import { VILLAGE_PLACE_CATEGORY_LABELS } from "@/lib/constants";
import { parseVillagePlacePayload } from "@/lib/village-place";
import { SuperAdminPlaceRequestActions } from "../superadmin-place-request-actions";
export default async function SuperAdminPlaceRequestDetail({params}:{params:Promise<{villageId:string;requestId:string}>}){const {villageId,requestId}=await params;const db=(prisma as unknown as {villagePlaceSubmission:{findFirst:(args:unknown)=>Promise<any>}}).villagePlaceSubmission;const row=await db.findFirst({where:{id:requestId,villageId},include:{requester:{select:{name:true,phoneNumber:true}}}});if(!row)notFound();const payload=parseVillagePlacePayload(row.payload);if(!payload)notFound();const images=payload.images.sort((a,b)=>a.sortOrder-b.sortOrder).flatMap(image=>image.url?[image.url]:[]);return <div className="mx-auto w-full max-w-4xl space-y-4"><AdminPageToolbar sticky variant="request" backHref={`/superadmin/villages/${villageId}/places/requests`} backLabel="กลับคำขอสถานที่" title="รายละเอียดคำขอสถานที่" description="ตรวจสอบข้อมูลสถานที่และผู้ส่งคำขอ"/><article className="space-y-5 rounded-xl border bg-white p-4 sm:p-8"><div className="flex flex-wrap gap-2"><Badge variant="outline">{row.type}</Badge><Badge variant={row.status==="PENDING"?"warning":row.status==="APPROVED"?"success":"danger"}>{row.status}</Badge><Badge variant="outline">{VILLAGE_PLACE_CATEGORY_LABELS[payload.category]??payload.category}</Badge></div><h1 className="text-2xl font-bold">{payload.name}</h1><p className="text-sm text-gray-600">ผู้ส่ง: {row.requester.name} · {row.requester.phoneNumber}</p>{payload.description?<p className="whitespace-pre-wrap text-gray-700">{payload.description}</p>:null}<div className="grid gap-2 rounded-xl bg-gray-50 p-4 text-sm">{payload.address?<p>ที่อยู่: {payload.address}</p>:null}{payload.openingHours?<p>เวลาเปิด-ปิด: {payload.openingHours}</p>:null}{payload.contactPhone?<p>โทรศัพท์: {payload.contactPhone}</p>:null}{payload.latitude!=null&&payload.longitude!=null?<p>พิกัด: {payload.latitude}, {payload.longitude}</p>:null}</div>{images.length?<ImageCarousel images={images} altPrefix={payload.name}/>:null}{row.status==="PENDING"?<SuperAdminPlaceRequestActions villageId={villageId} submissionId={row.id}/>:<p className="text-sm text-gray-500">คำขอนี้ถูกดำเนินการแล้ว</p>}</article></div>}
