import Link from "next/link";
import { AuditAction, Prisma } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { getWorkspaceVillage } from "@/features/village-workspace/server/queries";

const pageSize = 25;

function reason(metadata: unknown) { if (!metadata || typeof metadata !== "object") return null; const data = metadata as { reason?: unknown; supportReason?: unknown }; return typeof data.reason === "string" ? data.reason : typeof data.supportReason === "string" ? data.supportReason : null; }
export default async function VillageAuditPage({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; action?: string; page?: string }> }) {
  await requireSuperAdminPageSession(); const { villageId } = await params; const search = await searchParams; const page = Math.max(1, Number(search.page) || 1); const q = search.q?.trim() ?? "";
  const where: Prisma.AuditLogWhereInput = { villageId, ...(search.action && search.action !== "ALL" ? { action: search.action as AuditAction } : {}), ...(q ? { OR: [{ resource: { contains: q, mode: "insensitive" } }, { resourceId: { contains: q, mode: "insensitive" } }, { user: { is: { name: { contains: q, mode: "insensitive" } } } }] } : {}) };
  const [village, logs, total] = await Promise.all([getWorkspaceVillage(villageId), prisma.auditLog.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize, select: { id: true, action: true, resource: true, resourceId: true, metadata: true, createdAt: true, user: { select: { name: true, systemRole: true } } } }), prisma.auditLog.count({ where })]);
  const base = `/superadmin/villages/${villageId}/audit`; const pages = Math.max(1, Math.ceil(total / pageSize)); const href = (next: number) => { const p = new URLSearchParams(); if (q) p.set("q", q); if (search.action) p.set("action", search.action); p.set("page", String(next)); return `${base}?${p}`; };
  return <div className="space-y-4"><div><h2 className="text-xl font-semibold text-slate-950">บันทึกการใช้งาน</h2><p className="mt-1 text-sm text-slate-500">Audit Log เฉพาะ {village.name}</p></div><form action={base} className="grid gap-2 rounded-xl border bg-white p-3 sm:grid-cols-[1fr_auto_auto]"><input type="search" name="q" defaultValue={q} placeholder="ค้นหาผู้ดำเนินการ resource หรือ ID" className="min-h-10 rounded-lg border px-3 text-sm" /><select name="action" defaultValue={search.action ?? "ALL"} className="min-h-10 rounded-lg border bg-white px-3 text-sm"><option value="ALL">ทุก action</option>{["CREATE","UPDATE","DELETE","APPROVE","REJECT"].map((item) => <option key={item}>{item}</option>)}</select><div className="flex gap-2"><button className="rounded-lg bg-slate-900 px-4 text-sm text-white">ค้นหา</button><Link href={base} className="inline-flex items-center rounded-lg border px-3 text-sm">ล้าง</Link></div></form>{logs.length ? <div className="overflow-hidden rounded-xl border bg-white"><div className="divide-y">{logs.map((log) => <article key={log.id} className="grid gap-2 p-4 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-start"><Badge variant="outline">{log.action}</Badge><div className="min-w-0"><p className="truncate font-medium text-slate-800">{log.resource} <span className="font-normal text-slate-400">{log.resourceId ?? ""}</span></p><p className="mt-1 text-xs text-slate-500">{log.user?.name ?? "ระบบ"} · {log.user?.systemRole ?? "SYSTEM"}</p>{reason(log.metadata) ? <p className="mt-2 text-sm text-slate-600">เหตุผล: {reason(log.metadata)}</p> : null}</div><time className="text-xs text-slate-400">{log.createdAt.toLocaleString("th-TH")}</time></article>)}</div></div> : <div className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">ไม่พบบันทึก</div>}<div className="flex items-center justify-between"><p className="text-xs text-slate-500">{total} รายการ · หน้า {page}/{pages}</p><div className="flex gap-2">{page > 1 ? <Link href={href(page - 1)} className="rounded-lg border px-3 py-2 text-sm">ก่อนหน้า</Link> : null}{page < pages ? <Link href={href(page + 1)} className="rounded-lg border px-3 py-2 text-sm">ถัดไป</Link> : null}</div></div></div>;
}
