import Link from "next/link";
import { AuditAction, MembershipStatus, Prisma } from "@prisma/client";
import { ClipboardList } from "lucide-react";
import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { auditActionLabel, formatAuditEvent } from "@/lib/audit-event";
import { getThaiRoleLabel } from "@/lib/user-display";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { getWorkspaceVillage } from "@/features/village-workspace/server/queries";
import { AuditEventList, type AuditListEvent } from "../../../../../(admin)/admin/security/audit-event-list";
import { WorkspaceListPage } from "../workspace-list-page";

const PAGE_SIZE = 25;
function bangkokDayKey(value: Date) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Bangkok", year: "numeric", month: "2-digit", day: "2-digit" }).format(value); }
function groupDate(value: Date) { const now = new Date(); const yesterday = new Date(now); yesterday.setDate(yesterday.getDate() - 1); if (bangkokDayKey(value) === bangkokDayKey(now)) return "วันนี้"; if (bangkokDayKey(value) === bangkokDayKey(yesterday)) return "เมื่อวาน"; return new Intl.DateTimeFormat("th-TH", { timeZone: "Asia/Bangkok", day: "numeric", month: "short", year: "numeric" }).format(value); }
function shortTime(value: Date) { return `${new Intl.DateTimeFormat("th-TH", { timeZone: "Asia/Bangkok", hour: "2-digit", minute: "2-digit", hour12: false }).format(value)} น.`; }
function fullAuditTime(value: Date) { return `${new Intl.DateTimeFormat("th-TH", { timeZone: "Asia/Bangkok", day: "numeric", month: "long", year: "numeric" }).format(value)} เวลา ${shortTime(value)}`; }
function metadataUserIds(metadata: unknown) { if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return []; const record = metadata as Record<string, unknown>; return [record.targetUserId, record.affectedUserId, record.userId, record.requesterId].filter((value): value is string => typeof value === "string" && value.length > 0); }
async function resolveTargetNames(villageId: string, logs: Array<{ id: string; resource: string; resourceId: string | null; metadata: Prisma.JsonValue | null }>) {
  const ids = (resource: string) => logs.filter((log) => log.resource === resource && log.resourceId).map((log) => log.resourceId!); const userIds = [...new Set([...ids("UserAccount"), ...logs.flatMap((log) => metadataUserIds(log.metadata))])];
  const [news, places, houses, people, galleries, downloads, events, issues, transparency, contacts, appointments, bindingRequests, users] = await Promise.all([
    prisma.news.findMany({ where: { villageId, id: { in: ids("News") } }, select: { id: true, title: true } }), prisma.villagePlace.findMany({ where: { villageId, id: { in: ids("VillagePlace") } }, select: { id: true, name: true } }), prisma.house.findMany({ where: { villageId, id: { in: ids("House") } }, select: { id: true, houseNumber: true } }), prisma.person.findMany({ where: { villageId, id: { in: ids("Person") } }, select: { id: true, firstName: true, lastName: true } }),
    prisma.galleryAlbum.findMany({ where: { villageId, id: { in: ids("GalleryAlbum") } }, select: { id: true, title: true } }), prisma.downloadFile.findMany({ where: { villageId, id: { in: ids("DownloadFile") } }, select: { id: true, title: true } }), prisma.villageEvent.findMany({ where: { villageId, id: { in: ids("VillageEvent") } }, select: { id: true, title: true } }), prisma.issue.findMany({ where: { villageId, id: { in: ids("Issue") } }, select: { id: true, title: true } }),
    prisma.transparencyRecord.findMany({ where: { villageId, id: { in: ids("TransparencyRecord") } }, select: { id: true, title: true } }), prisma.contactDirectory.findMany({ where: { villageId, id: { in: ids("ContactDirectory") } }, select: { id: true, name: true } }), prisma.appointment.findMany({ where: { villageId, id: { in: ids("Appointment") } }, select: { id: true, title: true, user: { select: { name: true } } } }), prisma.bindingRequest.findMany({ where: { villageId, id: { in: ids("BindingRequest") } }, select: { id: true, user: { select: { name: true } } } }), prisma.user.findMany({ where: { id: { in: userIds } }, select: { id: true, name: true } }),
  ]);
  const names = new Map<string, string>([...news.map((row) => [row.id, row.title] as const), ...places.map((row) => [row.id, row.name] as const), ...houses.map((row) => [row.id, `บ้านเลขที่ ${row.houseNumber}`] as const), ...people.map((row) => [row.id, `${row.firstName} ${row.lastName}`.trim()] as const), ...galleries.map((row) => [row.id, row.title] as const), ...downloads.map((row) => [row.id, row.title] as const), ...events.map((row) => [row.id, row.title] as const), ...issues.map((row) => [row.id, row.title] as const), ...transparency.map((row) => [row.id, row.title] as const), ...contacts.map((row) => [row.id, row.name] as const), ...appointments.map((row) => [row.id, `${row.title} · ${row.user.name}`] as const), ...bindingRequests.map((row) => [row.id, row.user.name] as const), ...users.map((row) => [row.id, row.name] as const)]);
  const usersById = new Map(users.map((row) => [row.id, row.name] as const));
  return new Map(logs.flatMap((log) => { const name = log.resourceId ? names.get(log.resourceId) : undefined; const metadataName = metadataUserIds(log.metadata).map((id) => usersById.get(id)).find(Boolean); return name || metadataName ? [[log.id, name ?? metadataName!] as const] : []; }));
}
function href(base: string, q: string, action: string, page?: number) { const params = new URLSearchParams(); if (q) params.set("q", q); if (action !== "ALL") params.set("action", action); if (page && page > 1) params.set("page", String(page)); const query = params.toString(); return query ? `${base}?${query}` : base; }

export default async function VillageAuditPage({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; action?: string; page?: string }> }) {
  await requireSuperAdminPageSession(); const { villageId } = await params; const search = await searchParams; const base = `/superadmin/villages/${villageId}/audit`; const q = search.q?.trim() ?? "";
  const action = Object.values(AuditAction).includes(search.action as AuditAction) ? search.action as AuditAction : "ALL"; const page = Math.max(1, Number(search.page) || 1);
  const where: Prisma.AuditLogWhereInput = { villageId, ...(action !== "ALL" ? { action } : {}), ...(q ? { OR: [{ resource: { contains: q, mode: "insensitive" } }, { resourceId: { contains: q, mode: "insensitive" } }, { user: { is: { name: { contains: q, mode: "insensitive" } } } }] } : {}) };
  const [village, logs, total, allTotal, actions] = await Promise.all([getWorkspaceVillage(villageId), prisma.auditLog.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE, select: { id: true, action: true, resource: true, resourceId: true, metadata: true, createdAt: true, user: { select: { name: true, systemRole: true, memberships: { where: { villageId, status: MembershipStatus.ACTIVE }, select: { role: true }, take: 1 } } } } }), prisma.auditLog.count({ where }), prisma.auditLog.count({ where: { villageId } }), prisma.auditLog.findMany({ where: { villageId }, select: { action: true }, distinct: ["action"] })]);
  const targetNames = await resolveTargetNames(villageId, logs);
  const events = logs.map((log) => { const formatted = formatAuditEvent(log); const isSuperAdmin = formatted.isSuperAdminIntervention || log.user?.systemRole === "SUPERADMIN"; const role = isSuperAdmin ? "SUPERADMIN" : log.user?.memberships[0]?.role ?? log.user?.systemRole; const actor = log.user?.name?.trim() ? `${log.user.name.trim()} (${getThaiRoleLabel(role)})` : "ระบบ"; const actorRole = log.user ? getThaiRoleLabel(role) : "ระบบ"; const target = targetNames.get(log.id) ?? formatted.targetFromMetadata ?? formatted.resourceLabel; return { id: log.id, actor, actorRole, event: formatted.label, item: target, referenceId: log.resourceId, time: log.createdAt.toISOString(), formattedTime: fullAuditTime(log.createdAt), shortTime: shortTime(log.createdAt), dateGroup: groupDate(log.createdAt), icon: formatted.icon, tone: formatted.tone, changes: formatted.changes, reason: formatted.reason, reasonLabel: isSuperAdmin ? "เหตุผลในการดำเนินการแทน" : "เหตุผล" } satisfies AuditListEvent; });
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE)); const actionValues = actions.map((item) => item.action).sort((a, b) => Object.values(AuditAction).indexOf(a) - Object.values(AuditAction).indexOf(b)); const actionOptions = [{ label: "ทุกการดำเนินการ", value: "ALL" }, ...actionValues.map((value) => ({ label: auditActionLabel(value), value }))]; const title = "บันทึกการใช้งาน"; const description = `ตรวจสอบประวัติการดำเนินงานของ ${village.name}`;
  return <WorkspaceListPage><div className="flex min-h-0 flex-col gap-3"><SuperAdminPageHeaderRegistration priority={1} context={{ title, description }} /><AdminListToolbar sticky hideHeading compact title={title} description={description} searchAction={base} clearHref={base} keyword={q} searchLabel="ค้นหาบันทึก" searchPlaceholder="ค้นหาผู้ดำเนินการ รายการ หรือรหัสอ้างอิง" hiddenInputs={{ action: action === "ALL" ? "" : action }} groups={[{ label: "การดำเนินการ", options: actionOptions.map((option) => ({ label: option.label, href: href(base, q, option.value), active: action === option.value, isDefault: option.value === "ALL" })) }]} />}{events.length ? <AuditEventList events={events} /> : <div className="rounded-xl border border-gray-200 bg-white px-4 py-12 text-center"><ClipboardList aria-hidden="true" className="mx-auto mb-3 h-10 w-10 text-gray-300" /><p className="font-medium text-gray-700">{allTotal ? "ไม่พบบันทึกที่ตรงกับเงื่อนไข" : "ยังไม่มีบันทึกการใช้งาน"}</p><p className="mt-1 text-sm text-gray-500">ประวัติการดำเนินงานของหมู่บ้านจะแสดงที่นี่</p></div>}{total ? <nav className="flex flex-wrap items-center justify-between gap-3" aria-label="แบ่งหน้าบันทึกการใช้งาน"><span className="text-sm text-gray-500">{total.toLocaleString("th-TH")} รายการ · หน้าละ {PAGE_SIZE} รายการ</span><div className="flex gap-2">{page > 1 ? <Link href={href(base, q, action, page - 1)} className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">ก่อนหน้า</Link> : null}{page < pages ? <Link href={href(base, q, action, page + 1)} className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">ถัดไป</Link> : null}</div></nav> : null}</div></WorkspaceListPage>;
}
