import Link from "next/link";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { prisma } from "@/lib/prisma";
import { getVillageMembers, getWorkspaceVillage } from "@/features/village-workspace/server/queries";
import { MemberList } from "../member-list";

export default async function VillageUsersPage({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; role?: string; status?: string; page?: string }> }) {
  await requireSuperAdminPageSession(); const { villageId } = await params; const search = await searchParams;
  const filters = { query: search.q, role: search.role, status: search.status, page: Number(search.page) || 1 };
  const [village, result, houses] = await Promise.all([getWorkspaceVillage(villageId), getVillageMembers(villageId, filters), prisma.house.findMany({ where: { villageId }, orderBy: { houseNumber: "asc" }, select: { id: true, houseNumber: true } })]);
  const base = `/superadmin/villages/${villageId}/users`; const kept = new URLSearchParams(); if (search.q) kept.set("q", search.q); if (search.role) kept.set("role", search.role); if (search.status) kept.set("status", search.status); const queryString = kept.size ? `?${kept}` : "";
  return <div className="space-y-4"><div><h2 className="text-xl font-semibold text-slate-950">สมาชิก</h2><p className="mt-1 text-sm text-slate-500">สมาชิกทั้งหมด {result.total.toLocaleString("th-TH")} คน เฉพาะในหมู่บ้านนี้</p></div><form action={base} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 sm:grid-cols-[minmax(12rem,1fr)_auto_auto_auto]"><input type="search" name="q" defaultValue={search.q} placeholder="ค้นหาชื่อ เบอร์โทร หรือบ้านเลขที่" className="min-h-10 min-w-0 rounded-lg border border-slate-300 px-3 text-sm" /><select name="role" defaultValue={search.role ?? "ALL"} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">ทุกบทบาท</option><option value="RESIDENT">ลูกบ้าน</option><option value="HEADMAN">ผู้ใหญ่บ้าน</option><option value="ASSISTANT_HEADMAN">ผู้ช่วยผู้ใหญ่บ้าน</option><option value="COMMITTEE">คณะกรรมการ</option></select><select name="status" defaultValue={search.status ?? "ALL"} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">ทุกสถานะ</option><option value="ACTIVE">ใช้งานอยู่</option><option value="PENDING">รอตรวจสอบ</option><option value="SUSPENDED">ระงับ</option><option value="REJECTED">ไม่อนุมัติ</option></select><div className="flex gap-2"><button className="min-h-10 rounded-lg bg-slate-900 px-4 text-sm font-medium text-white">ค้นหา</button><Link href={base} className="inline-flex min-h-10 items-center rounded-lg border px-3 text-sm">ล้าง</Link></div></form><MemberList {...result} villageId={villageId} villageName={village.name} houses={houses} queryString={queryString} returnTo="users" /></div>;
}
