import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { getVillageMembers, getWorkspaceVillage } from "@/features/village-workspace/server/queries";
import { MemberList } from "../member-list";
import { WorkspaceListPage } from "../workspace-list-page";

export default async function VillageUsersPage({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; role?: string; status?: string }> }) {
  await requireSuperAdminPageSession(); const { villageId } = await params; const search = await searchParams; const base = `/superadmin/villages/${villageId}/users`; const keyword = (search.q ?? "").trim(); const role = search.role ?? "ALL"; const status = search.status ?? "ALL";
  const [village, result, houses] = await Promise.all([getWorkspaceVillage(villageId), getVillageMembers(villageId, { query: keyword, role, status }), prisma.house.findMany({ where: { villageId }, orderBy: { houseNumber: "asc" }, select: { id: true, houseNumber: true } })]);
  const href = (nextRole = role, nextStatus = status) => { const query = new URLSearchParams(); if (keyword) query.set("q", keyword); if (nextRole !== "ALL") query.set("role", nextRole); if (nextStatus !== "ALL") query.set("status", nextStatus); const value = query.toString(); return value ? `${base}?${value}` : base; };
  return <WorkspaceListPage><div className="flex min-h-0 flex-col gap-2 sm:h-[calc(100dvh-var(--app-topbar-visible-offset,4rem)-2rem)]"><SuperAdminPageHeaderRegistration priority={1} context={{ title: "สมาชิก", description: `สมาชิกทั้งหมด ${result.total.toLocaleString("th-TH")} คน · เฉพาะในหมู่บ้านนี้` }} /><AdminListToolbar sticky hideHeading title="สมาชิก" description={`สมาชิกทั้งหมด ${result.total.toLocaleString("th-TH")} คน · เฉพาะในหมู่บ้านนี้`} searchAction={base} clearHref={base} keyword={keyword} searchLabel="ค้นหาสมาชิก" searchPlaceholder="ค้นหาชื่อ เบอร์โทร หรือบ้านเลขที่" groups={[{ label: "บทบาท", options: [{ label: "ทุกบทบาท", href: href("ALL", status), active: role === "ALL", isDefault: true }, { label: "ลูกบ้าน", href: href("RESIDENT", status), active: role === "RESIDENT" }, { label: "ผู้ใหญ่บ้าน", href: href("HEADMAN", status), active: role === "HEADMAN" }, { label: "ผู้ช่วยผู้ใหญ่บ้าน", href: href("ASSISTANT_HEADMAN", status), active: role === "ASSISTANT_HEADMAN" }] }, { label: "สถานะ", options: [{ label: "ทุกสถานะ", href: href(role, "ALL"), active: status === "ALL", isDefault: true }, { label: "ใช้งานอยู่", href: href(role, "ACTIVE"), active: status === "ACTIVE" }, { label: "รอตรวจสอบ", href: href(role, "PENDING"), active: status === "PENDING" }, { label: "ระงับ", href: href(role, "SUSPENDED"), active: status === "SUSPENDED" }] }]} /><MemberList {...result} villageId={villageId} villageName={village.name} houses={houses} returnTo="users" /></div></WorkspaceListPage>;
}
