"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, RotateCcw, Send, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ActionReasonDialog } from "@/components/admin/action-reason-dialog";
import { useToast } from "@/components/ui/toast";
import { archiveTransparencyAction, deleteTransparencyAction, publishTransparencyAction, republishTransparencyAction } from "../actions";

type Props = { transparencyId: string; title: string; visibilityLabel: string; stage: "DRAFT" | "PUBLISHED" | "ARCHIVED" };
type Dialog = "publish" | "archive" | "delete" | null;
export function TransparencyLifecycleActions({ transparencyId, title, visibilityLabel, stage }: Props) {
  const router = useRouter(); const toast = useToast(); const [dialog, setDialog] = useState<Dialog>(null); const [pending, setPending] = useState(false);
  const config = dialog === "publish" ? { heading: "เผยแพร่ข้อมูลความโปร่งใส", text: <>รายการ: <strong>{title}</strong><br />การมองเห็น: <strong>{visibilityLabel}</strong><br /><span className="mt-3 block">เมื่อเผยแพร่แล้ว ผู้ที่มีสิทธิ์จะสามารถเห็นข้อมูลรายการนี้ได้</span></>, confirm: "ยืนยันเผยแพร่", action: publishTransparencyAction, success: "เผยแพร่รายการเรียบร้อยแล้ว", failure: "ไม่สามารถเผยแพร่รายการได้" } : dialog === "archive" ? { heading: "จัดเก็บรายการนี้?", text: <>รายการจะไม่แสดงต่อประชาชนหรือลูกบ้าน แต่ข้อมูลจะยังคงอยู่ในระบบ</>, confirm: "จัดเก็บ", action: archiveTransparencyAction, success: "จัดเก็บรายการแล้ว", failure: "ไม่สามารถจัดเก็บรายการได้" } : { heading: "ลบฉบับร่าง?", text: <>การดำเนินการนี้ไม่สามารถย้อนกลับได้</>, confirm: "ลบฉบับร่าง", action: deleteTransparencyAction, success: "ลบฉบับร่างเรียบร้อยแล้ว", failure: "ไม่สามารถลบฉบับร่างได้" };
  const execute = async (reason = "") => { setPending(true); const result = dialog === "archive" ? await archiveTransparencyAction(transparencyId, reason) : dialog === "delete" ? await deleteTransparencyAction(transparencyId, reason) : await publishTransparencyAction(transparencyId); setPending(false); if (!result.success) { toast.error(config.failure, result.error); return; } toast.success(config.success); const completed = dialog; setDialog(null); if (completed === "delete") router.push("/admin/transparency"); else router.refresh(); };
  const republish = async () => { setPending(true); const result = await republishTransparencyAction(transparencyId); setPending(false); if (!result.success) { toast.error("ไม่สามารถนำรายการกลับมาเผยแพร่ได้", result.error); return; } toast.success("นำรายการกลับมาเผยแพร่แล้ว"); router.refresh(); };
  return <><div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row">{stage !== "ARCHIVED" ? <Button size="sm" variant="outline" onClick={() => router.push(`/admin/transparency/${transparencyId}/edit`)}>แก้ไข</Button> : null}{stage === "DRAFT" ? <><Button size="sm" onClick={() => setDialog("publish")}><Send className="mr-1 h-4 w-4" />เผยแพร่</Button><Button size="sm" variant="dangerOutline" onClick={() => setDialog("delete")}><Trash2 className="mr-1 h-4 w-4" />ลบฉบับร่าง</Button></> : null}{stage === "PUBLISHED" ? <Button size="sm" variant="outline" onClick={() => setDialog("archive")}><Archive className="mr-1 h-4 w-4" />จัดเก็บ</Button> : null}{stage === "ARCHIVED" ? <Button size="sm" isLoading={pending} disabled={pending} onClick={republish}><RotateCcw className="mr-1 h-4 w-4" />นำกลับมาเผยแพร่</Button> : null}</div>{dialog === "publish" ? <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-labelledby="transparency-dialog-title"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><h2 id="transparency-dialog-title" className="text-lg font-semibold text-gray-900">{config.heading}</h2><div className="mt-2 text-sm leading-6 text-slate-600">{config.text}</div><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="outline" disabled={pending} onClick={() => setDialog(null)}>ยกเลิก</Button><Button isLoading={pending} onClick={() => { void execute(); }}>{config.confirm}</Button></div></div></div> : null}<ActionReasonDialog open={dialog === "archive"} action="content.archive" title={config.heading} description="รายการจะไม่แสดงต่อประชาชนหรือลูกบ้าน และเหตุผลจะถูกบันทึกใน Audit Log" submitLabel={config.confirm} loading={pending} onCancel={() => setDialog(null)} onSubmit={execute} /><ActionReasonDialog open={dialog === "delete"} action="content.delete" title={config.heading} description="การลบไม่สามารถย้อนกลับได้ และเหตุผลจะถูกบันทึกใน Audit Log" submitLabel={config.confirm} loading={pending} onCancel={() => setDialog(null)} onSubmit={execute} /></>;
}
