import Link from "next/link";
import { ArrowRight, ClipboardCheck, Home, UserRound } from "lucide-react";
import { AdminPageToolbar } from "@/components/ui/admin-page-toolbar";
import { requireVillagePagePermission } from "@/lib/admin-permission.server";
import { getVillageDataQuality } from "@/features/data-quality/server/data-quality-service";

const number = (value: number) => value.toLocaleString("th-TH");
export default async function AdminDataQualityPage() {
  const context = await requireVillagePagePermission("data-quality.view", { callbackUrl: "/admin/data-quality" });
  const data = await getVillageDataQuality(context.villageId);
  return <div data-admin-compact-top className="space-y-4"><AdminPageToolbar compact sticky title="คุณภาพข้อมูล" description="ตรวจสอบข้อมูลบัญชีและสมาชิกที่ควรได้รับการตรวจสอบภายในหมู่บ้าน" />
    <section className="grid gap-3 sm:grid-cols-3" aria-label="สรุปรายการที่ต้องตรวจสอบ"><Summary label="รายการที่ต้องตรวจสอบ" value={data.issueCount} detail="ตามเกณฑ์ที่ระบบตรวจสอบ" icon={ClipboardCheck} /><Summary label="บัญชีที่ต้องตรวจสอบข้อมูลซ้ำ" value={data.duplicateCount} detail="บัญชีที่ถูกระบุว่ามีข้อมูลซ้ำ" icon={UserRound} /><Summary label="ลูกบ้านที่ยังไม่มีบ้านผูก" value={data.residentWithoutHouseCount} detail="สมาชิกสถานะใช้งานที่ยังไม่มีบ้านผูก" icon={Home} /></section>
    {data.issueCount === 0 ? <section className="rounded-xl border border-gray-200 bg-white px-5 py-12 text-center shadow-sm"><ClipboardCheck className="mx-auto h-8 w-8 text-emerald-600" /><h2 className="mt-3 text-lg font-semibold text-gray-900">ยังไม่พบข้อมูลที่ต้องตรวจสอบ</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-gray-500">ระบบยังไม่พบรายการที่เข้าข่ายตามเกณฑ์ที่ตรวจสอบในขณะนี้</p></section> : <section className="grid gap-4 lg:grid-cols-2"><Issue title="บัญชีที่ต้องตรวจสอบข้อมูลซ้ำ" count={data.duplicateCount} detail="บัญชีที่ถูกระบุว่ามีข้อมูลซ้ำและยังไม่ได้คลี่คลาย" href="/admin/settings/access" icon={UserRound}>{data.duplicates.map((user) => <p key={user.id} className="break-words py-3 text-sm font-medium text-gray-800">{user.name}<span className="ml-2 text-xs font-normal text-gray-500">ข้อมูลบัญชีซ้ำ</span></p>)}</Issue><Issue title="ลูกบ้านที่ยังไม่มีบ้านผูก" count={data.residentWithoutHouseCount} detail="สมาชิกผู้พักอาศัยที่ใช้งานอยู่แต่ยังไม่มีบ้านผูก" href="/admin/population/binding-requests" icon={Home}>{data.residentsWithoutHouse.map((membership) => <p key={membership.id} className="break-words py-3 text-sm font-medium text-gray-800">{membership.user.name}</p>)}</Issue></section>}
  </div>;
}

function Summary({ label, value, detail, icon: Icon }: { label: string; value: number; detail: string; icon: typeof ClipboardCheck }) { return <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-sm text-gray-600">{label}</p><p className="mt-2 text-3xl font-semibold text-gray-950">{number(value)}</p></div><span className="rounded-lg bg-green-50 p-2.5 text-green-700"><Icon className="h-5 w-5" /></span></div><p className="mt-3 text-xs text-gray-500">{detail}</p></div>; }
function Issue({ title, count, detail, href, icon: Icon, children }: { title: string; count: number; detail: string; href: string; icon: typeof ClipboardCheck; children: React.ReactNode }) { return <article className="flex min-w-0 flex-col rounded-xl border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 p-4"><div className="flex gap-3"><span className="rounded-lg bg-gray-100 p-2 text-gray-700"><Icon className="h-5 w-5" /></span><div className="min-w-0"><h2 className="break-words font-semibold text-gray-900">{title}</h2><p className="mt-1 text-2xl font-semibold">{number(count)} <span className="text-sm font-normal text-gray-500">รายการ</span></p><p className="mt-1 text-sm text-gray-500">{detail}</p></div></div></div><div className="min-h-28 divide-y px-4">{count ? children : <p className="py-5 text-sm text-gray-500">ไม่พบรายการตามเกณฑ์นี้</p>}</div><div className="border-t p-4"><Link href={href} className="inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-lg border border-gray-200 text-sm font-medium text-green-700 hover:bg-green-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-600">เปิดพื้นที่จัดการ <ArrowRight className="h-4 w-4" /></Link></div></article>; }
