import Link from "next/link";
import { Download, FileText } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { DownloadVisibilityMetadata } from "@/components/downloads/download-metadata";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { DOWNLOAD_STAGE_LABELS } from "@/lib/downloads/constants";
import { downloadTypeLabel } from "@/lib/download-upload";
import { formatFileSize } from "@/lib/utils";
import { prisma } from "@/lib/prisma";
import { SuperAdminDownloadActions } from "../superadmin-download-actions";
export default async function Page({ params }: { params: Promise<{ villageId: string; fileId: string }> }) { const { villageId, fileId } = await params; const file = await prisma.downloadFile.findFirst({ where: { id: fileId, villageId }, include: { attachments: { orderBy: { sortOrder: "asc" } } } }); if (!file) notFound(); const totalSize = file.attachments.reduce((sum, item) => sum + item.fileSize, 0); return <div className="space-y-5"><SuperAdminPageHeaderRegistration context={{ title: file.title, description: "รายละเอียดเอกสารดาวน์โหลด" }} /><div className="flex flex-wrap items-center justify-between gap-3"><Link href={`/superadmin/villages/${villageId}/downloads`} className="text-sm text-gray-500">← กลับรายการเอกสาร</Link><SuperAdminDownloadActions villageId={villageId} fileId={file.id} stage={file.stage} /></div><section className="mx-auto w-full max-w-4xl space-y-6 rounded-xl border border-gray-200 bg-white p-5 sm:p-8"><div><Badge variant={file.stage === "PUBLISHED" ? "success" : file.stage === "DRAFT" ? "warning" : "default"}>{DOWNLOAD_STAGE_LABELS[file.stage]}</Badge><h1 className="mt-3 break-words text-2xl font-bold text-gray-900 sm:text-3xl">{file.title}</h1><div className="mt-2 flex flex-wrap gap-3 text-sm text-gray-500"><DownloadVisibilityMetadata visibility={file.visibility} category={file.category} categoryLabel={file.categoryLabel} /></div></div>{file.description ? <p className="whitespace-pre-wrap break-words leading-7 text-gray-700">{file.description}</p> : null}<div className="grid grid-cols-1 gap-3 border-y border-gray-200 py-3 text-sm sm:grid-cols-3"><div><p className="text-gray-500">ขนาดรวม</p><p className="font-medium">{formatFileSize(totalSize)}</p></div><div><p className="text-gray-500">ดาวน์โหลด</p><p className="font-medium">{file.downloadCount} ครั้ง</p></div><div><p className="text-gray-500">วันที่เผยแพร่</p><p className="font-medium">{file.publishedAt?.toLocaleDateString("th-TH") ?? "-"}</p></div></div><div><h2 className="mb-3 font-semibold">ไฟล์แนบ ({file.attachments.length})</h2><ul className="overflow-hidden rounded-xl border border-gray-200 divide-y divide-gray-100">{file.attachments.map((attachment) => <li key={attachment.id} className="flex min-w-0 flex-wrap items-center gap-3 px-3 py-3 sm:flex-nowrap sm:px-4"><FileText className="h-5 w-5 shrink-0 text-gray-400" /><div className="min-w-0 flex-1"><p className="break-words text-sm font-medium">{attachment.fileName}</p><p className="text-xs text-gray-500">{downloadTypeLabel(attachment.mimeType, attachment.fileName)} · {formatFileSize(attachment.fileSize)}</p></div><a href={`/api/downloads/${attachment.id}`} className="inline-flex min-h-11 shrink-0 items-center px-2 text-sm font-medium text-green-700"><Download className="mr-1 h-4 w-4" />ดาวน์โหลด</a></li>)}</ul></div></section></div>; }
