import Link from "next/link";
import { FileClock } from "lucide-react";
import { redirect } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { VILLAGE_PLACE_CATEGORY_LABELS, VILLAGE_PLACE_SUBMISSION_STATUS_LABELS, VILLAGE_PLACE_SUBMISSION_TYPE_LABELS } from "@/lib/constants";
import { prisma } from "@/lib/prisma";
import { getAdminMembership, getSessionContextFromServerCookies, isAdminUser } from "@/lib/access-control";
import { parseVillagePlacePayload } from "@/lib/village-place";

type RequestItem = { id: string; type: string; status: string; payload: unknown; createdAt: Date; reviewedBy: string | null; reviewedAt: Date | null; reviewNote: string | null; requester: { name: string; phoneNumber: string } };
type VillagePlaceSubmissionListDelegate = { findMany(args: unknown): Promise<RequestItem[]>; count(args: unknown): Promise<number> };
const statusVariant: Record<string, "default" | "info" | "success" | "warning" | "danger"> = { PENDING: "warning", APPROVED: "success", REJECTED: "danger" };

export default async function AdminPlaceRequestListPage({ searchParams }: { searchParams?: Promise<{ tab?: string }> }) {
  const session = await getSessionContextFromServerCookies(); if (!session?.id) redirect("/auth/login"); if (!isAdminUser(session)) redirect("/resident");
  const membership = getAdminMembership(session); if (!membership) redirect("/auth/login");
  const tab = (await searchParams)?.tab === "history" ? "history" : "pending";
  const villagePlaceSubmission = (prisma as unknown as { villagePlaceSubmission: VillagePlaceSubmissionListDelegate }).villagePlaceSubmission;
  const where = { villageId: membership.villageId, ...(tab === "pending" ? { status: "PENDING" } : { status: { in: ["APPROVED", "REJECTED"] } }) };
  const [requests, pendingCount] = await Promise.all([villagePlaceSubmission.findMany({ where, orderBy: [{ createdAt: "desc" }], include: { requester: { select: { name: true, phoneNumber: true } } } }), villagePlaceSubmission.count({ where: { villageId: membership.villageId, status: "PENDING" } })]);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-gray-900">คำขอสถานที่จากลูกบ้าน</h1><p className="mt-1 text-sm text-gray-500">ตรวจสอบคำขอเพิ่มหรือแก้ไขสถานที่จากลูกบ้าน</p></div><div className="flex gap-2 border-b border-gray-200"><Link href="/admin/places/requests" className={`border-b-2 px-3 py-2 text-sm font-medium ${tab === "pending" ? "border-green-700 text-green-800" : "border-transparent text-gray-500 hover:text-gray-700"}`}>รอพิจารณา ({pendingCount})</Link><Link href="/admin/places/requests?tab=history" className={`border-b-2 px-3 py-2 text-sm font-medium ${tab === "history" ? "border-green-700 text-green-800" : "border-transparent text-gray-500 hover:text-gray-700"}`}>ประวัติ</Link></div>{requests.length === 0 ? <div className="rounded-xl border border-gray-200 bg-white p-10 text-center"><FileClock className="mx-auto mb-3 h-10 w-10 text-gray-300" /><p className="font-medium text-gray-700">{tab === "pending" ? "ไม่มีคำขอที่รอพิจารณา" : "ยังไม่มีประวัติคำขอสถานที่"}</p></div> : <div className="space-y-2">{requests.map((request) => { const payload = parseVillagePlacePayload(request.payload); return <Link key={request.id} href={`/admin/places/requests/${request.id}`} className="block rounded-xl border border-gray-200 bg-white p-4 transition-shadow hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge variant="outline">{VILLAGE_PLACE_SUBMISSION_TYPE_LABELS[request.type] ?? request.type}</Badge><Badge variant={statusVariant[request.status] ?? "default"}>{VILLAGE_PLACE_SUBMISSION_STATUS_LABELS[request.status] ?? request.status}</Badge><Badge variant="outline">{VILLAGE_PLACE_CATEGORY_LABELS[payload?.category ?? "OTHER"]}</Badge></div><p className="truncate font-medium text-gray-900">{payload?.name ?? "ข้อมูลคำขอไม่ถูกต้อง"}</p><p className="mt-1 text-sm text-gray-500">ผู้ส่ง: {request.requester.name} • {request.requester.phoneNumber}</p>{tab === "history" && <p className="mt-1 text-xs text-gray-500">ผู้พิจารณา: {request.reviewedBy ?? "-"} • {request.reviewedAt ? new Date(request.reviewedAt).toLocaleString("th-TH") : "-"}{request.reviewNote ? ` • ${request.reviewNote}` : ""}</p>}</div><p className="shrink-0 whitespace-nowrap text-xs text-gray-400">{new Date(request.createdAt).toLocaleDateString("th-TH")}</p></div></Link>; })}</div>}</div>;
}
