import Link from "next/link";
import { Plus, SearchX, ShieldCheck } from "lucide-react";
import { Prisma } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { NEWS_VISIBILITY_LABELS, TRANSPARENCY_STAGE_LABELS } from "@/lib/constants";
import { prisma } from "@/lib/prisma";
import { WorkspaceListPage } from "../workspace-list-page";

const TAKE = 12;
const stageVariant: Record<string, "default" | "success" | "warning"> = { DRAFT: "warning", PUBLISHED: "success", ARCHIVED: "default" };

export default async function SuperAdminVillageTransparencyPage({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; status?: string; visibility?: string; sort?: string; year?: string; page?: string }> }) {
  const { villageId } = await params; const query = await searchParams; const keyword = query.q?.trim() ?? "";
  const activeStage = ["DRAFT", "PUBLISHED", "ARCHIVED"].includes(query.status ?? "") ? query.status! : "ALL"; const activeVisibility = ["PUBLIC", "RESIDENT_ONLY"].includes(query.visibility ?? "") ? query.visibility! : "ALL"; const activeSort = ["newest", "oldest", "amount"].includes(query.sort ?? "") ? query.sort! : "newest"; const year = query.year?.trim() ?? ""; const page = Math.max(1, Number.parseInt(query.page ?? "1", 10) || 1); const base = `/superadmin/villages/${villageId}/transparency`;
  const baseWhere: Prisma.TransparencyRecordWhereInput = { villageId }; const where: Prisma.TransparencyRecordWhereInput = { ...baseWhere, ...(activeStage !== "ALL" ? { stage: activeStage as Prisma.TransparencyRecordWhereInput["stage"] } : {}), ...(activeVisibility !== "ALL" ? { visibility: activeVisibility as Prisma.TransparencyRecordWhereInput["visibility"] } : {}), ...(year ? { fiscalYear: year } : {}), ...(keyword ? { OR: [{ title: { contains: keyword, mode: "insensitive" } }, { description: { contains: keyword, mode: "insensitive" } }, { category: { contains: keyword, mode: "insensitive" } }, { fiscalYear: { contains: keyword, mode: "insensitive" } }] } : {}) };
  const orderBy = activeSort === "oldest" ? [{ publishedAt: "asc" as const }, { createdAt: "asc" as const }] : activeSort === "amount" ? [{ amount: "desc" as const }, { createdAt: "desc" as const }] : [{ publishedAt: "desc" as const }, { createdAt: "desc" as const }];
  const [village, records, total, totalRecords, suggestions] = await Promise.all([prisma.village.findUnique({ where: { id: villageId }, select: { name: true } }), prisma.transparencyRecord.findMany({ where, orderBy, skip: (page - 1) * TAKE, take: TAKE, select: { id: true, title: true, category: true, amount: true, fiscalYear: true, stage: true, visibility: true, publishedAt: true, createdAt: true } }), prisma.transparencyRecord.count({ where }), prisma.transparencyRecord.count({ where: baseWhere }), prisma.transparencyRecord.findMany({ where: baseWhere, orderBy: { updatedAt: "desc" }, take: 12, select: { title: true } })]);
  const hasFilters = Boolean(keyword || year || activeStage !== "ALL" || activeVisibility !== "ALL" || activeSort !== "newest");
  const href = (next: { status?: string; visibility?: string; sort?: string; year?: string; page?: number }) => { const values = { status: activeStage, visibility: activeVisibility, sort: activeSort, year, ...next }; const params = new URLSearchParams(); if (keyword) params.set("q", keyword); if (values.status !== "ALL") params.set("status", values.status); if (values.visibility !== "ALL") params.set("visibility", values.visibility); if (values.sort !== "newest") params.set("sort", values.sort); if (values.year) params.set("year", values.year); if ((values.page ?? 1) > 1) params.set("page", String(values.page)); return params.size ? `${base}?${params}` : base; };
  const group = (label: string, values: Array<[string, string]>, key: "status" | "visibility" | "sort", active: string) => ({ label, options: values.map(([value, labelText], index) => ({ label: labelText, href: href({ [key]: value }), active: active === value, isDefault: index === 0 })) });
  const title = "ความโปร่งใส"; const description = `จัดการข้อมูลความโปร่งใสของ ${village?.name ?? "หมู่บ้าน"} เพื่อการสนับสนุนงานหมู่บ้าน`;
  return <WorkspaceListPage><div className="flex min-h-0 flex-col gap-3"><SuperAdminPageHeaderRegistration priority={1} context={{ title, description }} /><AdminListToolbar sticky hideHeading compact title={title} description={description} searchAction={base} clearHref={base} keyword={keyword} searchPlaceholder="ค้นหาชื่อรายการ หมวดหมู่ หรือปีงบประมาณ" suggestionTitles={suggestions.map(({ title: itemTitle }) => itemTitle)} hiddenInputs={{ status: activeStage === "ALL" ? "" : activeStage, visibility: activeVisibility === "ALL" ? "" : activeVisibility, sort: activeSort === "newest" ? "" : activeSort, year }} groups={[group("สถานะ", [["ALL", "ทั้งหมด"], ["DRAFT", "ฉบับร่าง"], ["PUBLISHED", "เผยแพร่"], ["ARCHIVED", "เก็บถาวร"]], "status", activeStage), group("การมองเห็น", [["ALL", "ทั้งหมด"], ["PUBLIC", "สาธารณะ"], ["RESIDENT_ONLY", "เฉพาะลูกบ้าน"]], "visibility", activeVisibility), group("เรียง", [["newest", "ล่าสุดก่อน"], ["oldest", "เก่าก่อน"], ["amount", "งบสูงก่อน"]], "sort", activeSort)]} extraFilters={<form action={base} className="flex items-center gap-2"><input type="hidden" name="q" value={keyword} /><input type="hidden" name="status" value={activeStage === "ALL" ? "" : activeStage} /><input type="hidden" name="visibility" value={activeVisibility === "ALL" ? "" : activeVisibility} /><input type="hidden" name="sort" value={activeSort === "newest" ? "" : activeSort} /><label htmlFor="transparency-year" className="sr-only">ปี / ปีงบประมาณ</label><input id="transparency-year" name="year" defaultValue={year} placeholder="ปี / ปีงบประมาณ" className="h-9 w-32 rounded-md border border-gray-300 px-2.5 text-sm outline-none focus:border-green-500 focus:ring-1 focus:ring-green-500" /></form>} actions={<Link href={`${base}/new`}><Button size="sm"><Plus className="mr-1 h-4 w-4" />เพิ่มรายการ</Button></Link>} />
      {records.length === 0 ? <div className="rounded-xl border border-gray-200 bg-white p-10 text-center">{hasFilters || totalRecords > 0 ? <SearchX className="mx-auto mb-3 h-10 w-10 text-gray-300" /> : <ShieldCheck className="mx-auto mb-3 h-10 w-10 text-gray-300" />}<p className="text-gray-700">{hasFilters || totalRecords > 0 ? "ไม่พบรายการที่ตรงกับเงื่อนไข" : "ยังไม่มีข้อมูลความโปร่งใส"}</p><p className="mt-1 text-sm text-gray-400">{hasFilters || totalRecords > 0 ? "ลองเปลี่ยนคำค้นหาหรือตัวกรอง" : "เพิ่มข้อมูลที่ต้องการเปิดเผยให้ประชาชนหรือลูกบ้านตรวจสอบ"}</p>{!hasFilters && totalRecords === 0 ? <Link className="mt-5 inline-block" href={`${base}/new`}><Button>เพิ่มรายการ</Button></Link> : null}</div> : <><div className="space-y-3">{records.map((record) => <Link key={record.id} href={`${base}/${record.id}`} className="block rounded-xl border border-gray-200 bg-white p-4 transition-shadow hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-600 focus-visible:ring-offset-2 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge variant={stageVariant[record.stage] ?? "default"}>{TRANSPARENCY_STAGE_LABELS[record.stage] ?? record.stage}</Badge><Badge variant="outline">{NEWS_VISIBILITY_LABELS[record.visibility] ?? record.visibility}</Badge>{record.fiscalYear ? <Badge variant="outline">ปี {record.fiscalYear}</Badge> : null}</div><p className="break-words font-medium text-gray-900">{record.title}</p><p className="mt-1 break-words text-sm text-gray-500">{record.category || "ไม่ระบุหมวดหมู่"}{record.amount != null ? ` • ${record.amount.toLocaleString("th-TH")} บาท` : ""}</p></div><time className="shrink-0 text-xs text-gray-400">{(record.publishedAt ?? record.createdAt).toLocaleDateString("th-TH")}</time></div></Link>)}</div>{total > TAKE ? <nav className="flex flex-wrap items-center justify-between gap-3" aria-label="เปลี่ยนหน้ารายการ"><p className="text-sm text-gray-500">หน้า {page} จาก {Math.ceil(total / TAKE)}</p><div className="flex gap-2">{page > 1 ? <Link href={href({ page: page - 1 })}><Button variant="outline" size="sm">ก่อนหน้า</Button></Link> : null}{page * TAKE < total ? <Link href={href({ page: page + 1 })}><Button variant="outline" size="sm">ถัดไป</Button></Link> : null}</div></nav> : null}</>}</div></WorkspaceListPage>;
}
