"use client";

import { useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ActionReasonDialog } from "@/components/admin/action-reason-dialog";
import { useToast } from "@/components/ui/toast";
import { superAdminDeleteTransparencyDataAction, superAdminSaveTransparencyDataAction } from "../public-content-actions";

export type TransparencyRecordInput = { id: string; title: string; description: string | null; category: string | null; amount: number | null; fiscalYear: string | null; stage: "DRAFT" | "PUBLISHED" | "ARCHIVED"; visibility: "PUBLIC" | "RESIDENT_ONLY" };
type Draft = { title: string; description: string; category: string; amount: string; fiscalYear: string; stage: TransparencyRecordInput["stage"]; visibility: TransparencyRecordInput["visibility"] };
const stageOptions = [{ value: "DRAFT", label: "ร่าง" }, { value: "PUBLISHED", label: "เผยแพร่" }, { value: "ARCHIVED", label: "เก็บถาวร" }];

function VisibilitySwitch({ defaultChecked }: { defaultChecked: boolean }) {
  return <label className="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-gray-200 px-4 py-3 transition hover:border-gray-300"><span className="min-w-0"><span className="block text-sm font-medium text-gray-900">เผยแพร่สาธารณะ</span><span className="mt-1 block text-xs leading-5 text-gray-500">เปิดเพื่อให้บุคคลทั่วไปสามารถเห็นรายการนี้ได้หลังเผยแพร่</span></span><span className="relative mt-0.5 inline-flex shrink-0"><input name="visibility" type="checkbox" value="PUBLIC" defaultChecked={defaultChecked} className="peer sr-only" /><span aria-hidden className="h-6 w-11 rounded-full bg-gray-200 transition peer-checked:bg-green-700 after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:after:translate-x-5" /></span></label>;
}

export function SuperAdminTransparencyForm({ villageId, initial, cancelHref }: { villageId: string; initial?: TransparencyRecordInput | null; cancelHref?: string }) {
  const router = useRouter(); const toast = useToast(); const submitting = useRef(false); const [draft, setDraft] = useState<Draft | null>(null); const [pending, setPending] = useState(false); const back = cancelHref ?? `/superadmin/villages/${villageId}/transparency`;
  const begin = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (submitting.current) return; const form = new FormData(event.currentTarget); const rawAmount = String(form.get("amount") ?? "").trim(); if (rawAmount && (!Number.isFinite(Number(rawAmount.replace(/,/g, ""))) || Number(rawAmount.replace(/,/g, "")) < 0)) { toast.error("จำนวนเงินไม่ถูกต้อง", "กรุณาระบุจำนวนเงินเป็นตัวเลขที่ไม่ติดลบ"); return; } setDraft({ title: String(form.get("title") ?? ""), description: String(form.get("description") ?? ""), category: String(form.get("category") ?? ""), amount: rawAmount, fiscalYear: String(form.get("fiscalYear") ?? ""), stage: String(form.get("stage") ?? "DRAFT") as Draft["stage"], visibility: form.get("visibility") === "PUBLIC" ? "PUBLIC" : "RESIDENT_ONLY" }); };
  const save = async (reason: string) => { if (!draft || submitting.current) return; submitting.current = true; setPending(true); try { const result = await superAdminSaveTransparencyDataAction(villageId, initial?.id ?? null, draft, reason); if (!result.success) { toast.error(result.error); return; } toast.success(initial ? "บันทึกการแก้ไขแล้ว" : "สร้างรายการแล้ว"); setDraft(null); router.replace(`/superadmin/villages/${villageId}/transparency`); } finally { submitting.current = false; setPending(false); } };
  return <><form onSubmit={begin} className="space-y-7 rounded-xl border border-gray-200 bg-white p-4 sm:p-6"><section className="space-y-4"><div><h2 className="font-semibold text-gray-900">ข้อมูลรายการ</h2><p className="mt-1 text-sm text-gray-500">ระบุรายละเอียดที่ช่วยให้ตรวจสอบข้อมูลได้ชัดเจน</p></div><Input name="title" label="ชื่อรายการ" defaultValue={initial?.title ?? ""} required /><Textarea name="description" label="รายละเอียด" rows={5} defaultValue={initial?.description ?? ""} /><Input name="category" label="หมวดหมู่" defaultValue={initial?.category ?? ""} /></section><section className="space-y-4 border-t border-gray-100 pt-6"><h2 className="font-semibold text-gray-900">ข้อมูลงบประมาณ</h2><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Input name="amount" label="จำนวนเงิน (บาท)" defaultValue={initial?.amount != null ? String(initial.amount) : ""} inputMode="decimal" placeholder="เช่น 120,000" /><Input name="fiscalYear" label="ปีงบประมาณ" defaultValue={initial?.fiscalYear ?? ""} placeholder="เช่น 2569" /></div></section><section className="space-y-4 border-t border-gray-100 pt-6"><div><h2 className="font-semibold text-gray-900">สถานะและการแสดงผล</h2><p className="mt-1 text-sm text-gray-500">กำหนดสถานะการเผยแพร่และผู้ที่เห็นรายการ</p></div><Select name="stage" label="สถานะ" defaultValue={initial?.stage ?? "DRAFT"} options={stageOptions} /><VisibilitySwitch defaultChecked={initial?.visibility !== "RESIDENT_ONLY"} /></section><div className="flex flex-col-reverse gap-3 border-t border-gray-100 pt-5 sm:flex-row sm:items-center"><Button type="button" variant="outline" onClick={() => router.push(back)}>ยกเลิก</Button><Button type="submit" disabled={pending} isLoading={pending}>{initial ? "บันทึกการแก้ไข" : "สร้างรายการ"}</Button></div></form><ActionReasonDialog open={Boolean(draft)} action="content.archive" title={initial ? "ยืนยันการแก้ไขรายการความโปร่งใส" : "ยืนยันการสร้างรายการความโปร่งใส"} description="การดำเนินการนี้จะถูกบันทึกใน Audit Log และแจ้งผู้ดูแลหมู่บ้าน" reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => { if (!pending) setDraft(null); }} onSubmit={save} /></>;
}

export function SuperAdminDeleteTransparencyButton({ villageId, recordId, title }: { villageId: string; recordId: string; title: string }) {
  const router = useRouter(); const toast = useToast(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false);
  const remove = async (reason: string) => { setPending(true); try { const result = await superAdminDeleteTransparencyDataAction(villageId, recordId, reason); if (!result.success) { toast.error(result.error); return; } toast.success("ลบรายการแล้ว"); setOpen(false); router.replace(`/superadmin/villages/${villageId}/transparency`); } finally { setPending(false); } };
  return <><Button type="button" size="sm" variant="danger" onClick={() => setOpen(true)} disabled={pending}>ลบ</Button><ActionReasonDialog open={open} action="content.delete" title="ยืนยันการลบรายการความโปร่งใส" description={`รายการ “${title}” จะถูกลบออก`} reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => { if (!pending) setOpen(false); }} onSubmit={remove} /></>;
}
