import Link from "next/link";
import { AlertCircle, Eye } from "lucide-react";
import { Prisma } from "@prisma/client";
import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { Button } from "@/components/ui/button";
import { QueryPagination } from "@/components/ui/query-pagination";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { IssueStatusIndicator } from "@/components/issues/issue-status-indicator";
import { ISSUE_CATEGORY_LABELS } from "@/lib/constants";
import { ISSUE_STATUS_META } from "@/lib/issues/status";
import { getIssuePriorityMeta } from "@/lib/issues/priority";
import { getUserDisplayName } from "@/lib/user-display";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { getWorkspaceVillage } from "@/features/village-workspace/server/queries";
import { WorkspaceListPage, WorkspaceTable, WorkspaceTableScroll } from "../workspace-list-page";

type Props = { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; stage?: string; category?: string; sort?: string; page?: string }> };
const pageSize = 25;
const date = (value: Date) => value.toLocaleDateString("th-TH", { year: "numeric", month: "short", day: "numeric" });

export default async function Page({ params, searchParams }: Props) {
  await requireSuperAdminPageSession();
  const { villageId } = await params; const search = await searchParams; const village = await getWorkspaceVillage(villageId);
  const keyword = search.q?.trim() ?? ""; const stage = search.stage === "OPEN" || search.stage === "WAITING" ? "PENDING" : search.stage === "CLOSED" ? "RESOLVED" : search.stage ?? "ALL"; const category = search.category ?? "ALL"; const sort = search.sort ?? "newest"; const page = Math.max(1, Number(search.page) || 1);
  const where: Prisma.IssueWhereInput = { villageId };
  if (stage === "PENDING") where.stage = { in: ["OPEN", "WAITING"] }; else if (stage === "RESOLVED") where.stage = { in: ["RESOLVED", "CLOSED"] }; else if (stage !== "ALL" && Object.hasOwn(ISSUE_STATUS_META, stage)) where.stage = stage as Prisma.IssueWhereInput["stage"];
  if (category !== "ALL" && Object.hasOwn(ISSUE_CATEGORY_LABELS, category)) where.category = category as Prisma.IssueWhereInput["category"];
  if (keyword) {
    const reporterIds = await prisma.user.findMany({ where: { memberships: { some: { villageId, status: "ACTIVE" } }, OR: [{ name: { contains: keyword, mode: "insensitive" } }, { phoneNumber: { contains: keyword } }] }, select: { id: true } });
    where.OR = [{ title: { contains: keyword, mode: "insensitive" } }, { description: { contains: keyword, mode: "insensitive" } }, { location: { contains: keyword, mode: "insensitive" } }, ...(reporterIds.length ? [{ reporterId: { in: reporterIds.map((row) => row.id) } }] : [])];
  }
  const orderBy = sort === "oldest" ? [{ createdAt: "asc" as const }] : sort === "priority" ? [{ priority: "desc" as const }, { createdAt: "desc" as const }] : [{ createdAt: "desc" as const }];
  const [issues, total, grouped] = await Promise.all([prisma.issue.findMany({ where, orderBy, skip: (page - 1) * pageSize, take: pageSize, select: { id: true, reporterId: true, title: true, category: true, priority: true, stage: true, createdAt: true, location: true } }), prisma.issue.count({ where }), prisma.issue.groupBy({ by: ["stage"], where: { villageId }, _count: true })]);
  const reporters = await prisma.user.findMany({ where: { id: { in: [...new Set(issues.map((issue) => issue.reporterId))] } }, select: { id: true, name: true, phoneNumber: true } }); const reporterById = new Map(reporters.map((row) => [row.id, row])); const counts = Object.fromEntries(grouped.map((row) => [row.stage, row._count])); const pending = (counts.OPEN ?? 0) + (counts.WAITING ?? 0); const resolved = (counts.RESOLVED ?? 0) + (counts.CLOSED ?? 0); const base = `/superadmin/villages/${villageId}/issues`;
  const href = (next: { stage?: string; category?: string; sort?: string }) => { const q = new URLSearchParams(); if (keyword) q.set("q", keyword); if (next.stage && next.stage !== "ALL") q.set("stage", next.stage); if (next.category && next.category !== "ALL") q.set("category", next.category); if (next.sort && next.sort !== "newest") q.set("sort", next.sort); return q.size ? `${base}?${q}` : base; };
  const stageOptions = [{ value: "ALL", label: "ทั้งหมด", count: Object.values(counts).reduce((a, b) => a + b, 0) }, { value: "PENDING", label: ISSUE_STATUS_META.PENDING.label, count: pending }, { value: "IN_PROGRESS", label: ISSUE_STATUS_META.IN_PROGRESS.label, count: counts.IN_PROGRESS ?? 0 }, { value: "RESOLVED", label: ISSUE_STATUS_META.RESOLVED.label, count: resolved }, { value: "REJECTED", label: ISSUE_STATUS_META.REJECTED.label, count: counts.REJECTED ?? 0 }];
  return <WorkspaceListPage><div className="flex min-h-0 flex-col gap-3 sm:h-[calc(100dvh-var(--app-topbar-visible-offset,4rem)-2rem)]"><SuperAdminPageHeaderRegistration priority={1} context={{ title: "ปัญหา", description: `ติดตามและจัดการปัญหาของ ${village.name} เพื่อการสนับสนุนงานหมู่บ้าน` }} /><AdminListToolbar sticky hideHeading title="ปัญหา" description="" searchAction={base} clearHref={base} keyword={keyword} searchPlaceholder="ค้นหาหัวข้อ ผู้แจ้ง เบอร์โทร สถานที่ หรือรายละเอียด" hiddenInputs={{ stage: stage === "ALL" ? "" : stage, category: category === "ALL" ? "" : category, sort: sort === "newest" ? "" : sort }} suggestionTitles={[...new Set(issues.map((issue) => issue.title))].slice(0, 12)} groups={[{ label: "สถานะ", options: stageOptions.map((item) => ({ label: `${item.label}${item.count ? ` (${item.count})` : ""}`, href: href({ stage: item.value, category, sort }), active: stage === item.value })) }, { label: "หมวดหมู่", options: [{ label: "ทั้งหมด", href: href({ stage, category: "ALL", sort }), active: category === "ALL" }, ...Object.entries(ISSUE_CATEGORY_LABELS).map(([value, label]) => ({ label, href: href({ stage, category: value, sort }), active: category === value }))] }, { label: "เรียง", options: [{ label: "ล่าสุดก่อน", href: href({ stage, category, sort: "newest" }), active: sort === "newest" }, { label: "เก่าก่อน", href: href({ stage, category, sort: "oldest" }), active: sort === "oldest" }, { label: "เร่งด่วนก่อน", href: href({ stage, category, sort: "priority" }), active: sort === "priority" }] }]} />
    <WorkspaceTable empty={!issues.length}>{!issues.length ? <div className="p-10 text-center"><AlertCircle className="mx-auto mb-3 h-12 w-12 text-slate-300" /><p className="font-medium text-slate-700">ไม่พบรายการปัญหา</p></div> : <><WorkspaceTableScroll><table className="w-full min-w-[760px] table-fixed text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-left text-xs font-semibold text-slate-500"><tr><th className="w-[35%] px-4 py-3">หัวข้อ</th><th className="hidden px-4 py-3 md:table-cell">ผู้แจ้ง</th><th className="hidden px-4 py-3 md:table-cell">หมวดหมู่</th><th className="hidden px-4 py-3 lg:table-cell">ความสำคัญ</th><th className="px-4 py-3">สถานะ</th><th className="hidden px-4 py-3 sm:table-cell">วันที่</th><th /></tr></thead><tbody>{issues.map((issue) => { const priority = getIssuePriorityMeta(issue.priority); const reporter = reporterById.get(issue.reporterId); return <tr key={issue.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="relative px-4 py-3"><span className={`absolute bottom-2 left-2 top-2 w-1 rounded-full ${priority.stripeClass}`} /><p className="truncate font-medium text-slate-900">{issue.title}</p>{issue.location ? <p className="truncate text-xs text-slate-500">{issue.location}</p> : null}</td><td className="hidden px-4 py-3 md:table-cell"><p className="truncate font-medium">{getUserDisplayName(reporter)}</p><p className="truncate text-xs text-slate-500">{reporter?.phoneNumber ?? "-"}</p></td><td className="hidden px-4 py-3 md:table-cell">{ISSUE_CATEGORY_LABELS[issue.category]}</td><td className="hidden px-4 py-3 lg:table-cell"><span className={`rounded-full px-2 py-1 text-xs ${priority.badgeClass}`}>{priority.label}</span></td><td className="px-4 py-3"><IssueStatusIndicator stage={issue.stage} /></td><td className="hidden px-4 py-3 text-slate-500 sm:table-cell">{date(issue.createdAt)}</td><td className="px-4 py-3 text-right"><Link href={`${base}/${issue.id}`}><Button size="sm" variant="outline"><Eye className="mr-1 h-3.5 w-3.5" />จัดการ</Button></Link></td></tr>; })}</tbody></table></WorkspaceTableScroll>{Math.ceil(total / pageSize) > 1 ? <footer className="border-t border-slate-200 px-4 py-2"><QueryPagination pathname={base} page={page} totalPages={Math.ceil(total / pageSize)} params={{ q: keyword || undefined, stage: stage !== "ALL" ? stage : undefined, category: category !== "ALL" ? category : undefined, sort: sort !== "newest" ? sort : undefined }} /></footer> : null}</>}</WorkspaceTable></div></WorkspaceListPage>;
}
