"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { ActionReasonDialog } from "@/components/admin/action-reason-dialog";
import { useToast } from "@/components/ui/toast";
import { deleteSuperAdminGalleryAlbumAction, deleteSuperAdminGalleryItemDataAction, reviewSuperAdminGallerySubmissionDataAction } from "../operational-actions";

export function SuperAdminDeleteAlbumButton({ villageId, albumId }: { villageId: string; albumId: string }) { const router = useRouter(); const toast = useToast(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const run = async (reason: string) => { setPending(true); const data = new FormData(); data.set("supportReason", reason); const result = await deleteSuperAdminGalleryAlbumAction(villageId, albumId, data); setPending(false); if (!result.success) { toast.error(result.error); return; } setOpen(false); toast.success(result.message); router.replace(`/superadmin/villages/${villageId}/gallery`); }; return <><Button variant="dangerOutline" size="sm" onClick={() => setOpen(true)}>ลบอัลบั้ม</Button><ActionReasonDialog open={open} action="content.delete" title="ลบอัลบั้ม" description="รูปภาพภายในอัลบั้มจะถูกลบทั้งหมด" reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => setOpen(false)} onSubmit={run} /></>; }

export function SuperAdminDeleteItemButton({ villageId, albumId, itemId }: { villageId: string; albumId: string; itemId: string }) { const router = useRouter(); const toast = useToast(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const run = async (reason: string) => { setPending(true); const result = await deleteSuperAdminGalleryItemDataAction(villageId, albumId, itemId, reason); setPending(false); if (!result.success) { toast.error(result.error); return; } setOpen(false); toast.success(result.message); router.refresh(); }; return <><Button variant="outline" size="sm" onClick={() => setOpen(true)}>ลบ</Button><ActionReasonDialog open={open} action="content.delete" title="ลบรูปภาพ" description="รูปภาพจะถูกลบและแจ้งผู้ดูแลหมู่บ้าน" reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => setOpen(false)} onSubmit={run} /></>; }

export function SuperAdminSubmissionReview({ villageId, submissionId }: { villageId: string; submissionId: string }) { const router = useRouter(); const toast = useToast(); const [decision, setDecision] = useState<"APPROVE" | "REJECT" | null>(null); const [businessReason, setBusinessReason] = useState<string | null>(null); const [pending, setPending] = useState(false); const run = async (supportReason: string) => { if (!decision) return; setPending(true); const result = await reviewSuperAdminGallerySubmissionDataAction(villageId, submissionId, decision, businessReason ?? "", supportReason); setPending(false); if (!result.success) { toast.error(result.error); return; } toast.success(result.message); setDecision(null); setBusinessReason(null); router.refresh(); }; return <><div className="flex flex-wrap gap-2"><Button variant="danger" disabled={pending} onClick={() => setDecision("REJECT")}>ไม่อนุมัติ</Button><Button disabled={pending} onClick={() => setDecision("APPROVE")}>อนุมัติ</Button></div><ActionReasonDialog open={decision === "REJECT" && businessReason === null} action="content.request.reject" title="เหตุผลที่ไม่อนุมัติรูปภาพ" description="เหตุผลนี้จะแจ้งแก่ผู้ส่งคำขอ และไม่ใช่เหตุผลในการดำเนินการของ Super Admin" reasonLabel="เหตุผลที่ไม่อนุมัติรูปภาพ" helperText="ระบุเหตุผลทางธุรกิจ 5–500 ตัวอักษร" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => setDecision(null)} onSubmit={async (reason) => setBusinessReason(reason)} /><ActionReasonDialog open={decision === "APPROVE" || (decision === "REJECT" && businessReason !== null)} action="content.request.reject" title={decision === "APPROVE" ? "ยืนยันการอนุมัติคำขอ" : "ยืนยันการปฏิเสธคำขอ"} description={decision === "REJECT" ? "ระบบจะบันทึกเหตุผลทางธุรกิจแยกจากเหตุผลการดำเนินการ" : "ระบบจะเพิ่มรูปภาพเข้าอัลบั้มและแจ้งผู้ส่งคำขอ"} reasonLabel="เหตุผลในการดำเนินการ" helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" requireReason minReasonLength={5} maxReasonLength={500} loading={pending} onCancel={() => { setDecision(null); setBusinessReason(null); }} onSubmit={run} /></>; }
