import Link from "next/link";
import { Clock } from "lucide-react";
import { Prisma } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { QueryPagination } from "@/components/ui/query-pagination";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { APPOINTMENT_STAGE_LABELS } from "@/lib/constants";
import { formatThaiDateTime } from "@/lib/utils";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { getWorkspaceVillage } from "@/features/village-workspace/server/queries";
import { WorkspaceListPage } from "../workspace-list-page";

type Props = { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; stage?: string; sort?: string; page?: string }> };
const stageVariant: Record<string, "default" | "info" | "success" | "warning" | "danger"> = { PENDING_APPROVAL: "warning", TIME_SUGGESTED: "info", APPROVED: "success", REJECTED: "danger", CANCELLED: "default", COMPLETED: "info" };
const pageSize = 25;
function slotDateTime(row: { scheduledAt: Date | null; slot: { date: Date; startTime: string } | null }) { if (!row.scheduledAt || !row.slot) return null; const [hours, minutes] = row.slot.startTime.split(":").map(Number); if (!Number.isInteger(hours) || !Number.isInteger(minutes)) return null; return new Date(Date.UTC(row.slot.date.getUTCFullYear(), row.slot.date.getUTCMonth(), row.slot.date.getUTCDate(), hours, minutes) - 7 * 60 * 60 * 1000); }

export default async function Page({ params, searchParams }: Props) {
  await requireSuperAdminPageSession(); const { villageId } = await params; const query = await searchParams; const village = await getWorkspaceVillage(villageId); const keyword = query.q?.trim() ?? ""; const validStages = ["PENDING_APPROVAL", "TIME_SUGGESTED", "APPROVED", "REJECTED", "CANCELLED", "COMPLETED"] as const; const stage = validStages.includes(query.stage as typeof validStages[number]) ? query.stage! : "ALL"; const sort = query.sort === "oldest" || query.sort === "upcoming" ? query.sort : "newest"; const page = Math.max(1, Number(query.page) || 1);
  const where: Prisma.AppointmentWhereInput = { villageId, ...(stage !== "ALL" ? { stage: stage as Prisma.AppointmentWhereInput["stage"] } : {}) }; if (keyword) where.OR = [{ title: { contains: keyword, mode: "insensitive" } }, { description: { contains: keyword, mode: "insensitive" } }, { user: { name: { contains: keyword, mode: "insensitive" } } }, { user: { phoneNumber: { contains: keyword } } }];
  const select = { id: true, title: true, description: true, stage: true, scheduledAt: true, createdAt: true, user: { select: { name: true, phoneNumber: true } }, slot: { select: { date: true, startTime: true, endTime: true } } } satisfies Prisma.AppointmentSelect;
  const [rows, count] = await Promise.all([prisma.appointment.findMany({ where, select, orderBy: { createdAt: "desc" } }), prisma.appointment.count({ where })]);
  const visible = sort === "upcoming" ? rows.filter((row) => row.stage === "APPROVED" && (slotDateTime(row)?.getTime() ?? 0) >= Date.now()).sort((a, b) => slotDateTime(a)!.getTime() - slotDateTime(b)!.getTime()) : sort === "oldest" ? [...rows].reverse() : rows; const total = sort === "upcoming" ? visible.length : count; const appointments = visible.slice((page - 1) * pageSize, page * pageSize); const base = `/superadmin/villages/${villageId}/appointments`;
  const href = (next: { stage?: string; sort?: string }) => { const params = new URLSearchParams(); if (keyword) params.set("q", keyword); if (next.stage && next.stage !== "ALL") params.set("stage", next.stage); if (next.sort && next.sort !== "newest") params.set("sort", next.sort); return params.size ? `${base}?${params}` : base; };
  const filters = [["ALL", "ทั้งหมด"], ["PENDING_APPROVAL", "รออนุมัติ"], ["TIME_SUGGESTED", "รอลูกบ้านยืนยันเวลา"], ["APPROVED", "อนุมัติแล้ว"], ["COMPLETED", "เสร็จสิ้น"]] as const;
  return <WorkspaceListPage><div className="flex min-h-0 flex-col gap-3"><SuperAdminPageHeaderRegistration priority={1} context={{ title: "นัดหมาย", description: `ติดตามและจัดการนัดหมายของ ${village.name} เพื่อการสนับสนุนงานหมู่บ้าน` }} /><AdminListToolbar sticky hideHeading title="นัดหมาย" description="" searchAction={base} clearHref={base} keyword={keyword} searchPlaceholder="ค้นหาหัวข้อ ผู้ขอนัด เบอร์โทร หรือรายละเอียด" hiddenInputs={{ stage: stage === "ALL" ? "" : stage, sort: sort === "newest" ? "" : sort }} suggestionTitles={[...new Set(appointments.map((row) => row.title))].slice(0, 12)} groups={[{ label: "สถานะ", options: filters.map(([value, label]) => ({ label, href: href({ stage: value, sort }), active: stage === value })) }, { label: "เรียง", countsAsFilter: false, options: [{ label: "สร้างล่าสุดก่อน", href: href({ stage, sort: "newest" }), active: sort === "newest" }, { label: "สร้างเก่าสุดก่อน", href: href({ stage, sort: "oldest" }), active: sort === "oldest" }, { label: "นัดหมายใกล้ถึงก่อน", href: href({ stage, sort: "upcoming" }), active: sort === "upcoming" }] }]} />{appointments.length ? <section className="space-y-3">{appointments.map((row) => { const scheduled = slotDateTime(row); const label = row.stage === "TIME_SUGGESTED" ? "รอลูกบ้านยืนยันเวลา" : APPOINTMENT_STAGE_LABELS[row.stage]; return <Link key={row.id} href={`${base}/${row.id}`} className="block rounded-xl border bg-white p-4 transition-shadow hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-600"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div className="min-w-0"><div className="mb-1.5 flex flex-wrap items-center gap-2"><p className="break-words text-base font-semibold text-slate-900 sm:text-lg">{row.title}</p><Badge variant={stageVariant[row.stage] ?? "default"}>{label}</Badge></div><p className="break-words text-sm text-slate-600"><span className="text-slate-500">ผู้ขอนัด: </span>{row.user.name || row.user.phoneNumber || "-"}</p>{row.description ? <p className="mt-1 line-clamp-1 text-sm text-slate-500">{row.description}</p> : null}</div><div className="space-y-1.5 text-sm lg:text-right">{scheduled ? <p className="flex items-center gap-1.5 font-medium text-slate-700 lg:justify-end"><Clock className="h-4 w-4 shrink-0 text-slate-500" />{["APPROVED", "COMPLETED"].includes(row.stage) ? "นัดหมาย" : "เสนอเวลา"}: {formatThaiDateTime(scheduled)}</p> : <p className="font-medium text-slate-600">ยังไม่กำหนดเวลา</p>}<p className="text-xs text-slate-400">สร้างเมื่อ {formatThaiDateTime(row.createdAt)}</p></div></div></Link>; })}</section> : <section className="rounded-xl border bg-white p-10 text-center text-slate-500">ไม่พบรายการนัดหมาย</section>}<QueryPagination pathname={base} page={page} totalPages={Math.max(1, Math.ceil(total / pageSize))} params={{ q: keyword || undefined, stage: stage !== "ALL" ? stage : undefined, sort: sort !== "newest" ? sort : undefined }} /></div></WorkspaceListPage>;
}
