"use client";

import { NewsFilterChip } from "@/components/news/news-toolbar";
import { ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
type VisibilityValue = "PUBLIC" | "RESIDENT_ONLY";
type SortValue = "date_desc" | "date_asc";
type Props = { keyword: string; selectedVisibilities: VisibilityValue[]; sort: SortValue; suggestionTitles: string[]; canViewResidentOnly: boolean };
function href({ visibilities, sort, keyword }: { visibilities: VisibilityValue[]; sort: SortValue; keyword: string }) { const query = new URLSearchParams(); const values = Array.from(new Set(visibilities)).sort(); if (values.length) query.set("visibility", values.join(",")); if (sort !== "date_desc") query.set("sort", sort); if (keyword.trim()) query.set("q", keyword.trim()); return query.size ? `/resident/transparency?${query}` : "/resident/transparency"; }
export function ResidentTransparencyToolbar({ keyword, selectedVisibilities, sort, suggestionTitles, canViewResidentOnly }: Props) { const has = (value: VisibilityValue) => selectedVisibilities.includes(value); const toggle = (value: VisibilityValue) => href({ visibilities: has(value) ? selectedVisibilities.filter((item) => item !== value) : [...selectedVisibilities, value], sort, keyword }); return <ResidentPageToolbar namespace="resident-transparency" title="ความโปร่งใส" search={{ keyword, placeholder: "พิมพ์หัวข้อความโปร่งใส", label: "ค้นหาข้อมูลความโปร่งใส", suggestions: suggestionTitles }} activeFilterCount={selectedVisibilities.length + Number(sort !== "date_desc")} filters={<>{canViewResidentOnly ? <><span className="text-xs font-semibold text-gray-500">การมองเห็น</span>{([['RESIDENT_ONLY','ข้อมูลในหมู่บ้าน'],['PUBLIC','ข้อมูลสาธารณะ']] as const).map(([value,label]) => <NewsFilterChip key={value} href={toggle(value)} active={has(value)}>{label}</NewsFilterChip>)}</> : null}<span className="ml-1 text-xs font-semibold text-gray-500">เรียงตามวันที่</span>{([['date_desc','ล่าสุดก่อน'],['date_asc','เก่าก่อน']] as const).map(([value,label]) => <NewsFilterChip key={value} href={href({ visibilities: selectedVisibilities, sort: value, keyword })} active={sort === value}>{label}</NewsFilterChip>)}</>} />; }
