"use client";

import Link from "next/link";
import { Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { NewsFilterChip } from "@/components/news/news-toolbar";
import { ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
import { ISSUE_CATEGORY_LABELS, ISSUE_PRIORITY_LABELS } from "@/lib/constants";
type ScopeValue = "mine" | "others";
type SortValue = "date_desc" | "date_asc" | "priority_desc" | "priority_asc";
type PriorityFilterValue = "ALL" | "LOW" | "MEDIUM" | "HIGH" | "URGENT";
type CategoryFilterValue = "ALL" | "ROAD" | "WATER" | "ELECTRICITY" | "SECURITY" | "WASTE" | "ENVIRONMENT" | "PUBLIC_HEALTH" | "OTHER";
type Props = { keyword: string; selectedScopes: ScopeValue[]; priorityFilter: PriorityFilterValue; categoryFilter: CategoryFilterValue; sort: string; suggestionTitles: string[] };
function href({ scopes, sort, keyword, priority, category }: { scopes: ScopeValue[]; sort: string; keyword: string; priority: PriorityFilterValue; category: CategoryFilterValue }) { const query = new URLSearchParams(); const values = Array.from(new Set(scopes)).sort(); if (values.length) query.set("scope", values.join(",")); if (priority !== "ALL") query.set("priority", priority); if (category !== "ALL") query.set("category", category); if (sort !== "date_desc") query.set("sort", sort); if (keyword.trim()) query.set("q", keyword.trim()); return query.size ? `/resident/issues?${query}` : "/resident/issues"; }
export function ResidentIssuesToolbar({ keyword, selectedScopes, priorityFilter, categoryFilter, sort, suggestionTitles }: Props) {
  const router = useRouter();
  const sortValue: SortValue = sort === "date_asc" || sort === "priority_desc" || sort === "priority_asc" ? sort : "date_desc";
  const hasScope = (scope: ScopeValue) => selectedScopes.includes(scope);
  const selectClass = "h-9 rounded-lg border border-gray-300 bg-white px-2 text-xs text-gray-700 focus:outline-none focus:ring-2 focus:ring-green-500";
  const go = (next: { priority?: PriorityFilterValue; category?: CategoryFilterValue; sort?: SortValue }) => router.push(href({ scopes: selectedScopes, keyword, priority: next.priority ?? priorityFilter, category: next.category ?? categoryFilter, sort: next.sort ?? sortValue }));
  return <ResidentPageToolbar namespace="resident-issues" title="ปัญหา/คำร้อง" search={{ keyword, placeholder: "พิมพ์ชื่อปัญหา", label: "ค้นหาปัญหา", suggestions: suggestionTitles }} activeFilterCount={selectedScopes.length + Number(priorityFilter !== "ALL") + Number(categoryFilter !== "ALL") + Number(sortValue !== "date_desc")} actions={<Link href="/resident/issues/new"><Button size="sm" className="h-10 px-2 sm:px-3"><Plus className="h-4 w-4" /><span className="hidden min-[390px]:ml-1 min-[390px]:inline">แจ้งปัญหาใหม่</span></Button></Link>} filters={<><span className="text-xs font-semibold text-gray-500">ขอบเขต</span>{([['mine','ปัญหาของฉัน'],['others','ปัญหาผู้อื่น']] as const).map(([value,label]) => <NewsFilterChip key={value} href={href({ scopes: hasScope(value) ? selectedScopes.filter((item) => item !== value) : [...selectedScopes, value], keyword, priority: priorityFilter, category: categoryFilter, sort: sortValue })} active={hasScope(value)}>{label}</NewsFilterChip>)}<label className="ml-1 flex items-center gap-1 text-xs font-semibold text-gray-500">ความสำคัญ<select aria-label="ระดับความสำคัญ" value={priorityFilter} onChange={(event) => go({ priority: event.target.value as PriorityFilterValue })} className={selectClass}><option value="ALL">ทั้งหมด</option>{Object.entries(ISSUE_PRIORITY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="flex items-center gap-1 text-xs font-semibold text-gray-500">หมวดหมู่<select aria-label="หมวดหมู่ปัญหา" value={categoryFilter} onChange={(event) => go({ category: event.target.value as CategoryFilterValue })} className={selectClass}><option value="ALL">ทั้งหมด</option>{Object.entries(ISSUE_CATEGORY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="flex items-center gap-1 text-xs font-semibold text-gray-500">เรียง<select aria-label="เรียงปัญหา" value={sortValue} onChange={(event) => go({ sort: event.target.value as SortValue })} className={selectClass}>{([['date_desc','วันที่ใหม่ไปเก่า'],['date_asc','วันที่เก่าไปใหม่'],['priority_desc','ความสำคัญสูงไปต่ำ'],['priority_asc','ความสำคัญต่ำไปสูง']] as const).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><NewsFilterChip href="/resident/issues" active={false}>ล้างตัวกรอง</NewsFilterChip></>} />;
}
