"use client";
import Link from "next/link";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ResidentFilterDropdown, ResidentMultiFilterDropdown, ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
import { ISSUE_CATEGORY_LABELS, ISSUE_PRIORITY_LABELS } from "@/lib/constants";
type ScopeValue = "mine" | "others"; type SortValue = "date_desc" | "date_asc" | "priority_desc" | "priority_asc"; type PriorityFilterValue = "ALL" | "LOW" | "MEDIUM" | "HIGH" | "URGENT"; type CategoryFilterValue = "ALL" | "ROAD" | "WATER" | "ELECTRICITY" | "SECURITY" | "WASTE" | "ENVIRONMENT" | "PUBLIC_HEALTH" | "OTHER";
type Props = { keyword: string; selectedScopes: ScopeValue[]; priorityFilter: PriorityFilterValue; categoryFilter: CategoryFilterValue; sort: string; suggestionTitles: string[] };
function href({ scopes, sort, keyword, priority, category }: { scopes: ScopeValue[]; sort: string; keyword: string; priority: PriorityFilterValue; category: CategoryFilterValue }) { const query = new URLSearchParams(); const values = Array.from(new Set(scopes)).sort(); if (values.length) query.set("scope", values.join(",")); if (priority !== "ALL") query.set("priority", priority); if (category !== "ALL") query.set("category", category); if (sort !== "date_desc") query.set("sort", sort); if (keyword.trim()) query.set("q", keyword.trim()); return query.size ? `/resident/issues?${query}` : "/resident/issues"; }
export function ResidentIssuesToolbar({ keyword, selectedScopes, priorityFilter, categoryFilter, sort, suggestionTitles }: Props) {
  const sortValue: SortValue = sort === "date_asc" || sort === "priority_desc" || sort === "priority_asc" ? sort : "date_desc"; const hasScope = (scope: ScopeValue) => selectedScopes.includes(scope); const toggleScope = (scope: ScopeValue) => href({ scopes: hasScope(scope) ? selectedScopes.filter((item) => item !== scope) : [...selectedScopes, scope], keyword, priority: priorityFilter, category: categoryFilter, sort: sortValue }); const count = selectedScopes.length + Number(priorityFilter !== "ALL") + Number(categoryFilter !== "ALL");
  return <ResidentPageToolbar namespace="resident-issues" title="แจ้งปัญหา" registerHeader search={{ keyword, placeholder: "พิมพ์ชื่อปัญหา", label: "ค้นหาปัญหา", suggestions: suggestionTitles }} activeFilterCount={count} actions={<Link href="/resident/issues/new"><Button size="sm" className="h-10 px-2 sm:px-3"><Plus className="h-4 w-4" /><span className="hidden min-[390px]:ml-1 min-[390px]:inline">แจ้งปัญหาใหม่</span></Button></Link>} filters={<>
    <ResidentMultiFilterDropdown label="ขอบเขต" clearHref={href({ scopes: [], keyword, priority: priorityFilter, category: categoryFilter, sort: sortValue })} options={([['mine', 'ปัญหาของฉัน'], ['others', 'ปัญหาผู้อื่น']] as const).map(([value, label]) => ({ label, href: toggleScope(value), active: hasScope(value) }))} />
    <ResidentFilterDropdown label="ความสำคัญ" options={[{ label: "ทั้งหมด", href: href({ scopes: selectedScopes, keyword, priority: "ALL", category: categoryFilter, sort: sortValue }), active: priorityFilter === "ALL" }, ...Object.entries(ISSUE_PRIORITY_LABELS).map(([value, label]) => ({ label, href: href({ scopes: selectedScopes, keyword, priority: value as PriorityFilterValue, category: categoryFilter, sort: sortValue }), active: priorityFilter === value }))]} />
    <ResidentFilterDropdown label="หมวดหมู่" options={[{ label: "ทั้งหมด", href: href({ scopes: selectedScopes, keyword, priority: priorityFilter, category: "ALL", sort: sortValue }), active: categoryFilter === "ALL" }, ...Object.entries(ISSUE_CATEGORY_LABELS).map(([value, label]) => ({ label, href: href({ scopes: selectedScopes, keyword, priority: priorityFilter, category: value as CategoryFilterValue, sort: sortValue }), active: categoryFilter === value }))]} />
    <ResidentFilterDropdown label="เรียง" options={([['date_desc', 'วันที่ใหม่ไปเก่า'], ['date_asc', 'วันที่เก่าไปใหม่'], ['priority_desc', 'ความสำคัญสูงไปต่ำ'], ['priority_asc', 'ความสำคัญต่ำไปสูง']] as const).map(([value, label]) => ({ label, href: href({ scopes: selectedScopes, keyword, priority: priorityFilter, category: categoryFilter, sort: value }), active: sortValue === value }))} />
    {count > 0 ? <Link href={href({ scopes: [], keyword, priority: "ALL", category: "ALL", sort: sortValue })} className="inline-flex h-9 items-center rounded-md px-2 text-xs font-medium text-gray-600 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-green-500">ล้างตัวกรอง</Link> : null}
  </>} />;
}
