import Link from "next/link";
import { AdminPageToolbar } from "@/components/ui/admin-page-toolbar";
import { requireVillagePagePermission } from "@/lib/admin-permission.server";
import { listVillageBroadcasts } from "@/features/broadcasts/server/broadcast-service";
import { createAdminVillageBroadcastAction } from "./actions";

type Props = { searchParams?: Promise<{ q?: string; status?: string; page?: string }> };
const copy: Record<string, string> = { ACTIVE: "กำลังแสดง", EXPIRED: "หมดอายุแล้ว", CANCELLED: "ยกเลิกแล้ว" };
export default async function AdminBroadcastsPage({ searchParams }: Props) {
  const context = await requireVillagePagePermission("broadcasts.manage", { callbackUrl: "/admin/broadcasts" }); const params = await searchParams ?? {}; const q = (params.q ?? "").trim(); const status = ["all", "active", "expired", "cancelled"].includes(params.status ?? "") ? params.status! : "all"; const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1); const { rows, total, now } = await listVillageBroadcasts(context.villageId, q, status, page);
  return <div data-admin-compact-top className="space-y-4"><AdminPageToolbar compact sticky title="ประกาศส่วนกลางของหมู่บ้าน" description="ส่งประกาศสำคัญถึงสมาชิกหมู่บ้านที่ใช้งานอยู่" search={{ keyword: q, label: "ค้นหาประกาศ", placeholder: "ค้นหาหัวข้อหรือเนื้อหา" }} />
    <details className="rounded-xl border border-gray-200 bg-white p-4"><summary className="cursor-pointer font-medium text-gray-900">สร้างประกาศส่วนกลาง</summary><form action={createAdminVillageBroadcastAction} className="mt-4 grid gap-3"><label className="text-sm font-medium">หัวข้อ<input required name="title" className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-medium">เนื้อหา<textarea required name="body" rows={5} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-medium">ระยะเวลาประกาศ<select name="expiryMode" defaultValue="ONE_DAY" className="mt-1 w-full rounded-lg border p-2"><option value="ONE_HOUR">1 ชั่วโมง</option><option value="ONE_DAY">1 วัน</option><option value="THREE_DAYS">3 วัน</option><option value="SEVEN_DAYS">7 วัน</option><option value="CUSTOM">กำหนดเอง</option><option value="NEVER">ไม่กำหนดวันหมดอายุ</option></select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">กำหนดเอง (จำนวน)<input name="customValue" type="number" min="1" className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-medium">หน่วย<select name="customUnit" defaultValue="HOURS" className="mt-1 w-full rounded-lg border p-2"><option value="HOURS">ชั่วโมง</option><option value="MINUTES">นาที</option></select></label></div><button className="w-fit rounded-lg bg-green-700 px-4 py-2 text-sm font-medium text-white hover:bg-green-800">ส่งประกาศ</button></form></details>
    <p className="text-sm text-gray-600">พบ {total.toLocaleString("th-TH")} ประกาศ</p><section className="space-y-2" aria-label="ประวัติประกาศ">{rows.length ? rows.map((row) => { const state = row.status === "CANCELLED" ? "CANCELLED" : row.expiresAt && row.expiresAt <= now ? "EXPIRED" : "ACTIVE"; return <Link key={row.id} href={`/admin/broadcasts/${row.id}`} className="block rounded-xl border border-gray-200 bg-white p-4 hover:border-green-300"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-gray-900">{row.title}</h2><span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs">{copy[state]}</span></div><p className="mt-2 line-clamp-2 whitespace-pre-wrap text-sm text-gray-700">{row.body}</p><p className="mt-3 text-xs text-gray-500">ผู้รับ {row.audienceCount.toLocaleString("th-TH")} คน · สร้างเมื่อ {row.createdAt.toLocaleString("th-TH")}</p></Link>; }) : <p className="rounded-xl border border-dashed p-8 text-center text-sm text-gray-600">ยังไม่มีประวัติประกาศ</p>}</section></div>;
}
