"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/toast";
import { MEMBER_ROLE_LABEL, MEMBER_STATUS_LABEL } from "@/features/village-workspace/constants";
import type { HouseOption, MemberRow } from "@/features/village-workspace/types";
import { maskPhone } from "@/features/village-workspace/utils";
import { changeMembershipSupportAction } from "./actions";

function ActionDialog({ row, villageId, houses, returnTo, open, onClose }: { row: MemberRow; villageId: string; houses: HouseOption[]; returnTo: "users" | "admins"; open: boolean; onClose: () => void }) {
  const router = useRouter(); const toast = useToast(); const [busy, setBusy] = useState(false); const [operation, setOperation] = useState("ACTIVATE");
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); try { const result = await changeMembershipSupportAction(villageId, new FormData(event.currentTarget)); toast.success(result.message); onClose(); router.refresh(); } catch (error) { toast.error("ดำเนินการไม่สำเร็จ", error instanceof Error ? error.message : "เกิดข้อผิดพลาด"); } finally { setBusy(false); } };
  return <Dialog open={open} title={`จัดการสมาชิก: ${row.user.name}`} description="เลือกการดำเนินการและยืนยันเหตุผลสำหรับการเปลี่ยนแปลง" onClose={() => !busy && onClose()} closeOnBackdrop={false} closeOnEscape={!busy} footer={<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>ยกเลิก</Button><Button type="submit" form={`member-action-${row.id}`} isLoading={busy} disabled={busy}>ยืนยันการเปลี่ยนแปลง</Button></div>}>
    <form id={`member-action-${row.id}`} onSubmit={submit} className="grid gap-4"><input type="hidden" name="membershipId" value={row.id} /><input type="hidden" name="returnTo" value={returnTo} />
      <label className="grid gap-1.5 text-sm font-medium text-slate-700">การดำเนินการ<select name="operation" value={operation} onChange={(event) => setOperation(event.target.value)} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 font-normal"><option value="ACTIVATE">เปิดใช้งาน</option><option value="SUSPEND">ระงับสมาชิก</option><option value="RESIDENT">เปลี่ยนเป็นลูกบ้าน</option></select></label>
      {operation === "RESIDENT" ? <label className="grid gap-1.5 text-sm font-medium text-slate-700">บ้าน<select name="houseId" required className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 font-normal"><option value="">เลือกบ้าน</option>{houses.map((house) => <option key={house.id} value={house.id}>บ้านเลขที่ {house.houseNumber}</option>)}</select></label> : <input type="hidden" name="houseId" value="" />}
      {row.role === "HEADMAN" && operation === "SUSPEND" ? <label className="flex items-start gap-2 text-sm text-slate-700"><input type="checkbox" name="confirmVacant" value="true" required className="mt-0.5 h-4 w-4 rounded border-slate-300 text-green-600" />ยืนยันว่าการระงับอาจทำให้ตำแหน่งผู้ใหญ่บ้านว่าง</label> : null}
      <label className="grid gap-1.5 text-sm font-medium text-slate-700">เหตุผล <span className="text-xs font-normal text-slate-500">อธิบายเหตุผลอย่างน้อย 5 ตัวอักษร <span className="text-red-600">*</span></span><textarea name="reason" required minLength={5} rows={3} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-normal" /></label>
    </form>
  </Dialog>;
}

function ActionButton({ row, villageId, houses, returnTo }: { row: MemberRow; villageId: string; houses: HouseOption[]; returnTo: "users" | "admins" }) { const [open, setOpen] = useState(false); return <><button type="button" onClick={() => setOpen(true)} className="inline-flex min-h-9 items-center justify-center rounded-md border border-slate-300 px-2.5 text-xs font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-green-500">จัดการ</button><ActionDialog row={row} villageId={villageId} houses={houses} returnTo={returnTo} open={open} onClose={() => setOpen(false)} /></>; }

export function MemberList({ rows, villageId, houses, returnTo }: { rows: MemberRow[]; villageId: string; villageName: string; houses: HouseOption[]; total: number; returnTo: "users" | "admins" }) {
  if (!rows.length) return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">ไม่พบรายการที่ตรงกับตัวกรอง</div>;
  return <div className="rounded-xl border border-slate-200 bg-white"><div className="hidden max-h-[calc(100dvh-15rem)] overflow-y-auto md:block"><table className="w-full text-left text-sm"><thead className="sticky top-0 z-10 border-b border-slate-200 bg-slate-50 text-xs font-medium text-slate-500"><tr><th className="px-4 py-3">สมาชิก</th><th className="px-4 py-3">บทบาท</th><th className="px-4 py-3">สถานะ</th><th className="px-4 py-3">บ้าน</th><th className="px-4 py-3">วันที่เข้าร่วม</th><th className="w-28 px-4 py-3 text-center">การจัดการ</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="align-middle hover:bg-slate-50/60"><td className="px-4 py-3"><p className="font-medium text-slate-900">{row.user.name}</p><p className="mt-0.5 text-xs text-slate-400">{maskPhone(row.user.phoneNumber)}</p></td><td className="px-4 py-3"><Badge variant="outline">{MEMBER_ROLE_LABEL[row.role] ?? row.role}</Badge></td><td className="px-4 py-3"><Badge variant={row.status === "ACTIVE" ? "success" : row.status === "SUSPENDED" ? "danger" : "warning"}>{MEMBER_STATUS_LABEL[row.status] ?? row.status}</Badge></td><td className="px-4 py-3 text-slate-600">{row.house?.houseNumber ?? "-"}</td><td className="px-4 py-3 text-slate-500">{row.joinedAt ? new Date(row.joinedAt).toLocaleDateString("th-TH") : "-"}</td><td className="px-4 py-3 text-center"><ActionButton row={row} villageId={villageId} houses={houses} returnTo={returnTo} /></td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{rows.map((row) => <article key={row.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-slate-900">{row.user.name}</p><p className="mt-1 text-xs text-slate-400">{maskPhone(row.user.phoneNumber)}</p></div><Badge variant={row.status === "ACTIVE" ? "success" : "warning"}>{MEMBER_STATUS_LABEL[row.status] ?? row.status}</Badge></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-400">บทบาท</dt><dd className="mt-1 text-slate-700">{MEMBER_ROLE_LABEL[row.role] ?? row.role}</dd></div><div><dt className="text-xs text-slate-400">บ้านเลขที่</dt><dd className="mt-1 text-slate-700">{row.house?.houseNumber ?? "-"}</dd></div><div><dt className="text-xs text-slate-400">เข้าร่วม</dt><dd className="mt-1 text-slate-700">{row.joinedAt ? new Date(row.joinedAt).toLocaleDateString("th-TH") : "-"}</dd></div></dl><div className="mt-4"><ActionButton row={row} villageId={villageId} houses={houses} returnTo={returnTo} /></div></article>)}</div></div>;
}
