"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/toast";
import { MEMBER_ROLE_LABEL, MEMBER_STATUS_LABEL } from "@/features/village-workspace/constants";
import type { HouseOption, MemberRole, MemberRow } from "@/features/village-workspace/types";
import { changeMembershipSupportAction } from "./actions";

const choices = (role: MemberRole): MemberRole[] => role === "RESIDENT" ? ["ASSISTANT_HEADMAN", "HEADMAN"] : role === "ASSISTANT_HEADMAN" ? ["RESIDENT", "HEADMAN"] : ["RESIDENT", "ASSISTANT_HEADMAN"];
const roleClass = (role: MemberRole) => role === "HEADMAN" ? "border-slate-400 bg-slate-100 text-slate-800" : role === "ASSISTANT_HEADMAN" ? "border-cyan-200 bg-cyan-50 text-cyan-800" : "border-slate-200 bg-white text-slate-600";

function MemberAction({ row, villageId, houses }: { row: MemberRow; villageId: string; houses: HouseOption[] }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false);
  const [operation, setOperation] = useState(row.status === "SUSPENDED" ? "ACTIVATE" : "SUSPEND");
  const [targetRole, setTargetRole] = useState<MemberRole>(choices(row.role)[0]);
  const router = useRouter(), toast = useToast();
  if (row.status !== "ACTIVE" && row.status !== "SUSPENDED") return <span className="text-xs text-slate-400">-</span>;
  const changing = operation === "CHANGE_ROLE", vacancy = row.role === "HEADMAN" && (operation === "SUSPEND" || (changing && targetRole !== "HEADMAN"));
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); try { const result = await changeMembershipSupportAction(villageId, new FormData(event.currentTarget)); toast.success(result.message); setOpen(false); router.refresh(); } catch (error) { toast.error("ดำเนินการไม่สำเร็จ", error instanceof Error ? error.message : "เกิดข้อผิดพลาด"); } finally { setBusy(false); } };
  return <><button type="button" onClick={() => setOpen(true)} className="inline-flex min-h-9 items-center justify-center rounded-md border border-slate-300 px-2.5 text-xs font-medium text-slate-700 hover:bg-slate-50">จัดการ</button><Dialog open={open} title={`จัดการสมาชิก: ${row.user.name}`} description="เลือกการดำเนินการและยืนยันเหตุผลสำหรับการเปลี่ยนแปลง" onClose={() => !busy && setOpen(false)} closeOnBackdrop={false} closeOnEscape={!busy} footer={<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" disabled={busy} onClick={() => setOpen(false)}>ยกเลิก</Button><Button type="submit" form={`member-action-${row.id}`} isLoading={busy} disabled={busy}>ยืนยันการเปลี่ยนแปลง</Button></div>}><form id={`member-action-${row.id}`} onSubmit={submit} className="grid gap-4"><input type="hidden" name="membershipId" value={row.id} />{row.status === "ACTIVE" ? <label className="grid gap-1.5 text-sm font-medium text-slate-700">การดำเนินการ<select name="operation" value={operation} onChange={(e) => setOperation(e.target.value)} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 font-normal"><option value="SUSPEND">ระงับสมาชิก</option><option value="CHANGE_ROLE">เปลี่ยนบทบาท</option></select></label> : <><input type="hidden" name="operation" value="ACTIVATE" /><p className="text-sm text-slate-600">เปิดใช้งานสมาชิกที่ถูกระงับ</p></>}{changing ? <><label className="grid gap-1.5 text-sm font-medium text-slate-700">บทบาทใหม่<select name="targetRole" value={targetRole} onChange={(e) => setTargetRole(e.target.value as MemberRole)} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 font-normal">{choices(row.role).map((role) => <option key={role} value={role}>{MEMBER_ROLE_LABEL[role]}</option>)}</select></label>{targetRole === "RESIDENT" ? <label className="grid gap-1.5 text-sm font-medium text-slate-700">บ้าน<select name="houseId" required className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 font-normal"><option value="">เลือกบ้าน</option>{houses.map((house) => <option key={house.id} value={house.id}>บ้านเลขที่ {house.houseNumber}</option>)}</select></label> : <input type="hidden" name="houseId" value="" />}</> : <><input type="hidden" name="targetRole" value="" /><input type="hidden" name="houseId" value="" /></>}{vacancy ? <label className="flex items-start gap-2 text-sm text-slate-700"><input type="checkbox" name="confirmVacant" value="true" required className="mt-0.5 h-4 w-4" />ยืนยันว่าหมู่บ้านอาจไม่มีผู้ใหญ่บ้าน หรือแต่งตั้งผู้ใหญ่บ้านใหม่ก่อน</label> : null}<label className="grid gap-1.5 text-sm font-medium text-slate-700">เหตุผลในการดำเนินการ <span className="text-red-600">*</span><span className="text-xs font-normal text-slate-500">อธิบายเหตุผลอย่างน้อย 5 ตัวอักษร</span><textarea name="reason" required minLength={5} rows={3} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-normal" /></label></form></Dialog></>;
}

export function MemberList({ rows, villageId, houses }: { rows: MemberRow[]; villageId: string; villageName: string; houses: HouseOption[]; total: number }) {
  if (!rows.length) return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">ไม่พบรายการที่ตรงกับตัวกรอง</div>;
  const statusVariant = (status: string) => status === "ACTIVE" ? "success" : status === "SUSPENDED" ? "danger" : "warning";
  return <div className="rounded-xl border border-slate-200 bg-white"><div className="hidden max-h-[calc(100dvh-15rem)] overflow-y-auto md:block"><table className="w-full text-left text-sm"><thead className="sticky top-0 z-10 border-b border-slate-200 bg-slate-50 text-xs font-medium text-slate-500"><tr><th className="px-4 py-3">สมาชิก</th><th className="px-4 py-3">เบอร์โทร</th><th className="px-4 py-3">บทบาท</th><th className="px-4 py-3">สถานะ</th><th className="px-4 py-3">บ้าน</th><th className="px-4 py-3">วันที่เข้าร่วม</th><th className="w-28 px-4 py-3 text-center">การจัดการ</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="hover:bg-slate-50/60"><td className="px-4 py-3 font-medium text-slate-900">{row.user.name}</td><td className="px-4 py-3 text-slate-600">{row.user.phoneNumber || "-"}</td><td className="px-4 py-3"><Badge variant="outline" className={roleClass(row.role)}>{MEMBER_ROLE_LABEL[row.role]}</Badge></td><td className="px-4 py-3"><Badge variant={statusVariant(row.status)}>{MEMBER_STATUS_LABEL[row.status]}</Badge></td><td className="px-4 py-3 text-slate-600">{row.house?.houseNumber ?? "-"}</td><td className="px-4 py-3 text-slate-500">{row.joinedAt ? new Date(row.joinedAt).toLocaleDateString("th-TH") : "-"}</td><td className="px-4 py-3 text-center"><MemberAction row={row} villageId={villageId} houses={houses} /></td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{rows.map((row) => <article key={row.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-slate-900">{row.user.name}</p><p className="mt-1 text-xs text-slate-500">{row.user.phoneNumber || "-"}</p></div><Badge variant={statusVariant(row.status)}>{MEMBER_STATUS_LABEL[row.status]}</Badge></div><div className="mt-3"><Badge variant="outline" className={roleClass(row.role)}>{MEMBER_ROLE_LABEL[row.role]}</Badge></div><div className="mt-4"><MemberAction row={row} villageId={villageId} houses={houses} /></div></article>)}</div></div>;
}
