import Link from "next/link";
import { Plus, SearchX, ShieldCheck } from "lucide-react";
import { Prisma } from "@prisma/client";
import { redirect } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AdminListToolbar } from "@/components/ui/admin-list-toolbar";
import { prisma } from "@/lib/prisma";
import { getAdminMembership, getSessionContextFromServerCookies } from "@/lib/access-control";
import { NEWS_VISIBILITY_LABELS, TRANSPARENCY_STAGE_LABELS } from "@/lib/constants";

type PageProps = { searchParams?: Promise<{ q?: string; stage?: string; visibility?: string; sort?: string; page?: string }> };
const TAKE = 12;
const stageVariant: Record<string, "default" | "info" | "success" | "warning" | "danger"> = { DRAFT: "warning", PUBLISHED: "success", ARCHIVED: "default" };

export default async function TransparencyPage({ searchParams }: PageProps) {
  const params = (searchParams ? await searchParams : {}) ?? {}; const session = await getSessionContextFromServerCookies();
  if (!session?.id) redirect("/auth/login"); const membership = getAdminMembership(session); if (!membership) redirect("/resident");
  const keyword = params.q?.trim() ?? ""; const activeStage = ["DRAFT", "PUBLISHED", "ARCHIVED"].includes(params.stage ?? "") ? params.stage! : "ALL"; const activeVisibility = ["PUBLIC", "RESIDENT_ONLY"].includes(params.visibility ?? "") ? params.visibility! : "ALL"; const activeSort = ["newest", "oldest", "amount"].includes(params.sort ?? "") ? params.sort! : "newest"; const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1);
  const baseWhere: Prisma.TransparencyRecordWhereInput = { villageId: membership.villageId };
  const where: Prisma.TransparencyRecordWhereInput = { ...baseWhere, ...(activeStage !== "ALL" ? { stage: activeStage as Prisma.TransparencyRecordWhereInput["stage"] } : {}), ...(activeVisibility !== "ALL" ? { visibility: activeVisibility as Prisma.TransparencyRecordWhereInput["visibility"] } : {}), ...(keyword ? { OR: [{ title: { contains: keyword, mode: "insensitive" } }, { description: { contains: keyword, mode: "insensitive" } }, { category: { contains: keyword, mode: "insensitive" } }, { fiscalYear: { contains: keyword, mode: "insensitive" } }] } : {}) };
  const orderBy = activeSort === "oldest" ? [{ publishedAt: "asc" as const }, { createdAt: "asc" as const }] : activeSort === "amount" ? [{ amount: "desc" as const }, { createdAt: "desc" as const }] : [{ publishedAt: "desc" as const }, { createdAt: "desc" as const }];
  const [records, total, totalRecords, suggestions] = await Promise.all([prisma.transparencyRecord.findMany({ where, orderBy, skip: (page - 1) * TAKE, take: TAKE, select: { id: true, title: true, category: true, amount: true, fiscalYear: true, stage: true, visibility: true, publishedAt: true, createdAt: true } }), prisma.transparencyRecord.count({ where }), prisma.transparencyRecord.count({ where: baseWhere }), prisma.transparencyRecord.findMany({ where: baseWhere, orderBy: { updatedAt: "desc" }, take: 12, select: { title: true } })]);
  const hasFilters = Boolean(keyword || activeStage !== "ALL" || activeVisibility !== "ALL" || activeSort !== "newest");
  const EmptyIcon = hasFilters || totalRecords > 0 ? SearchX : ShieldCheck;
  function href(next: { q?: string; stage?: string; visibility?: string; sort?: string; page?: number }) { const query = new URLSearchParams(); const q = next.q?.trim() ?? ""; const stage = next.stage ?? "ALL"; const visibility = next.visibility ?? "ALL"; const sort = next.sort ?? "newest"; const nextPage = next.page ?? 1; if (q) query.set("q", q); if (stage !== "ALL") query.set("stage", stage); if (visibility !== "ALL") query.set("visibility", visibility); if (sort !== "newest") query.set("sort", sort); if (nextPage > 1) query.set("page", String(nextPage)); return query.size ? `/admin/transparency?${query}` : "/admin/transparency"; }
  return <div className="space-y-6"><AdminListToolbar title="ความโปร่งใส" description="จัดการรายการงบประมาณ โครงการ และข้อมูลการเปิดเผย" searchAction="/admin/transparency" keyword={keyword} searchPlaceholder="ค้นหาชื่อรายการ หมวดหมู่ หรือปีงบประมาณ" hiddenInputs={{ stage: activeStage === "ALL" ? "" : activeStage, visibility: activeVisibility === "ALL" ? "" : activeVisibility, sort: activeSort === "newest" ? "" : activeSort }} suggestionTitles={suggestions.map(({ title }) => title)} groups={[{ label: "สถานะ", options: [["ทั้งหมด", "ALL"], ["ร่าง", "DRAFT"], ["เผยแพร่", "PUBLISHED"], ["เก็บถาวร", "ARCHIVED"]].map(([label, value]) => ({ label, href: href({ q: keyword, stage: value, visibility: activeVisibility, sort: activeSort }), active: activeStage === value })) }, { label: "การมองเห็น", options: [["ทั้งหมด", "ALL"], ["สาธารณะ", "PUBLIC"], ["เฉพาะลูกบ้าน", "RESIDENT_ONLY"]].map(([label, value]) => ({ label, href: href({ q: keyword, stage: activeStage, visibility: value, sort: activeSort }), active: activeVisibility === value })) }, { label: "เรียง", options: [["ล่าสุดก่อน", "newest"], ["เก่าก่อน", "oldest"], ["งบสูงก่อน", "amount"]].map(([label, value]) => ({ label, href: href({ q: keyword, stage: activeStage, visibility: activeVisibility, sort: value }), active: activeSort === value })) }]} actions={<Link href="/admin/transparency/new"><Button size="sm"><Plus className="mr-1 h-4 w-4" />เพิ่มรายการ</Button></Link>} />
    {records.length === 0 ? <div className="rounded-xl border border-gray-200 bg-white p-10 text-center"><EmptyIcon className="mx-auto mb-3 h-10 w-10 text-gray-300" />{hasFilters || totalRecords > 0 ? <><p className="text-gray-700">ไม่พบรายการที่ตรงกัน</p><p className="mt-1 text-sm text-gray-400">ลองเปลี่ยนคำค้นหาหรือตัวกรอง</p></> : <><p className="text-gray-700">ยังไม่มีข้อมูลความโปร่งใส</p><p className="mt-1 text-sm text-gray-400">เพิ่มข้อมูลที่ต้องการเปิดเผยให้ประชาชนหรือลูกบ้านตรวจสอบ</p><Link className="mt-5 inline-block" href="/admin/transparency/new"><Button>เพิ่มรายการ</Button></Link></>}</div> : <><div className="space-y-3">{records.map(record => <Link key={record.id} href={`/admin/transparency/${record.id}`} className="block rounded-xl border border-gray-200 bg-white p-4 transition-shadow hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-600 focus-visible:ring-offset-2 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge variant={stageVariant[record.stage] ?? "default"}>{TRANSPARENCY_STAGE_LABELS[record.stage]}</Badge><Badge variant="outline">{NEWS_VISIBILITY_LABELS[record.visibility]}</Badge>{record.fiscalYear ? <Badge variant="outline">ปี {record.fiscalYear}</Badge> : null}</div><p className="break-words font-medium text-gray-900">{record.title}</p><p className="mt-1 break-words text-sm text-gray-500">{record.category || "ไม่ระบุหมวดหมู่"}{record.amount != null ? ` • ${record.amount.toLocaleString("th-TH")} บาท` : ""}</p></div><p className="shrink-0 text-xs text-gray-400">{(record.publishedAt ?? record.createdAt).toLocaleDateString("th-TH")}</p></div></Link>)}</div>{total > TAKE ? <nav className="flex flex-wrap items-center justify-between gap-3" aria-label="เปลี่ยนหน้ารายการ"><p className="text-sm text-gray-500">หน้า {page} จาก {Math.ceil(total / TAKE)}</p><div className="flex gap-2">{page > 1 ? <Link href={href({ q: keyword, stage: activeStage, visibility: activeVisibility, sort: activeSort, page: page - 1 })}><Button variant="outline" size="sm">ก่อนหน้า</Button></Link> : null}{page * TAKE < total ? <Link href={href({ q: keyword, stage: activeStage, visibility: activeVisibility, sort: activeSort, page: page + 1 })}><Button variant="outline" size="sm">ถัดไป</Button></Link> : null}</div></nav> : null}</>}</div>;
}
