"use client";
import { useEffect, useRef, useState } from "react";
import { CheckCircle2, Mail, Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/toast";
import { MAX_HOUSE_ACCOUNT_EMAILS } from "@/lib/house-account-email-policy";
type EmailRow={id:string;email:string;isCanonical:boolean;isCurrentSession:boolean}; type Flow={error?:string;maskedEmail?:string;expiresAt?:string;resendAvailableAt?:string};
export function HouseAccountEmailManager({emails}:{emails:EmailRow[]}){
 const router=useRouter();const toast=useToast();const codeRef=useRef<HTMLInputElement>(null);const [open,setOpen]=useState(false);const [step,setStep]=useState<"EMAIL"|"OTP">("EMAIL");const [email,setEmail]=useState("");const [code,setCode]=useState("");const [masked,setMasked]=useState("");const [available,setAvailable]=useState<Date|null>(null);const [seconds,setSeconds]=useState(0);const [busy,setBusy]=useState(false);const [removingId,setRemovingId]=useState<string|null>(null);const [pending,setPending]=useState<EmailRow|null>(null);
 useEffect(()=>{if(step==="OTP")codeRef.current?.focus()},[step]);useEffect(()=>{if(!available)return;const tick=()=>setSeconds(Math.max(0,Math.ceil((available.getTime()-Date.now())/1000)));tick();const timer=window.setInterval(tick,1000);return()=>window.clearInterval(timer)},[available]);
 function reset(){setOpen(false);setStep("EMAIL");setEmail("");setCode("");setMasked("");setAvailable(null)} async function closeFlow(){if(step==="OTP")await fetch("/api/auth/house-account-emails/cancel",{method:"POST"}).catch(()=>undefined);reset()}
 async function start(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/auth/house-account-emails/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const b=(await r.json().catch(()=>null)) as Flow|null;setBusy(false);if(!r.ok||!b?.expiresAt||!b.resendAvailableAt){toast.error(b?.error??"ไม่สามารถส่งรหัสยืนยันได้");return}setMasked(b.maskedEmail??email);setAvailable(new Date(b.resendAvailableAt));setStep("OTP")}
 async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/auth/house-account-emails/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});const b=(await r.json().catch(()=>null)) as Flow|null;setBusy(false);if(!r.ok){toast.error(b?.error??"ไม่สามารถยืนยันอีเมลได้");return}reset();toast.success("เพิ่มอีเมลสำหรับเข้าสู่ระบบแล้ว");router.refresh()}
 async function resend(){setBusy(true);const r=await fetch("/api/auth/house-account-emails/resend",{method:"POST"});const b=(await r.json().catch(()=>null)) as Flow|null;setBusy(false);if(!r.ok||!b?.resendAvailableAt){toast.error(b?.error??"ไม่สามารถส่งรหัสใหม่ได้");return}setAvailable(new Date(b.resendAvailableAt));toast.success("ส่งรหัสยืนยันใหม่แล้ว")}
 async function remove(){if(!pending)return;const row=pending;setRemovingId(row.id);const r=await fetch(`/api/auth/house-account-emails/${encodeURIComponent(row.id)}`,{method:"DELETE"});const b=(await r.json().catch(()=>null)) as {error?:string;currentSessionRevoked?:boolean}|null;setRemovingId(null);if(!r.ok){toast.error(b?.error??"ไม่สามารถนำอีเมลออกได้");return}setPending(null);if(b?.currentSessionRevoked){window.location.assign("/auth/login?emailRemoved=success");return}toast.success("นำอีเมลออกแล้ว");router.refresh()}
 return <section className="rounded-xl border border-gray-200 bg-white p-4 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Mail className="h-5 w-5 text-green-700" aria-hidden="true"/><h2 className="font-semibold text-gray-900">อีเมลที่ใช้งาน</h2></div><Button type="button" className="min-h-11 shrink-0" disabled={emails.length>=MAX_HOUSE_ACCOUNT_EMAILS} onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4" aria-hidden="true"/>เพิ่มอีเมล</Button></div><ul className="mt-5 space-y-3">{emails.map(row=><li key={row.id} className="flex min-w-0 items-center gap-3 rounded-lg border border-gray-200 p-4"><div className="min-w-0 flex-1"><p className="break-all font-medium text-gray-900">{row.email}</p><p className="mt-1 flex flex-wrap gap-x-3 text-xs text-green-700"><span><CheckCircle2 className="mr-1 inline h-3.5 w-3.5" aria-hidden="true"/>ยืนยันแล้ว</span>{row.isCurrentSession?<span className="text-gray-500">อีเมลที่กำลังใช้</span>:null}</p></div><Button type="button" variant="dangerOutline" className="min-h-11 shrink-0 px-3" aria-label={`นำ ${row.email} ออก`} disabled={emails.length<=1} onClick={()=>setPending(row)}><Trash2 className="h-4 w-4" aria-hidden="true"/><span className="sr-only">นำอีเมลออก</span></Button></li>)}</ul>
 <Dialog open={open} onClose={closeFlow} title="เพิ่มอีเมล" description={step==="EMAIL"?"กรอกอีเมลใหม่เพื่อรับรหัสยืนยัน":`กรอกรหัสยืนยันที่ส่งไปยัง ${masked}`} closeOnBackdrop={!busy} closeOnEscape={!busy}>{step==="EMAIL"?<form className="space-y-4" onSubmit={start}><label htmlFor="new-house-email" className="block text-sm font-medium text-gray-700">อีเมลใหม่</label><input id="new-house-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} className="min-h-11 w-full rounded-lg border border-gray-300 px-3 py-2"/><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" className="min-h-11" disabled={busy} onClick={closeFlow}>ยกเลิก</Button><Button type="submit" className="min-h-11" isLoading={busy}>ส่งรหัสยืนยัน</Button></div></form>:<form className="space-y-4" onSubmit={verify}><label htmlFor="new-house-email-otp" className="block text-sm font-medium text-gray-700">รหัสยืนยัน</label><input ref={codeRef} id="new-house-email-otp" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} className="min-h-12 w-full rounded-lg border border-gray-300 px-3 text-center text-xl tracking-[0.35em]"/><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><button type="button" disabled={busy||seconds>0} onClick={resend} className="min-h-11 px-3 text-sm font-medium text-green-700 disabled:text-gray-400">{seconds>0?`ส่งใหม่ได้ใน ${seconds} วินาที`:"ส่งรหัสอีกครั้ง"}</button><div className="flex flex-col-reverse gap-2 sm:flex-row"><Button type="button" variant="outline" className="min-h-11" disabled={busy} onClick={closeFlow}>ยกเลิก</Button><Button type="submit" className="min-h-11" disabled={code.length!==6} isLoading={busy}>ยืนยัน</Button></div></div></form>}</Dialog>
 <Dialog open={pending!==null} onClose={()=>{if(!removingId)setPending(null)}} title="ลบอีเมลนี้หรือไม่?" description={pending?`อีเมล ${pending.email} จะไม่สามารถใช้เข้าสู่บัญชีบ้านนี้ได้อีก`:undefined} closeOnBackdrop={!removingId} closeOnEscape={!removingId}><div className="space-y-5"><p className="text-sm text-gray-600">การดำเนินการนี้ไม่สามารถย้อนกลับได้จากหน้านี้</p><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" className="min-h-11" disabled={!!removingId} onClick={()=>setPending(null)}>ยกเลิก</Button><Button type="button" variant="danger" className="min-h-11" isLoading={!!removingId} onClick={remove}>{removingId?"กำลังลบ...":"ลบอีเมล"}</Button></div></div></Dialog></section>;
}
