"use client";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { PublicPageToolbar } from "@/components/public/public-page-toolbar";
import { VILLAGE_PLACE_CATEGORY_LABELS } from "@/lib/constants";
type SortValue = "newest" | "oldest" | "name_asc" | "name_desc";
type Props = { villageSlug: string; villageName: string; keyword: string; category: string; sort: SortValue; suggestionTitles: string[]; };
function href(villageSlug: string, keyword: string, category: string, sort: SortValue) { const p = new URLSearchParams(); if (keyword.trim()) p.set("q", keyword.trim()); if (category !== "ALL") p.set("category", category); if (sort !== "newest") p.set("sort", sort); return p.size ? `/${villageSlug}/places?${p}` : `/${villageSlug}/places`; }
export function PublicPlacesToolbar({ villageSlug, villageName, keyword, category, sort, suggestionTitles }: Props) { const chip = (on: boolean) => cn("rounded-lg px-3 py-1.5 text-xs font-medium", on ? "bg-green-700 text-white" : "bg-gray-100 text-gray-700 hover:bg-gray-200"); return <PublicPageToolbar namespace="public-places" title={`สถานที่สำคัญ ${villageName}`} description="ค้นหาและกรองเฉพาะสถานที่ที่เผยแพร่สาธารณะ" keyword={keyword} placeholder="ค้นหาชื่อ รายละเอียด หรือที่อยู่" suggestions={suggestionTitles} activeFilterCount={Number(category !== "ALL") + Number(sort !== "newest")} filters={<><span className="text-xs font-semibold text-gray-500">หมวดหมู่</span><Link href={href(villageSlug, keyword, "ALL", sort)} className={chip(category === "ALL")}>ทั้งหมด</Link>{Object.entries(VILLAGE_PLACE_CATEGORY_LABELS).map(([value, label]) => <Link key={value} href={href(villageSlug, keyword, value, sort)} className={chip(category === value)}>{label}</Link>)}<span className="ml-1 text-xs font-semibold text-gray-500">เรียง</span>{([['newest','ล่าสุด'],['oldest','เก่าสุด'],['name_asc','ชื่อ ก-ฮ'],['name_desc','ชื่อ ฮ-ก']] as const).map(([value,label]) => <Link key={value} href={href(villageSlug, keyword, category, value)} className={chip(sort === value)}>{label}</Link>)}<Link href={`/${villageSlug}/places`} className={chip(false)}>ล้างตัวกรอง</Link></>} />; }
