"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FileUpload } from "@/components/ui/file-upload";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { VILLAGE_PLACE_CATEGORY_LABELS } from "@/lib/constants";
import { createVillagePlaceSubmissionAction, createVillagePlaceUpdateSubmissionAction } from "./actions";

const RESIDENT_ALLOWED_PLACE_CATEGORIES = ["SHOP", "OTHER"] as const;
const schema = z.object({ name: z.string().trim().min(2, "กรุณาระบุชื่อสถานที่อย่างน้อย 2 ตัวอักษร"), category: z.string().min(1, "กรุณาเลือกหมวดหมู่"), description: z.string(), address: z.string(), openingHours: z.string(), contactPhone: z.string(), mapUrl: z.string(), latitude: z.string(), longitude: z.string() });
type FormData = z.infer<typeof schema>;
type PlaceRequestFormProps = { mode?: "create" | "update"; targetPlaceId?: string; defaultValues?: FormData & { imageUrls: string[] } };

function fileToDataUrl(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || "")); reader.onerror = reject; reader.readAsDataURL(file); }); }

export function PlaceRequestForm({ mode = "create", targetPlaceId, defaultValues }: PlaceRequestFormProps) {
  const router = useRouter(); const toast = useToast(); const [selectedFiles, setSelectedFiles] = useState<File[]>([]); const [existingImageUrls, setExistingImageUrls] = useState<string[]>(defaultValues?.imageUrls ?? []);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormData>({ resolver: zodResolver(schema), defaultValues: { name: defaultValues?.name ?? "", category: defaultValues?.category ?? "OTHER", description: defaultValues?.description ?? "", address: defaultValues?.address ?? "", openingHours: defaultValues?.openingHours ?? "", contactPhone: defaultValues?.contactPhone ?? "", mapUrl: defaultValues?.mapUrl ?? "", latitude: defaultValues?.latitude ?? "", longitude: defaultValues?.longitude ?? "" } });
  const onSubmit = async (data: FormData) => { let uploadedImageDataUrls: string[] = []; try { uploadedImageDataUrls = await Promise.all(selectedFiles.map(fileToDataUrl)); } catch { toast.error("ไม่สามารถอ่านไฟล์รูปภาพได้"); return; } const payload = { ...data, imageUrls: [...existingImageUrls, ...uploadedImageDataUrls] }; const result = mode === "update" ? await createVillagePlaceUpdateSubmissionAction(targetPlaceId ?? "", payload) : await createVillagePlaceSubmissionAction(payload); if (!result.success) { toast.error(result.error); return; } toast.success(mode === "update" ? "ส่งคำขอแก้ไขสถานที่เรียบร้อยแล้ว" : "ส่งคำขอเพิ่มสถานที่เรียบร้อยแล้ว"); router.push("/resident/places/requests"); router.refresh(); };
  return <form onSubmit={handleSubmit(onSubmit)} className="space-y-8 rounded-xl border border-gray-200 bg-white p-4 sm:p-6"><section className="space-y-4"><div><h2 className="font-semibold text-gray-900">ข้อมูลสถานที่</h2><p className="mt-1 text-sm text-gray-500">ลูกบ้านสามารถเสนอร้านค้า/ตลาดหรือสถานที่ทั่วไปได้</p></div><Input label="ชื่อสถานที่" {...register("name")} error={errors.name?.message} /><Select label="หมวดหมู่" {...register("category")} options={RESIDENT_ALLOWED_PLACE_CATEGORIES.map((value) => ({ value, label: VILLAGE_PLACE_CATEGORY_LABELS[value] ?? value }))} error={errors.category?.message} /><Textarea label="รายละเอียด" rows={5} {...register("description")} error={errors.description?.message} /></section><section className="space-y-4 border-t border-gray-100 pt-6"><h2 className="font-semibold text-gray-900">ข้อมูลติดต่อและตำแหน่ง</h2><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Input label="เบอร์โทรติดต่อ" {...register("contactPhone")} error={errors.contactPhone?.message} /><Input label="เวลาเปิด-ปิด" placeholder="เช่น ทุกวัน 08:00-17:00" {...register("openingHours")} error={errors.openingHours?.message} /></div><Input label="ที่อยู่" {...register("address")} error={errors.address?.message} /><Input label="ลิงก์แผนที่ (ไม่บังคับ)" placeholder="https://maps.google.com/..." {...register("mapUrl")} error={errors.mapUrl?.message} /><details className="rounded-lg border border-gray-200 px-3 py-2"><summary className="cursor-pointer text-sm font-medium text-gray-700">ข้อมูลพิกัดเพิ่มเติม</summary><div className="mt-3 grid grid-cols-1 gap-4 md:grid-cols-2"><Input label="Latitude" placeholder="13.7563" {...register("latitude")} error={errors.latitude?.message} /><Input label="Longitude" placeholder="100.5018" {...register("longitude")} error={errors.longitude?.message} /></div></details></section><section className="space-y-3 border-t border-gray-100 pt-6"><h2 className="font-semibold text-gray-900">รูปภาพ</h2><FileUpload label="อัปโหลดรูปภาพ" accept="image/*" multiple maxSize={5 * 1024 * 1024} onFilesChange={setSelectedFiles} />{existingImageUrls.length > 0 && <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{existingImageUrls.map((url) => <div key={url} className="relative overflow-hidden rounded-lg border border-gray-200 bg-gray-50"><img src={url} alt="รูปสถานที่" className="h-24 w-full object-cover" /><button type="button" onClick={() => setExistingImageUrls((items) => items.filter((item) => item !== url))} className="absolute right-1 top-1 flex h-9 w-9 items-center justify-center rounded-full bg-white/90 text-red-500 hover:bg-white" aria-label="นำรูปภาพออก"><Trash2 className="h-4 w-4" /></button></div>)}</div>}</section><div className="flex flex-col-reverse gap-3 sm:flex-row"><Button type="button" variant="outline" onClick={() => router.back()}>ย้อนกลับ</Button><Button type="submit" isLoading={isSubmitting}>{mode === "update" ? "ส่งคำขอแก้ไขสถานที่" : "ส่งคำขอเพิ่มสถานที่"}</Button></div></form>;
}
