"use client";

import { NewsFilterChip } from "@/components/news/news-toolbar";
import { ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
type SortValue = "newest" | "oldest";
type VisibilityValue = "PUBLIC" | "RESIDENT_ONLY";
type Props = { keyword: string; sort: SortValue; villageName: string; selectedVisibilities: VisibilityValue[]; allowSubmissionsOnly: boolean; suggestionTitles: string[]; canSubmit: boolean };
function href({ keyword, sort, visibilities, allowSubmissionsOnly }: { keyword: string; sort: SortValue; visibilities: VisibilityValue[]; allowSubmissionsOnly: boolean }) { const query = new URLSearchParams(); const values = Array.from(new Set(visibilities)).sort(); if (values.length) query.set("visibility", values.join(",")); if (allowSubmissionsOnly) query.set("allowSubmissions", "1"); if (sort !== "newest") query.set("sort", sort); if (keyword.trim()) query.set("q", keyword.trim()); return query.size ? `/resident/gallery?${query}` : "/resident/gallery"; }
export function ResidentGalleryToolbar({ keyword, sort, villageName, selectedVisibilities, allowSubmissionsOnly, suggestionTitles }: Props) { const has = (value: VisibilityValue) => selectedVisibilities.includes(value); const toggle = (value: VisibilityValue) => href({ keyword, sort, visibilities: has(value) ? selectedVisibilities.filter((item) => item !== value) : [...selectedVisibilities, value], allowSubmissionsOnly }); return <ResidentPageToolbar namespace="resident-gallery" title="แกลเลอรีภาพ" description={`ภาพกิจกรรมและบรรยากาศของ ${villageName}`} search={{ keyword, placeholder: "พิมพ์ชื่ออัลบั้ม", label: "ค้นหาอัลบั้ม", suggestions: suggestionTitles }} activeFilterCount={selectedVisibilities.length + Number(sort !== "newest") + Number(allowSubmissionsOnly)} filters={<><span className="text-xs font-semibold text-gray-500">การมองเห็น</span>{([['PUBLIC','สาธารณะ'],['RESIDENT_ONLY','ลูกบ้าน']] as const).map(([value,label]) => <NewsFilterChip key={value} href={toggle(value)} active={has(value)}>{label}</NewsFilterChip>)}<NewsFilterChip href={href({ keyword, sort, visibilities: selectedVisibilities, allowSubmissionsOnly: !allowSubmissionsOnly })} active={allowSubmissionsOnly}>เปิดให้ส่งรูป</NewsFilterChip><span className="ml-1 text-xs font-semibold text-gray-500">เรียง</span>{([['newest','ล่าสุดก่อน'],['oldest','เก่าก่อน']] as const).map(([value,label]) => <NewsFilterChip key={value} href={href({ keyword, sort: value, visibilities: selectedVisibilities, allowSubmissionsOnly })} active={sort === value}>{label}</NewsFilterChip>)}<NewsFilterChip href="/resident/gallery" active={false}>ล้างตัวกรอง</NewsFilterChip></>} />; }
