import Link from "next/link";
import { AlertCircle, ArrowRight, Building2, CheckCircle2, ClipboardCheck, Home, MapPin, RefreshCw, ShieldAlert, UserRound, Users } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";

const number = (value: number) => value.toLocaleString("en-US");
const date = (value: Date) => value.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
type Check = { title: string; description: string; count: number; items: string[]; severity: "high" | "medium" | "low"; icon: typeof Building2; href: string };

export default async function DataQualityPage() {
  await requireSuperAdminPageSession();
  const staleBefore = new Date(); staleBefore.setDate(staleBefore.getDate() - 14);
  const [villagesWithoutHeadman, residentsWithoutHouse, usersWithoutMembership, emptyHouses, staleBindings, suspendedAdmins, incompleteVillages, duplicateUsers, unlinkedCatalogVillages, villageCount, activeVillageCount, activeMembershipCount, houseCount, personCount] = await Promise.all([
    prisma.village.findMany({ where: { memberships: { none: { role: "HEADMAN", status: "ACTIVE" } } }, select: { id: true, name: true } }),
    prisma.villageMembership.findMany({ where: { role: "RESIDENT", status: "ACTIVE", houseId: null }, take: 100, select: { id: true, user: { select: { name: true } }, village: { select: { name: true } } } }),
    prisma.user.findMany({ where: { accountStatus: "ACTIVE", memberships: { none: {} } }, take: 100, select: { id: true, name: true } }),
    prisma.house.findMany({ where: { memberships: { none: {} }, persons: { none: {} } }, take: 100, select: { id: true, houseNumber: true, village: { select: { name: true } } } }),
    prisma.bindingRequest.findMany({ where: { status: "PENDING", createdAt: { lt: staleBefore } }, take: 100, select: { id: true, createdAt: true, village: { select: { name: true } } } }),
    prisma.villageMembership.findMany({ where: { role: { in: ["HEADMAN", "ASSISTANT_HEADMAN"] }, status: { not: "ACTIVE" } }, take: 100, select: { id: true, user: { select: { name: true } }, village: { select: { name: true } } } }),
    prisma.village.findMany({ where: { OR: [{ province: null }, { district: null }, { subdistrict: null }] }, select: { id: true, name: true } }),
    prisma.user.findMany({ where: { duplicateOfUserId: { not: null } }, take: 100, select: { id: true, name: true } }),
    prisma.village.findMany({ where: { catalogVillageId: null }, take: 100, select: { id: true, name: true } }),
    prisma.village.count(), prisma.village.count({ where: { isActive: true } }), prisma.villageMembership.count({ where: { status: "ACTIVE" } }), prisma.house.count(), prisma.person.count({ where: { status: "ACTIVE" } }),
  ]);
  const checks: Check[] = [
    { title: "Village leadership", description: "Active villages should have an active headman", count: villagesWithoutHeadman.length, items: villagesWithoutHeadman.map((x) => x.name), severity: "high", icon: ShieldAlert, href: "/superadmin/villages" },
    { title: "Pending bindings", description: "Requests waiting for review for more than 14 days", count: staleBindings.length, items: staleBindings.map((x) => `${x.village?.name ?? "Unknown village"} · ${date(x.createdAt)}`), severity: "high", icon: RefreshCw, href: "/superadmin/villages" },
    { title: "Resident location", description: "Active residents without a linked house", count: residentsWithoutHouse.length, items: residentsWithoutHouse.map((x) => `${x.user.name} · ${x.village.name}`), severity: "medium", icon: Home, href: "/superadmin/users" },
    { title: "Unassigned accounts", description: "Active user accounts without a village membership", count: usersWithoutMembership.length, items: usersWithoutMembership.map((x) => x.name), severity: "medium", icon: UserRound, href: "/superadmin/users" },
    { title: "Incomplete location", description: "Villages missing province, district, or subdistrict", count: incompleteVillages.length, items: incompleteVillages.map((x) => x.name), severity: "medium", icon: MapPin, href: "/superadmin/villages" },
    { title: "Unlinked houses", description: "Houses with no member or population record", count: emptyHouses.length, items: emptyHouses.map((x) => `${x.village.name} · House ${x.houseNumber}`), severity: "low", icon: Home, href: "/superadmin/villages" },
    { title: "Duplicate accounts", description: "Accounts already flagged as duplicates", count: duplicateUsers.length, items: duplicateUsers.map((x) => x.name), severity: "low", icon: Users, href: "/superadmin/users" },
    { title: "Inactive administrators", description: "Headman or assistant records that are not active", count: suspendedAdmins.length, items: suspendedAdmins.map((x) => `${x.user.name} · ${x.village.name}`), severity: "low", icon: ShieldAlert, href: "/superadmin/users" },
    { title: "Catalog matching", description: "Villages not linked to the official master catalog", count: unlinkedCatalogVillages.length, items: unlinkedCatalogVillages.map((x) => x.name), severity: "low", icon: Building2, href: "/superadmin/villages" },
  ];
  const issueCount = checks.reduce((total, check) => total + check.count, 0);
  const weighted = checks.reduce((total, check) => total + check.count * (check.severity === "high" ? 5 : check.severity === "medium" ? 2 : 1), 0);
  const score = Math.max(0, Math.min(100, Math.round(100 - weighted / Math.max(villageCount, 1))));
  const scoreLabel = score >= 95 ? "Excellent" : score >= 80 ? "Needs attention" : "Action required";
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700"><ClipboardCheck className="h-4 w-4" /> Governance / Data quality</div><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Data quality centre</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">A clear view of data completeness and records that need attention across the village network.</p></div><div className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3.5 py-2 text-xs text-slate-500 shadow-sm"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Live checks · Updated just now</div></div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Quality score" value={`${score}%`} hint={scoreLabel} icon={CheckCircle2} tone={score >= 80 ? "emerald" : "amber"} /><Metric label="Open findings" value={number(issueCount)} hint="Across 9 checks" icon={AlertCircle} tone="rose" /><Metric label="Active villages" value={number(activeVillageCount)} hint={`${number(villageCount)} total villages`} icon={Building2} tone="cyan" /><Metric label="Population coverage" value={number(personCount)} hint={`${number(activeMembershipCount)} active memberships · ${number(houseCount)} houses`} icon={Users} tone="violet" /></section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,0.65fr)]"><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Quality checks</h2><p className="mt-1 text-sm text-slate-500">Prioritised by operational impact</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{checks.length} checks</span></div><div className="divide-y divide-slate-100">{checks.map((check) => <CheckRow key={check.title} check={check} />)}</div></div>
      <div className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">Network health</p><p className="mt-2 text-5xl font-semibold tracking-tight">{score}<span className="text-2xl text-slate-500">/100</span></p></div><div className="rounded-xl bg-white/10 p-3"><CheckCircle2 className="h-6 w-6 text-emerald-400" /></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${score}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-400">Score reflects the number and severity of findings. Resolve high-impact items first.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Recommended next steps</h2><div className="mt-4 space-y-3"><QuickLink href="/superadmin/villages" icon={Building2} title="Review village profiles" subtitle={`${number(incompleteVillages.length + villagesWithoutHeadman.length)} villages need review`} /><QuickLink href="/superadmin/users" icon={Users} title="Review people & access" subtitle={`${number(usersWithoutMembership.length + duplicateUsers.length)} accounts need review`} /><QuickLink href="/superadmin/logs?view=all" icon={ClipboardCheck} title="Audit recent changes" subtitle="See the full activity trail" /></div></div></div></section>
  </div>;
}

function Metric({ label, value, hint, icon: Icon, tone }: { label: string; value: string | number; hint: string; icon: typeof Building2; tone: "emerald" | "amber" | "rose" | "cyan" | "violet" }) { const tones = { emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", rose: "bg-rose-50 text-rose-600", cyan: "bg-cyan-50 text-cyan-600", violet: "bg-violet-50 text-violet-600" }; return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{value}</p></div><div className={`rounded-xl p-2.5 ${tones[tone]}`}><Icon className="h-5 w-5" /></div></div><p className="mt-3 text-xs text-slate-500">{hint}</p></div>; }
function CheckRow({ check }: { check: Check }) { const Icon = check.icon; const severity = { high: { label: "High", className: "bg-rose-50 text-rose-700" }, medium: { label: "Medium", className: "bg-amber-50 text-amber-700" }, low: { label: "Low", className: "bg-slate-100 text-slate-600" } }[check.severity]; return <div className="flex gap-3 px-5 py-4 transition hover:bg-slate-50"><div className="mt-0.5 rounded-lg bg-slate-100 p-2 text-slate-600"><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold text-slate-800">{check.title}</h3><span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${severity.className}`}>{severity.label}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{check.description}</p>{check.count > 0 ? <details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer font-medium text-cyan-700">View {number(check.count)} record{check.count === 1 ? "" : "s"}</summary><div className="mt-2 max-h-32 space-y-1 overflow-auto rounded-lg bg-slate-50 p-2">{check.items.map((item, index) => <p key={`${item}-${index}`} className="truncate">{item}</p>)}</div></details> : <p className="mt-2 flex items-center gap-1 text-xs font-medium text-emerald-600"><CheckCircle2 className="h-3.5 w-3.5" /> No findings</p>}</div>{check.count > 0 ? <Link href={check.href} className="self-center rounded-lg p-2 text-slate-400 transition hover:bg-cyan-50 hover:text-cyan-700" aria-label={`Review ${check.title}`}><ArrowRight className="h-4 w-4" /></Link> : null}</div>; }
function QuickLink({ href, icon: Icon, title, subtitle }: { href: string; icon: typeof Building2; title: string; subtitle: string }) { return <Link href={href} className="group flex items-center gap-3 rounded-xl border border-slate-100 p-3 transition hover:border-cyan-200 hover:bg-cyan-50"><span className="rounded-lg bg-cyan-50 p-2 text-cyan-700 group-hover:bg-white"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-slate-800">{title}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{subtitle}</span></span><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-cyan-700" /></Link>; }
