import Link from "next/link";
import { BindingRequestStatus, Prisma } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { getWorkspaceVillage, WORKSPACE_PAGE_SIZE, maskPhone } from "@/features/village-workspace/server/queries";
import { BindingReviewForm } from "../binding-review-form";

const statusLabel: Record<string, string> = { PENDING: "รอตรวจสอบ", APPROVED: "อนุมัติแล้ว", REJECTED: "ปฏิเสธแล้ว", CANCELLED: "ยกเลิก" };
export default async function VillageBindingRequestsPage({ params, searchParams }: { params: Promise<{ villageId: string }>; searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  await requireSuperAdminPageSession(); const { villageId } = await params; const search = await searchParams; const page = Math.max(1, Number(search.page) || 1); const q = search.q?.trim() ?? "";
  const where: Prisma.BindingRequestWhereInput = { villageId, ...(search.status && search.status !== "ALL" ? { status: search.status as BindingRequestStatus } : {}), ...(q ? { OR: [{ user: { is: { name: { contains: q, mode: "insensitive" } } } }, { user: { is: { phoneNumber: { contains: q, mode: "insensitive" } } } }, { houseNumber: { contains: q, mode: "insensitive" } }, { house: { is: { houseNumber: { contains: q, mode: "insensitive" } } } }] } : {}) };
  const [village, rows, total, houses] = await Promise.all([
    getWorkspaceVillage(villageId),
    prisma.bindingRequest.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * WORKSPACE_PAGE_SIZE, take: WORKSPACE_PAGE_SIZE, select: { id: true, status: true, houseId: true, houseNumber: true, reviewNote: true, createdAt: true, reviewedAt: true, user: { select: { name: true, phoneNumber: true } }, house: { select: { id: true, villageId: true, houseNumber: true } } } }),
    prisma.bindingRequest.count({ where }),
    prisma.house.findMany({ where: { villageId }, orderBy: { houseNumber: "asc" }, select: { id: true, houseNumber: true } }),
  ]);
  const base = `/superadmin/villages/${villageId}/binding-requests`; const pages = Math.max(1, Math.ceil(total / WORKSPACE_PAGE_SIZE));
  const href = (next: number) => { const p = new URLSearchParams(); if (q) p.set("q", q); if (search.status) p.set("status", search.status); p.set("page", String(next)); return `${base}?${p}`; };
  return <div className="space-y-4"><div><h2 className="text-xl font-semibold text-slate-950">คำขอผูกบ้าน</h2><p className="mt-1 text-sm text-slate-500">ตรวจสอบตัวตนและจับคู่บ้านในทะเบียนของ {village.name}</p></div>
    <form action={base} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 sm:grid-cols-[1fr_auto_auto]"><input name="q" type="search" defaultValue={q} placeholder="ค้นหาชื่อ เบอร์โทร หรือบ้านเลขที่" className="min-h-10 min-w-0 rounded-lg border border-slate-300 px-3 text-sm" /><select name="status" defaultValue={search.status ?? "PENDING"} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ALL">ทุกสถานะ</option><option value="PENDING">รอตรวจสอบ</option><option value="APPROVED">อนุมัติแล้ว</option><option value="REJECTED">ปฏิเสธแล้ว</option></select><div className="flex gap-2"><button className="rounded-lg bg-slate-900 px-4 text-sm font-medium text-white">ค้นหา</button><Link href={base} className="inline-flex items-center rounded-lg border px-3 text-sm">ล้าง</Link></div></form>
    {rows.length ? <div className="grid gap-3">{rows.map((row) => { const proposed = !row.houseId; return <article key={row.id} className="rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-medium text-slate-900">{row.user.name}</p><p className="mt-1 text-xs text-slate-400">{maskPhone(row.user.phoneNumber)} · ส่งเมื่อ {row.createdAt.toLocaleString("th-TH")}</p></div><Badge variant={row.status === "APPROVED" ? "success" : row.status === "REJECTED" ? "danger" : "warning"}>{statusLabel[row.status] ?? row.status}</Badge></div><div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><p className="text-slate-500">บ้านที่ขอผูก</p><p className="mt-1 font-medium text-slate-900">บ้านเลขที่ {row.house?.houseNumber ?? row.houseNumber ?? "ไม่ระบุ"}</p>{proposed ? <p className="mt-1 text-xs text-slate-500">เป็นเลขบ้านที่ผู้ใช้เสนอ ต้องจับคู่กับบ้านในทะเบียนก่อนอนุมัติ</p> : null}</div>{row.reviewNote ? <p className="mt-3 text-sm text-slate-600"><span className="font-medium">เหตุผล:</span> {row.reviewNote}</p> : null}{row.status === "PENDING" ? <BindingReviewForm villageId={villageId} villageName={village.name} requestId={row.id} proposed={proposed} houses={houses} /> : null}</article>; })}</div> : <div className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">ไม่พบคำขอผูกบ้าน</div>}
    <div className="flex items-center justify-between"><p className="text-xs text-slate-500">ทั้งหมด {total} รายการ · หน้า {page}/{pages}</p><div className="flex gap-2">{page > 1 ? <Link href={href(page - 1)} className="rounded-lg border px-3 py-2 text-sm">ก่อนหน้า</Link> : null}{page < pages ? <Link href={href(page + 1)} className="rounded-lg border px-3 py-2 text-sm">ถัดไป</Link> : null}</div></div>
  </div>;
}
