import Link from "next/link";
import { notFound } from "next/navigation";
import { Clock3, MapPin, Pencil, Phone } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { ImageCarousel } from "@/components/ui/image-carousel";
import { AdminPageToolbar } from "@/components/ui/admin-page-toolbar";
import { prisma } from "@/lib/prisma";
import { VILLAGE_PLACE_CATEGORY_LABELS } from "@/lib/constants";
import { orderedPlaceImages } from "@/lib/place-image";
import { getVillagePlaceEmbedMapUrl } from "@/lib/village-place";
import { SuperAdminDeletePlaceButton } from "../superadmin-place-actions";
export default async function SuperAdminPlaceDetail({params}:{params:Promise<{villageId:string;placeId:string}>}){const {villageId,placeId}=await params;const place=await prisma.villagePlace.findFirst({where:{id:placeId,villageId},include:{images:{orderBy:{sortOrder:"asc"}}}});if(!place)notFound();const images=orderedPlaceImages(place.images,place.imageUrls).map(image=>image.url);return <div className="mx-auto w-full max-w-4xl space-y-4"><AdminPageToolbar sticky variant="detail" backHref={`/superadmin/villages/${villageId}/places`} backLabel="กลับสถานที่" title={place.name} description="รายละเอียดสถานที่" actions={<div className="flex flex-wrap gap-2"><Link href={`/superadmin/villages/${villageId}/places/${place.id}/edit`} className="inline-flex items-center rounded-lg border px-3 py-2 text-sm"><Pencil className="mr-1 h-4 w-4"/>แก้ไข</Link><SuperAdminDeletePlaceButton villageId={villageId} placeId={place.id} placeName={place.name}/></div>}/><article className="space-y-5 rounded-xl border bg-white p-4 sm:p-8"><div className="flex flex-wrap gap-2"><Badge variant="outline">{VILLAGE_PLACE_CATEGORY_LABELS[place.category]??place.category}</Badge>{place.isFeatured?<Badge variant="warning">สถานที่สำคัญ</Badge>:null}<Badge variant={place.isPublic?"success":"info"}>{place.isPublic?"สาธารณะ":"เฉพาะลูกบ้าน"}</Badge></div><p className="text-sm text-gray-500">เพิ่มเมื่อ {place.createdAt.toLocaleDateString("th-TH")} · แก้ไขล่าสุด {place.updatedAt.toLocaleDateString("th-TH")}</p>{images.length?<ImageCarousel images={images} altPrefix={place.name}/>:null}<div className="grid gap-3 rounded-xl border bg-gray-50 p-4 text-sm text-gray-700">{place.address?<p className="inline-flex items-start gap-2"><MapPin className="mt-0.5 h-4 w-4"/>{place.address}</p>:null}{place.openingHours?<p className="inline-flex items-start gap-2"><Clock3 className="mt-0.5 h-4 w-4"/>{place.openingHours}</p>:null}{place.contactPhone?<p className="inline-flex items-start gap-2"><Phone className="mt-0.5 h-4 w-4"/>{place.contactPhone}</p>:null}{place.latitude!=null&&place.longitude!=null?<p>พิกัด: {place.latitude}, {place.longitude}</p>:null}</div>{place.description?<p className="whitespace-pre-wrap leading-7 text-gray-700">{place.description}</p>:null}{place.mapUrl?<a href={place.mapUrl} target="_blank" rel="noreferrer" className="text-sm font-medium text-blue-700">เปิดแผนที่</a>:null}{getVillagePlaceEmbedMapUrl(place.latitude,place.longitude)?<iframe title={`map-${place.id}`} src={getVillagePlaceEmbedMapUrl(place.latitude,place.longitude)!} className="h-72 w-full rounded-xl border" loading="lazy"/>:null}</article></div>}
