"use client";

/* eslint-disable react-hooks/set-state-in-effect -- changing the selected area must clear its asynchronous village results. */
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { MapPinned, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SuggestCombobox } from "@/components/ui/suggest-combobox";
import type { ThaiProvince } from "@/lib/thai-geography";
import { formatVillageLabel, formatVillageLocation, villageSearchText } from "@/lib/village-label";
type Village={id:string;slug:string;name:string;moo:string|null;province:string|null;district:string|null;subdistrict:string|null};
const norm=(v:string)=>v.toLowerCase().normalize("NFKC").replace(/\s+/g,"").replace(/[\u200B-\u200D\uFEFF]/g,"");
export function VillagePublicSearch({thaiGeography}:{thaiGeography:ThaiProvince[]}){
 const router=useRouter(); const [province,setProvince]=useState("");const [district,setDistrict]=useState("");const [subdistrict,setSubdistrict]=useState("");const [villageName,setVillageName]=useState("");const [selectedId,setSelectedId]=useState("");const [villages,setVillages]=useState<Village[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
 const selectedProvince=useMemo(()=>thaiGeography.find(x=>x.name===province)??null,[province,thaiGeography]); const selectedDistrict=useMemo(()=>selectedProvince?.districts.find(x=>x.name===district)??null,[district,selectedProvince]);
 const resetVillage=()=>{setVillageName("");setSelectedId("");setError(null)};
 useEffect(()=>{if(!province||!district||!subdistrict||!selectedDistrict?.subdistricts.includes(subdistrict)){setVillages([]);setLoading(false);return}const controller=new AbortController();setLoading(true);fetch(`/api/public/villages?${new URLSearchParams({province,district,subdistrict})}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<{villages:Village[]}>}).then(x=>setVillages(x.villages)).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setVillages([])}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[province,district,subdistrict,selectedDistrict]);
 const suggestions=useMemo(()=>{const q=norm(villageName);return villages.filter(x=>!q||norm(villageSearchText(x)).includes(q))},[villages,villageName]);const selected=villages.find(x=>x.id===selectedId)??null;
 const helper=!subdistrict?"เลือกตำบลก่อนเพื่อค้นหาหมู่บ้าน":loading?"กำลังค้นหาหมู่บ้าน...":villages.length===0?"ยังไม่มีหมู่บ้านที่เปิดใช้งานในพื้นที่นี้":"พิมพ์เพื่อค้นหา หรือเลือกจากรายการ";
 return <div className="mx-auto mt-9 w-full max-w-5xl rounded-2xl border border-white/20 bg-white/10 p-4 text-left shadow-lg backdrop-blur sm:p-5"><div className="mb-4 flex gap-3"><div className="shrink-0 rounded-lg bg-white/15 p-2"><MapPinned aria-hidden="true" className="h-5 w-5"/></div><div><h2 className="text-lg font-semibold">ค้นหาหมู่บ้านของคุณ</h2><p className="mt-0.5 text-sm text-green-100">เลือกพื้นที่สั้น ๆ เพื่อเปิดข้อมูล ข่าวสาร และบริการสาธารณะของหมู่บ้าน</p></div></div><form onSubmit={e=>{e.preventDefault();if(!selected){setError("กรุณาเลือกชื่อหมู่บ้านจากรายการแนะนำ");return}router.push(`/${selected.slug}`)}} className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
 <SuggestCombobox id="public-province" label="จังหวัด" value={province} options={thaiGeography.map(x=>({value:x.name}))} placeholder="เลือกหรือพิมพ์จังหวัด" labelClassName="text-white" inputClassName="min-h-11 bg-white" onChange={v=>{setProvince(v);setDistrict("");setSubdistrict("");resetVillage()}}/>
 <SuggestCombobox id="public-district" label="อำเภอ" value={district} options={(selectedProvince?.districts??[]).map(x=>({value:x.name}))} placeholder={province?"เลือกหรือพิมพ์อำเภอ":"เลือกจังหวัดก่อน"} disabled={!province} helperText={!province?"เลือกจังหวัดก่อน":undefined} labelClassName="text-white" helperClassName="text-green-100" inputClassName="min-h-11 bg-white" onChange={v=>{setDistrict(v);setSubdistrict("");resetVillage()}}/>
 <SuggestCombobox id="public-subdistrict" label="ตำบล" value={subdistrict} options={(selectedDistrict?.subdistricts??[]).map(value=>({value}))} placeholder={district?"เลือกหรือพิมพ์ตำบล":"เลือกอำเภอก่อน"} disabled={!district} helperText={!district?"เลือกอำเภอก่อน":undefined} labelClassName="text-white" helperClassName="text-green-100" inputClassName="min-h-11 bg-white" onChange={v=>{setSubdistrict(v);resetVillage()}}/>
 <SuggestCombobox id="public-village" label="หมู่บ้าน" value={villageName} options={suggestions.map(x=>({value:x.id,label:formatVillageLabel(x.name,x.moo),description:formatVillageLocation(x),searchText:villageSearchText(x)}))} placeholder={subdistrict?"พิมพ์ค้นหาชื่อหมู่บ้าน":"เลือกตำบลก่อน"} disabled={!subdistrict||loading} helperText={helper} emptyMessage={villages.length===0?"ยังไม่มีหมู่บ้านที่เปิดใช้งานในพื้นที่นี้":"ไม่พบชื่อหมู่บ้านที่ตรงกัน"} labelClassName="text-white" helperClassName="text-green-100" inputClassName="min-h-11 bg-white" onChange={v=>{setVillageName(v);setSelectedId("");setError(null)}} onSelect={o=>{const x=villages.find(v=>v.id===o.value);if(x){setSelectedId(x.id);setVillageName(formatVillageLabel(x.name,x.moo))}}}/>
 <div className="sm:col-span-2 lg:col-span-4 flex flex-col gap-3 border-t border-white/15 pt-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-green-100 sm:text-sm">{selected?<>หมู่บ้านที่เลือก: <strong className="text-white">{formatVillageLabel(selected.name,selected.moo)}</strong></>:"เลือกชื่อหมู่บ้านจากรายการเพื่อไปยังหน้าสาธารณะ"}</p><Button type="submit" variant="ghost" className="min-h-11 rounded-xl bg-white px-4 font-semibold text-green-800 hover:bg-green-50"><Search aria-hidden="true" className="h-4 w-4"/>ดูข้อมูลหมู่บ้าน</Button></div>{error?<p className="sm:col-span-2 lg:col-span-4 text-sm text-red-100">{error}</p>:null}</form></div>
}
