import Link from "next/link";
import { BookOpen, Calendar, Compass, ExternalLink, Eye, HeartPulse, Info, Landmark, Mail, MapPin, Newspaper, Phone, School, Sprout, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { VillagePlaceCategory } from "@prisma/client";
import { getCommunityProfile } from "@/features/public-village/server/community-profile";
import { getPublicVillageProfile } from "@/features/public-village/server/public-village-profile";
interface PageProps { params: Promise<{ villageSlug: string }> }
export default async function VillageHomePage({ params }: PageProps) {
  const { villageSlug } = await params; const profile = await getPublicVillageProfile(villageSlug); if (!profile) notFound();
  const { village, placeCounts } = profile; const catalog = village.catalogVillage; const community = getCommunityProfile(catalog?.officialCode);
  const villageName = `บ้าน${village.name}`; const location = [village.subdistrict && `ตำบล${village.subdistrict}`, village.district && `อำเภอ${village.district}`, village.province && `จังหวัด${village.province}`].filter(Boolean).join(" ");
  const stats = [["ประชากรทั้งหมด", catalog?.populationTotal, "คน"], ["จำนวนครัวเรือน", catalog?.householdCount, "ครัวเรือน"]].filter((item): item is [string, number, string] => item[1] != null);
  const nav = [{ href: `/${villageSlug}/news`, icon: Newspaper, label: "ข่าวสาร" }, { href: `/${villageSlug}/calendar`, icon: Calendar, label: "ปฏิทินกิจกรรม" }, { href: `/${villageSlug}/transparency`, icon: Eye, label: "ความโปร่งใส" }, { href: `/${villageSlug}/contacts`, icon: Phone, label: "ช่องทางติดต่อ" }];
  const services = [{ category: VillagePlaceCategory.TEMPLE, label: "วัดและศาสนสถาน", icon: Compass }, { category: VillagePlaceCategory.CLINIC, label: "โรงพยาบาล/คลินิก", icon: HeartPulse }, { category: VillagePlaceCategory.SCHOOL, label: "สถานศึกษา", icon: School }, { category: VillagePlaceCategory.COMMUNITY, label: "สถานที่ชุมชน", icon: Users }];
  const history = village.description ?? community?.history?.[0];
  return <div className="space-y-7 sm:space-y-9"><section className="rounded-2xl bg-gradient-to-br from-emerald-700 to-teal-800 p-5 text-white shadow-sm sm:p-8"><h1 className="text-2xl font-bold sm:text-3xl">{villageName}{village.moo ? ` หมู่ ${village.moo}` : ""}</h1><p className="mt-2 text-sm leading-6 text-emerald-50">{location}</p></section>
    <nav aria-label="ข้อมูลสาธารณะ" className="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4">{nav.map((item) => <Link key={item.href} href={item.href} className="rounded-xl border border-gray-200 bg-white p-4 text-center transition hover:border-emerald-300 hover:shadow-sm"><item.icon className="mx-auto mb-2 h-5 w-5 text-emerald-700" /><span className="block text-sm font-semibold text-gray-700">{item.label}</span></Link>)}</nav>
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Info className="h-5 w-5 text-emerald-700" />ภาพรวมหมู่บ้าน</h2><p className="mt-2 text-sm leading-6 text-gray-600">{location}</p>{stats.length > 0 && <div className="mt-4 grid grid-cols-2 gap-3">{stats.map(([label, value, unit]) => <div key={label} className="rounded-xl bg-gray-50 p-3"><p className="text-xl font-bold text-gray-900">{value.toLocaleString("th-TH")} <span className="text-sm font-medium text-gray-600">{unit}</span></p><p className="mt-1 text-xs text-gray-500">{label}</p></div>)}</div>}</section>
    <section className="max-w-4xl rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><BookOpen className="h-5 w-5 text-emerald-700" />ประวัติชุมชน</h2><p className="mt-3 text-sm leading-7 text-gray-600">{history ?? `ยินดีต้อนรับสู่${villageName} แหล่งข้อมูลและบริการออนไลน์สำหรับชุมชน`}</p><Link href={`/${villageSlug}/info`} className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg border border-emerald-200 px-3 text-sm font-medium text-emerald-800 hover:bg-emerald-50">ดูข้อมูลหมู่บ้านเพิ่มเติม <ExternalLink className="h-3.5 w-3.5" /></Link></section>
    {community && <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Landmark className="h-5 w-5 text-emerald-700" />จุดเด่นของชุมชน</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{community.highlights.slice(0, 3).map((item) => <article key={item.title} className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><Sprout className="h-5 w-5 text-emerald-700" /><h3 className="mt-3 font-semibold text-gray-900">{item.title}</h3><p className="mt-1 text-sm leading-6 text-gray-600">{item.description}</p></article>)}</div></section>}
    <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Compass className="h-5 w-5 text-emerald-700" />สถานที่และบริการในชุมชน</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{services.map((item) => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><item.icon className="h-5 w-5 text-emerald-700" /><div><p className="text-sm text-gray-600">{item.label}</p><p className="text-xl font-bold text-gray-900">{placeCounts.get(item.category) ?? 0}</p></div></div>)}</div></section>
    <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Phone className="h-5 w-5 text-emerald-700" />ช่องทางติดต่อ</h2><div className="mt-3 space-y-3 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">{village.address && <p className="flex gap-3 text-sm text-gray-600"><MapPin className="h-4 w-4 shrink-0 text-gray-400" />{village.address}</p>}{village.phone && <a href={`tel:${village.phone}`} className="flex gap-3 text-sm text-emerald-700"><Phone className="h-4 w-4" />{village.phone}</a>}{village.email && <a href={`mailto:${village.email}`} className="flex gap-3 break-all text-sm text-emerald-700"><Mail className="h-4 w-4" />{village.email}</a>}{!village.address && !village.phone && !village.email && <p className="text-sm text-gray-500">ยังไม่มีข้อมูลติดต่อสาธารณะ</p>}</div></section></div>;
}
