import Link from "next/link";
import { BookOpen, Calendar, Compass, ExternalLink, Eye, Globe, HeartPulse, Home, Info, Landmark, Mail, MapPin, Newspaper, Phone, Route, School, Sprout, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { VillagePlaceCategory } from "@prisma/client";
import { getCommunityProfile } from "@/features/public-village/server/community-profile";
import { getPublicVillageProfile } from "@/features/public-village/server/public-village-profile";
import { formatThaiDate } from "@/lib/utils";

interface PageProps { params: Promise<{ villageSlug: string }> }

export default async function VillageHomePage({ params }: PageProps) {
  const { villageSlug: rawVillageSlug } = await params;
  const profile = await getPublicVillageProfile(rawVillageSlug);
  if (!profile) notFound();
  const { villageSlug, village, placeCounts } = profile;
  const catalog = village.catalogVillage;
  const community = getCommunityProfile(catalog?.officialCode);
  const villageName = `บ้าน${village.name}`;
  const location = [village.subdistrict && `ตำบล${village.subdistrict}`, village.district && `อำเภอ${village.district}`, village.province && `จังหวัด${village.province}`].filter(Boolean).join(" ");
  const mapUrl = catalog?.latitude != null && catalog.longitude != null ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${catalog.latitude},${catalog.longitude}`)}` : null;
  const stats = [{ label: "ประชากรทั้งหมด", value: catalog?.populationTotal, unit: "คน", icon: Users }, { label: "จำนวนครัวเรือน", value: catalog?.householdCount, unit: "ครัวเรือน", icon: Home }, { label: "ประชากรชาย", value: catalog?.malePopulation, unit: "คน", icon: Users }, { label: "ประชากรหญิง", value: catalog?.femalePopulation, unit: "คน", icon: Users }].filter((stat): stat is typeof stat & { value: number } => stat.value != null);
  const services = [{ category: VillagePlaceCategory.TEMPLE, label: "วัดและศาสนสถาน", icon: Compass }, { category: VillagePlaceCategory.CLINIC, label: "โรงพยาบาล/คลินิก", icon: HeartPulse }, { category: VillagePlaceCategory.SCHOOL, label: "สถานศึกษา", icon: School }, { category: VillagePlaceCategory.GOVERNMENT, label: "หน่วยงานและบริการ", icon: Landmark }, { category: VillagePlaceCategory.COMMUNITY, label: "สถานที่ชุมชน", icon: Users }].filter((item) => item.category === VillagePlaceCategory.TEMPLE || item.category === VillagePlaceCategory.CLINIC || placeCounts.has(item.category));
  const history = village.description ? [village.description, community?.history[1]].filter(Boolean) : community?.history;
  const nav = [{ href: `/${villageSlug}/news`, icon: Newspaper, label: "ข่าวสาร" }, { href: `/${villageSlug}/calendar`, icon: Calendar, label: "ปฏิทินกิจกรรม" }, { href: `/${villageSlug}/transparency`, icon: Eye, label: "ความโปร่งใส" }, { href: `/${villageSlug}/contacts`, icon: Phone, label: "ช่องทางติดต่อ" }];

  return <div className="space-y-7 sm:space-y-9">
    <section className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-700 to-teal-800 p-5 text-white shadow-sm sm:p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.13),transparent_48%)]" /><div className="relative"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-emerald-100">ข้อมูลสาธารณะของชุมชน</p><h1 className="text-2xl font-bold sm:text-3xl">{villageName}{village.moo ? ` หมู่ ${village.moo}` : ""}</h1><p className="mt-2 text-sm leading-6 text-emerald-50">{location}</p></div></section>
    <nav aria-label="ข้อมูลสาธารณะ" className="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4">{nav.map((item) => <Link key={item.href} href={item.href} className="group rounded-xl border border-gray-200 bg-white p-4 text-center transition hover:border-emerald-300 hover:shadow-sm"><span className="mx-auto mb-2 inline-flex rounded-xl bg-emerald-50 p-2.5"><item.icon className="h-5 w-5 text-emerald-700" /></span><span className="block text-sm font-semibold text-gray-700">{item.label}</span></Link>)}</nav>
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Info className="h-5 w-5 text-emerald-700" />ข้อมูลพื้นฐานหมู่บ้าน</h2><div className="mt-4 grid gap-5 lg:grid-cols-[1.2fr_1fr]"><div><p className="text-lg font-semibold text-gray-900">{villageName}{village.moo ? ` หมู่ ${village.moo}` : ""}</p><p className="mt-1 text-sm leading-6 text-gray-600">{location}</p><dl className="mt-4 grid grid-cols-2 gap-x-5 gap-y-2 text-sm sm:grid-cols-3"><div><dt className="text-gray-500">ชื่อหมู่บ้าน</dt><dd className="font-medium">{villageName}</dd></div><div><dt className="text-gray-500">หมู่ที่</dt><dd className="font-medium">{village.moo ?? "-"}</dd></div><div><dt className="text-gray-500">รหัสหมู่บ้าน</dt><dd className="font-medium">{catalog?.officialCode ?? "-"}</dd></div></dl></div>{stats.length > 0 && <div className="grid grid-cols-2 gap-3">{stats.map((stat) => <div key={stat.label} className="rounded-xl bg-gray-50 p-3.5"><stat.icon className="h-4 w-4 text-emerald-700" /><p className="mt-3 text-xl font-bold text-gray-900">{stat.value.toLocaleString("th-TH")} <span className="text-sm font-medium text-gray-600">{stat.unit}</span></p><p className="mt-1 text-xs text-gray-500">{stat.label}</p></div>)}</div>}</div>{(catalog?.sourceName || catalog?.sourceUpdatedAt) && <div className="mt-4 space-y-1 border-t border-gray-100 pt-3 text-xs leading-5 text-gray-500">{catalog.sourceName && <p>แหล่งข้อมูล: {catalog.sourceUrl ? <a href={catalog.sourceUrl} target="_blank" rel="noreferrer" className="text-emerald-700 hover:underline">{catalog.sourceName}</a> : catalog.sourceName}</p>}{catalog.sourceUpdatedAt && <p>อัปเดตข้อมูล: {formatThaiDate(catalog.sourceUpdatedAt)}</p>}</div>}</section>
    <section className="max-w-4xl"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><BookOpen className="h-5 w-5 text-emerald-700" />ประวัติชุมชน</h2><div className="mt-3 space-y-3 text-sm leading-7 text-gray-600">{history?.map((paragraph) => <p key={paragraph}>{paragraph}</p>) ?? <p>{`ยินดีต้อนรับสู่${villageName} แหล่งข้อมูลและบริการออนไลน์สำหรับชุมชน`}</p>}</div>{community && <><p className="mt-3 text-xs leading-5 text-gray-500">{community.attribution}</p><Link href={`/${villageSlug}/info`} className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg border border-emerald-200 px-3 text-sm font-medium text-emerald-800 hover:bg-emerald-50">ดูข้อมูลหมู่บ้านเพิ่มเติม <ExternalLink className="h-3.5 w-3.5" /></Link></>}</section>
    {community && <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Landmark className="h-5 w-5 text-emerald-700" />จุดเด่นของชุมชน</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{community.highlights.map((item) => { const Icon = item.kind === "community" ? Sprout : item.kind === "tradition" ? BookOpen : Landmark; return <article key={item.title} className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><Icon className="h-5 w-5 text-emerald-700" /><h3 className="mt-3 font-semibold text-gray-900">{item.title}</h3><p className="mt-1 text-sm leading-6 text-gray-600">{item.description}</p></article>; })}</div></section>}
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><MapPin className="h-5 w-5 text-emerald-700" />ที่ตั้งและการเดินทาง</h2><p className="mt-3 font-semibold text-gray-900">{villageName}{village.moo ? ` หมู่ ${village.moo}` : ""}</p><p className="mt-1 text-sm leading-6 text-gray-600">{location}</p>{community && <p className="mt-3 flex items-start gap-2 text-sm leading-6 text-gray-600"><Route className="mt-0.5 h-4 w-4 shrink-0 text-emerald-700" />{community.transport}</p>}{mapUrl && <a href={mapUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg border border-emerald-200 px-3 text-sm font-medium text-emerald-800 hover:bg-emerald-50"><MapPin className="h-4 w-4" />ดูแผนที่<ExternalLink className="h-3.5 w-3.5" /></a>}</section>
    <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Compass className="h-5 w-5 text-emerald-700" />สถานที่และบริการในชุมชน</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{services.map((stat) => <div key={stat.label} className="flex items-center gap-3 rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><span className="rounded-xl bg-emerald-50 p-2.5"><stat.icon className="h-5 w-5 text-emerald-700" /></span><div><p className="text-xs font-medium text-gray-500">{stat.label}</p><p className="mt-0.5 text-xl font-bold text-gray-900">{placeCounts.get(stat.category) ?? 0}</p></div></div>)}</div></section>
    <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Phone className="h-5 w-5 text-emerald-700" />ช่องทางติดต่อ</h2><div className="mt-3 space-y-3 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">{village.address && <p className="flex gap-3 text-sm text-gray-600"><MapPin className="h-4 w-4 shrink-0 text-gray-400" />{village.address}</p>}{village.phone && <p className="flex gap-3 text-sm"><Phone className="h-4 w-4 shrink-0 text-gray-400" /><a href={`tel:${village.phone}`} className="text-emerald-700 hover:underline">{village.phone}</a></p>}{village.email && <p className="flex gap-3 text-sm"><Mail className="h-4 w-4 shrink-0 text-gray-400" /><a href={`mailto:${village.email}`} className="break-all text-emerald-700 hover:underline">{village.email}</a></p>}{village.website && <p className="flex gap-3 text-sm"><Globe className="h-4 w-4 shrink-0 text-gray-400" /><a href={village.website} target="_blank" rel="noreferrer" className="break-all text-emerald-700 hover:underline">{village.website}</a></p>}{!village.address && !village.phone && !village.email && !village.website && <p className="text-sm text-gray-500">ยังไม่มีข้อมูลติดต่อสาธารณะ</p>}</div></section>
  </div>;
}
