import Link from "next/link";
import { BookOpen, Calendar, Compass, Download, Eye, FileText, FolderOpen, Globe, HeartPulse, Home, Landmark, Mail, MapPin, Newspaper, Phone, School, Sprout, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { VillagePlaceCategory } from "@prisma/client";
import { getCommunityProfile } from "@/features/public-village/server/community-profile";
import { getPublicVillageProfile } from "@/features/public-village/server/public-village-profile";
import { formatThaiDate } from "@/lib/utils";

interface PageProps { params: Promise<{ villageSlug: string }> }

export default async function VillageHomePage({ params }: PageProps) {
  const { villageSlug } = await params;
  const profile = await getPublicVillageProfile(villageSlug);
  if (!profile) notFound();
  const { village, placeCounts } = profile;
  const catalog = village.catalogVillage;
  const community = getCommunityProfile(catalog?.officialCode);
  const villageName = `บ้าน${village.name}`;
  const location = [village.subdistrict && `ตำบล${village.subdistrict}`, village.district && `อำเภอ${village.district}`, village.province && `จังหวัด${village.province}`].filter(Boolean).join(" · ");
  const welcome = village.description ?? `ยินดีต้อนรับสู่${villageName} แหล่งข้อมูลและบริการออนไลน์สำหรับชุมชน`;
  const stats = [["จำนวนประชากร", catalog?.populationTotal, "คน", Users], ["จำนวนครัวเรือน", catalog?.householdCount, "ครัวเรือน", Home], ["ประชากรชาย", catalog?.malePopulation, "คน", Users], ["ประชากรหญิง", catalog?.femalePopulation, "คน", Users]].filter((item): item is [string, number, string, typeof Users] => item[1] != null);
  const nav = [
    ["ข่าวสาร", "news", Newspaper], ["ปฏิทินกิจกรรม", "calendar", Calendar], ["แกลเลอรี", "gallery", FolderOpen], ["สถานที่", "places", Compass], ["เอกสาร", "downloads", Download], ["ความโปร่งใส", "transparency", Eye], ["ติดต่อ", "contacts", Phone],
  ] as const;
  const services = [{ category: VillagePlaceCategory.TEMPLE, label: "วัดและศาสนสถาน", icon: Compass }, { category: VillagePlaceCategory.CLINIC, label: "โรงพยาบาล/คลินิก", icon: HeartPulse }, { category: VillagePlaceCategory.SCHOOL, label: "สถานศึกษา", icon: School }, { category: VillagePlaceCategory.GOVERNMENT, label: "หน่วยงานและบริการ", icon: Landmark }, { category: VillagePlaceCategory.COMMUNITY, label: "สถานที่ชุมชน", icon: Users }];
  const history = village.description ? [village.description, community?.history?.[1]].filter(Boolean) : community?.history;
  const mapUrl = catalog?.latitude != null && catalog.longitude != null ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${catalog.latitude},${catalog.longitude}`)}` : null;

  return <div className="space-y-7 sm:space-y-9">
    <section className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-700 to-teal-800 p-5 text-white shadow-sm sm:p-8"><div className="relative"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-emerald-100">ข้อมูลสาธารณะของชุมชน</p><h1 className="text-2xl font-bold sm:text-3xl">{villageName}{village.moo ? ` หมู่ ${village.moo}` : ""}</h1><p className="mt-2 text-sm leading-6 text-emerald-50">{location}</p><p className="mt-4 max-w-2xl text-sm leading-7 text-emerald-50">{welcome}</p></div></section>
    <nav aria-label="ข้อมูลสาธารณะ" className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{nav.map(([label, path, Icon]) => <Link key={path} href={`/${villageSlug}/${path}`} className="rounded-xl border border-gray-200 bg-white p-3 text-center transition hover:border-emerald-300 hover:shadow-sm sm:p-4"><Icon className="mx-auto mb-2 h-5 w-5 text-emerald-700" /><span className="block text-xs font-semibold text-gray-700 sm:text-sm">{label}</span></Link>)}</nav>
    {stats.length > 0 && <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Users className="h-5 w-5 text-emerald-700" />สถิติสำคัญ</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(([label, value, unit, Icon]) => <div key={label} className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><Icon className="h-4 w-4 text-emerald-700" /><p className="mt-3 text-xl font-bold text-gray-900">{value.toLocaleString("th-TH")} <span className="text-sm font-medium text-gray-600">{unit}</span></p><p className="mt-1 text-xs text-gray-500">{label}</p></div>)}</div></section>}
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-bold text-gray-900">ข้อมูลพื้นฐาน</h2><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-4 text-sm sm:grid-cols-3"><div><dt className="text-gray-500">ชื่อหมู่บ้าน</dt><dd className="font-medium">{villageName}</dd></div><div><dt className="text-gray-500">หมู่ที่</dt><dd className="font-medium">{village.moo ?? "-"}</dd></div><div><dt className="text-gray-500">รหัสหมู่บ้าน</dt><dd className="font-medium">{catalog?.officialCode ?? "-"}</dd></div><div><dt className="text-gray-500">ตำบล</dt><dd className="font-medium">{village.subdistrict ?? "-"}</dd></div><div><dt className="text-gray-500">อำเภอ</dt><dd className="font-medium">{village.district ?? "-"}</dd></div><div><dt className="text-gray-500">จังหวัด</dt><dd className="font-medium">{village.province ?? "-"}</dd></div></dl></section>
    <section className="max-w-4xl rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><BookOpen className="h-5 w-5 text-emerald-700" />ประวัติชุมชน</h2><div className="mt-3 space-y-4 text-sm leading-7 text-gray-600">{history?.map((paragraph) => <p key={paragraph}>{paragraph}</p>) ?? <p>{welcome}</p>}</div>{community && <p className="mt-4 border-t border-gray-100 pt-3 text-xs leading-5 text-gray-500">{community.attribution}</p>}</section>
    {community && <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Landmark className="h-5 w-5 text-emerald-700" />จุดเด่นของชุมชน</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{community.highlights.map((item) => <article key={item.title} className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><Sprout className="h-5 w-5 text-emerald-700" /><h3 className="mt-3 font-semibold text-gray-900">{item.title}</h3><p className="mt-1 text-sm leading-6 text-gray-600">{item.description}</p></article>)}</div></section>}
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><MapPin className="h-5 w-5 text-emerald-700" />ที่ตั้งและการเดินทาง</h2><p className="mt-3 font-semibold text-gray-900">{villageName}{village.moo ? ` หมู่ ${village.moo}` : ""}</p><p className="mt-1 text-sm leading-6 text-gray-600">{location}</p>{community && <p className="mt-3 flex items-start gap-2 text-sm leading-6 text-gray-600"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-emerald-700" />{community.transport}</p>}{mapUrl && <a href={mapUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg border border-emerald-200 px-3 text-sm font-medium text-emerald-800 hover:bg-emerald-50">ดูแผนที่ <Globe className="h-4 w-4" /></a>}</section>
    <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Compass className="h-5 w-5 text-emerald-700" />สถานที่และบริการที่สำคัญ</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{services.map((item) => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><item.icon className="h-5 w-5 shrink-0 text-emerald-700" /><div><p className="text-sm text-gray-600">{item.label}</p><p className="text-xl font-bold text-gray-900">{placeCounts.get(item.category) ?? 0}</p></div></div>)}</div></section>
    <section><h2 className="flex items-center gap-2 text-lg font-bold text-gray-900"><Phone className="h-5 w-5 text-emerald-700" />ช่องทางติดต่อ</h2><div className="mt-3 space-y-3 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">{village.address && <p className="flex gap-3 text-sm leading-6 text-gray-600"><MapPin className="h-4 w-4 shrink-0 text-gray-400" />{village.address}</p>}{village.phone && <a href={`tel:${village.phone}`} className="flex gap-3 text-sm text-emerald-700"><Phone className="h-4 w-4 shrink-0" />{village.phone}</a>}{village.email && <a href={`mailto:${village.email}`} className="flex gap-3 break-all text-sm text-emerald-700"><Mail className="h-4 w-4 shrink-0" />{village.email}</a>}{village.website && <a href={village.website} target="_blank" rel="noreferrer" className="flex gap-3 break-all text-sm text-emerald-700"><Globe className="h-4 w-4 shrink-0" />{village.website}</a>}{!village.address && !village.phone && !village.email && !village.website && <p className="text-sm text-gray-500">ยังไม่มีข้อมูลติดต่อสาธารณะ</p>}</div></section>
    {(catalog?.sourceName || catalog?.sourceUpdatedAt) && <section className="border-t border-gray-100 pt-4 text-xs leading-5 text-gray-500">{catalog.sourceName && <p>แหล่งข้อมูล: {catalog.sourceUrl ? <a href={catalog.sourceUrl} target="_blank" rel="noreferrer" className="text-emerald-700 hover:underline">{catalog.sourceName}</a> : catalog.sourceName}</p>}{catalog.sourceUpdatedAt && <p>อัปเดตข้อมูล: {formatThaiDate(catalog.sourceUpdatedAt)}</p>}</section>}
  </div>;
}
