import { NotificationStatus } from "@prisma/client";
import { notFound } from "next/navigation";
import { AdminPageToolbar } from "@/components/ui/admin-page-toolbar";
import { feedbackMetadataString, getFeedbackById, markFeedbackAsReadIfUnread } from "@/features/feedback/server/feedback-service";
import { updateAdminFeedbackStatusAction } from "../actions";
import { requireVillagePagePermission } from "@/lib/admin-permission.server";

export default async function AdminFeedbackDetailPage({ params }: { params: Promise<{ feedbackId: string }> }) {
  const context = await requireVillagePagePermission("feedback.manage", { callbackUrl: "/admin/feedback" });
  const { feedbackId } = await params; const initial = await getFeedbackById(feedbackId, context.villageId); if (!initial) notFound();
  await markFeedbackAsReadIfUnread(feedbackId, context.villageId); const feedback = await getFeedbackById(feedbackId, context.villageId); if (!feedback) notFound();
  const name = feedbackMetadataString(feedback.metadata, "name"); const email = feedbackMetadataString(feedback.metadata, "email");
  const action = (operation: "unread" | "archive" | "restore", label: string) => <form action={updateAdminFeedbackStatusAction}><input type="hidden" name="feedbackId" value={feedback.id} /><input type="hidden" name="operation" value={operation} /><button className="min-h-9 rounded-md border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-green-600">{label}</button></form>;
  return <div data-admin-compact-top className="space-y-4"><AdminPageToolbar compact sticky variant="detail" title="รายละเอียดความคิดเห็น" backHref="/admin/feedback" backLabel="กลับรายการความคิดเห็น" backPlacement="header-end" actions={<div className="flex flex-wrap gap-2">{feedback.status === NotificationStatus.ARCHIVED ? action("restore", "นำกลับเข้ากล่องขาเข้า") : <>{action("unread", "ตั้งเป็นยังไม่ได้อ่าน")}{action("archive", "เก็บถาวร")}</>}</div>} /><main className="mx-auto w-full max-w-3xl"><article className="rounded-xl border border-gray-200 bg-white p-5 sm:p-8"><h1 className="break-words text-2xl font-bold text-gray-950">{feedback.title || "รายละเอียดความคิดเห็น"}</h1><div className="mt-6 border-t pt-6"><p className="whitespace-pre-wrap break-words text-base leading-8 text-gray-800">{feedback.body || "ไม่มีรายละเอียด"}</p></div><section className="mt-8 border-t pt-6" aria-labelledby="sender"><h2 id="sender" className="font-semibold text-gray-900">ข้อมูลผู้ส่ง</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-gray-500">ชื่อ</dt><dd className="break-words font-medium">{name || "ไม่ระบุ"}</dd></div><div><dt className="text-gray-500">อีเมล</dt><dd className="break-all font-medium">{email || "ไม่ระบุ"}</dd></div><div><dt className="text-gray-500">ส่งเมื่อ</dt><dd className="font-medium">{feedback.createdAt.toLocaleString("th-TH")}</dd></div></dl></section></article></main></div>;
}
