"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { adminCreateAppointmentAction } from "@/app/(resident)/resident/appointments/actions";
type Resident = { id: string; name: string; phone: string; houseNumber: string };
export function CreateAppointmentForm({ onClose }: { onClose: () => void }) { const router = useRouter(); const [q, setQ] = useState(""); const [items, setItems] = useState<Resident[]>([]); const [resident, setResident] = useState<Resident | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [date, setDate] = useState(""); const [startTime, setStart] = useState(""); const [endTime, setEnd] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); useEffect(() => { const timer = setTimeout(() => fetch(`/api/appointments/residents?q=${encodeURIComponent(q)}`).then((r) => r.ok ? r.json() : []).then(setItems).catch(() => setItems([])), 250); return () => clearTimeout(timer); }, [q]); return <form className="space-y-3" onSubmit={async (e) => { e.preventDefault(); if (!resident) { setError("กรุณาเลือกลูกบ้าน"); return; } setPending(true); const result = await adminCreateAppointmentAction({ residentUserId: resident.id, title, description, date, startTime, endTime, message }); if (!result.success) { setError(result.error); setPending(false); return; } onClose(); router.refresh(); }}><div className="relative"><Input label="ค้นหาลูกบ้าน" value={resident ? resident.name : q} onChange={(e) => { setResident(null); setQ(e.target.value); }} placeholder="ชื่อ / เบอร์ / เลขบ้าน" />{!resident && q ? <div className="absolute z-20 mt-1 max-h-48 w-full overflow-auto rounded-lg border bg-white shadow-lg">{items.length ? items.map((item) => <button key={item.id} type="button" className="block w-full px-3 py-2 text-left text-sm hover:bg-gray-50" onClick={() => { setResident(item); setQ(""); }}>{item.name} · บ้าน {item.houseNumber || "-"} · {item.phone}</button>) : <p className="p-3 text-sm text-gray-500">ไม่พบลูกบ้าน</p>}</div> : null}</div><Input label="เรื่องนัดหมาย" value={title} onChange={(e) => setTitle(e.target.value)} required minLength={3} /><Textarea label="รายละเอียด" value={description} onChange={(e) => setDescription(e.target.value)} rows={3} /><div className="grid gap-3 sm:grid-cols-3"><Input label="วันที่" type="date" value={date} onChange={(e) => setDate(e.target.value)} required /><Input label="เริ่มเวลา" type="time" value={startTime} onChange={(e) => setStart(e.target.value)} required /><Input label="สิ้นสุด" type="time" value={endTime} onChange={(e) => setEnd(e.target.value)} required /></div><Textarea label="หมายเหตุถึงลูกบ้าน" value={message} onChange={(e) => setMessage(e.target.value)} rows={2} />{error ? <p className="text-sm text-red-600">{error}</p> : null}<div className="flex gap-2"><Button type="submit" isLoading={pending}>สร้างและเสนอวันเวลา</Button><Button type="button" variant="outline" onClick={onClose}>ยกเลิก</Button></div></form>; }
