import Link from "next/link";
import { MembershipStatus, VillageMembershipRole } from "@prisma/client";
import { redirect } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { MEMBERSHIP_ROLE_LABELS } from "@/lib/constants";
import { computeLandingPath, getAdminMembership, getSessionContextFromServerCookies } from "@/lib/access-control";
import { prisma } from "@/lib/prisma";
import { ACCESS_MEMBERSHIP_STATUSES } from "@/lib/settings-access";
import { AccessTable } from "./access-table";

type Props = { searchParams?: Promise<{ q?: string; role?: string; status?: string; page?: string }> };
const PAGE_SIZE = 20;
export default async function Page({ searchParams }: Props) {
  const params = (searchParams ? await searchParams : {}) ?? {}; const session = await getSessionContextFromServerCookies(); if (!session) redirect("/auth/login?callbackUrl=/admin/settings/access"); const adminMembership = getAdminMembership(session); if (!adminMembership) redirect(computeLandingPath(session));
  const q = params.q?.trim() ?? ""; const role = Object.values(VillageMembershipRole).includes(params.role as VillageMembershipRole) ? params.role as VillageMembershipRole : null; const status = params.status === MembershipStatus.ACTIVE || params.status === MembershipStatus.SUSPENDED ? params.status : null; const requestedPage = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1);
  const where = { villageId: adminMembership.villageId, status: status ? status : { in: [...ACCESS_MEMBERSHIP_STATUSES] }, ...(role ? { role } : {}), ...(q ? { OR: [{ user: { name: { contains: q, mode: "insensitive" as const } } }, { user: { phoneNumber: { contains: q } } }, { house: { houseNumber: { contains: q } } }] } : {}) };
  const total = await prisma.villageMembership.count({ where }); const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE)); const page = Math.min(requestedPage, totalPages);
  const members = await prisma.villageMembership.findMany({ where, select: { id: true, userId: true, role: true, status: true, user: { select: { name: true, phoneNumber: true } }, house: { select: { houseNumber: true } } }, orderBy: [{ role: "asc" }, { user: { name: "asc" } }], skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE });
  const query = new URLSearchParams(); if (q) query.set("q", q); if (role) query.set("role", role); if (status) query.set("status", status); const pageHref = (next: number) => { const nextQuery = new URLSearchParams(query); nextQuery.set("page", String(next)); return `/admin/settings/access?${nextQuery}`; };
  const hasFilters = Boolean(q || role || status);
  return <section className="flex h-full min-h-0 flex-col overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><header className="shrink-0 border-b border-gray-200 p-4 sm:p-5"><h2 className="text-base font-semibold text-gray-900">สิทธิ์ผู้ใช้</h2><p className="mt-1 text-sm text-gray-500">จัดการบทบาทและสถานะของสมาชิกจริงในหมู่บ้าน</p><form method="get" className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-[minmax(14rem,1fr)_12rem_12rem_auto]"><input name="q" defaultValue={q} placeholder="ค้นหาชื่อ เบอร์โทร หรือบ้านเลขที่" aria-label="ค้นหาสมาชิก" className="min-h-10 rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-green-500 focus:outline-none focus:ring-2 focus:ring-green-500/20" /><Select name="role" defaultValue={role ?? "ALL"} aria-label="กรองตามบทบาท" options={[{ value: "ALL", label: "ทุกบทบาท" }, ...Object.values(VillageMembershipRole).map((value) => ({ value, label: MEMBERSHIP_ROLE_LABELS[value] }))]} /><Select name="status" defaultValue={status ?? "ALL"} aria-label="กรองตามสถานะ" options={[{ value: "ALL", label: "ทุกสถานะ" }, { value: MembershipStatus.ACTIVE, label: "ใช้งานอยู่" }, { value: MembershipStatus.SUSPENDED, label: "ระงับการใช้งาน" }]} /><div className="flex items-center gap-2"><Button type="submit" variant="outline">ค้นหา</Button>{hasFilters ? <Link href="/admin/settings/access" className="inline-flex min-h-9 items-center justify-center rounded-lg px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-100">ล้าง</Link> : null}</div></form></header>
    {members.length ? <AccessTable currentUserId={session.id} members={members.map((item) => ({ id: item.id, userId: item.userId, name: item.user.name, phone: item.user.phoneNumber, houseNumber: item.house?.houseNumber ?? null, role: item.role, status: item.status }))} /> : <div className="flex min-h-48 flex-1 items-center justify-center p-6 text-center text-sm text-gray-500">{hasFilters ? "ไม่พบผู้ใช้ที่ตรงกับเงื่อนไข" : "ยังไม่มีสมาชิกที่จัดการสิทธิ์ได้"}</div>}
    <footer className="flex shrink-0 items-center justify-between gap-3 border-t border-gray-200 bg-white px-4 py-3 text-sm text-gray-500"><span>ทั้งหมด {total.toLocaleString("th-TH")} คน</span><div className="flex items-center gap-2"><Link aria-disabled={page <= 1} tabIndex={page <= 1 ? -1 : undefined} href={pageHref(Math.max(1, page - 1))} className={`rounded-lg border border-gray-300 px-3 py-1.5 text-sm font-medium ${page <= 1 ? "pointer-events-none opacity-50" : "text-gray-700 hover:bg-gray-50"}`}>ก่อนหน้า</Link><span>{page}/{totalPages}</span><Link aria-disabled={page >= totalPages} tabIndex={page >= totalPages ? -1 : undefined} href={pageHref(Math.min(totalPages, page + 1))} className={`rounded-lg border border-gray-300 px-3 py-1.5 text-sm font-medium ${page >= totalPages ? "pointer-events-none opacity-50" : "text-gray-700 hover:bg-gray-50"}`}>ถัดไป</Link></div></footer>
  </section>;
}
