import Link from "next/link";
import { ArrowLeft, Clock } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { AppointmentTimeline } from "@/components/appointments/appointment-timeline";
import { SuperAdminPageHeaderRegistration } from "@/components/layout/superadmin-page-header-context";
import { APPOINTMENT_STAGE_LABELS } from "@/lib/constants";
import { formatThaiDate, formatThaiDateTime } from "@/lib/utils";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { getWorkspaceVillage } from "@/features/village-workspace/server/queries";
import { SuperAdminAppointmentActions } from "./superadmin-appointment-actions";

type Props = { params: Promise<{ villageId: string; appointmentId: string }> };
const variants: Record<string, "default" | "info" | "success" | "warning" | "danger"> = { PENDING_APPROVAL: "warning", TIME_SUGGESTED: "info", APPROVED: "success", REJECTED: "danger", CANCELLED: "default", COMPLETED: "info" };
function metadata(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function valueFor(record: Record<string, unknown>, key: string) { return typeof record[key] === "string" && record[key].trim() ? record[key].trim() : null; }
function descriptionParts(value: string | null) { if (!value) return { description: null, preferredTime: null }; const lines = value.split(/\r?\n/); const index = lines.findIndex((line) => line.trim().startsWith("ช่วงเวลาที่สะดวก:")); return index < 0 ? { description: value, preferredTime: null } : { description: lines.filter((_, i) => i !== index).join("\n").trim() || null, preferredTime: lines[index].replace(/^\s*ช่วงเวลาที่สะดวก:\s*/, "").trim() || null }; }

export default async function Page({ params }: Props) {
  await requireSuperAdminPageSession(); const { villageId, appointmentId } = await params; const village = await getWorkspaceVillage(villageId); const appointment = await prisma.appointment.findFirst({ where: { id: appointmentId, villageId }, include: { user: { select: { name: true, phoneNumber: true, email: true } }, slot: true, timeline: { orderBy: { createdAt: "asc" }, include: { actor: { select: { name: true, email: true, memberships: { where: { status: "ACTIVE" }, select: { villageId: true, role: true } } } } } } } }); if (!appointment) notFound();
  const content = descriptionParts(appointment.description); const label = appointment.stage === "TIME_SUGGESTED" ? "รอลูกบ้านยืนยันเวลา" : APPOINTMENT_STAGE_LABELS[appointment.stage]; const terminal = ["REJECTED", "CANCELLED", "COMPLETED"].includes(appointment.stage); const adminCreated = metadata(appointment.timeline[0]?.metadata).adminCreated === true; const canPropose = !adminCreated && appointment.stage === "PENDING_APPROVAL"; const canReject = !adminCreated && appointment.stage === "PENDING_APPROVAL"; const canCancel = ["TIME_SUGGESTED", "APPROVED"].includes(appointment.stage); const latest = appointment.timeline.at(-1); const latestData = metadata(latest?.metadata); const latestName = latest?.actor?.name || latest?.actor?.email || (latestData.actorRole === "SUPERADMIN" ? "ผู้ดูแลระบบระดับสูง" : null); const latestRole = latestData.actorRole === "SUPERADMIN" ? "Super Admin" : latest?.actor?.memberships.find((item) => item.villageId === villageId)?.role ?? null; const base = `/superadmin/villages/${villageId}/appointments`;
  return <div className="mx-auto max-w-4xl space-y-5"><SuperAdminPageHeaderRegistration priority={1} context={{ title: "นัดหมาย", description: `ติดตามและจัดการนัดหมายของ ${village.name} เพื่อการสนับสนุนงานหมู่บ้าน` }} /><Link href={base} className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-800"><ArrowLeft className="h-4 w-4" />กลับรายการนัดหมาย</Link><section className="rounded-xl border border-gray-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-xl font-bold text-slate-900">{appointment.title}</h2>{content.description ? <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{content.description}</p> : null}</div><Badge variant={variants[appointment.stage] ?? "default"}>{label}</Badge></div><div className="mt-5 grid gap-x-8 gap-y-4 border-t border-gray-100 pt-4 text-sm sm:grid-cols-2"><div><p className="text-xs text-slate-500">ผู้ขอนัดหมาย</p><p className="mt-1 font-medium">{appointment.user.name || appointment.user.email || "-"}</p></div><div><p className="text-xs text-slate-500">เบอร์โทรศัพท์</p><p className="mt-1 font-medium">{appointment.user.phoneNumber || "-"}</p></div><div><p className="text-xs text-slate-500">สถานะปัจจุบัน</p><p className="mt-1">{label}</p></div><div><p className="text-xs text-slate-500">สร้างเมื่อ</p><p className="mt-1">{formatThaiDateTime(appointment.createdAt)}</p></div>{appointment.slot ? <div><p className="text-xs text-slate-500">{["APPROVED", "COMPLETED"].includes(appointment.stage) ? "วันนัดหมาย" : "วันเวลาที่เสนอ"}</p><p className="mt-1 flex items-center gap-1.5"><Clock className="h-4 w-4 text-slate-500" />{formatThaiDate(appointment.slot.date)} เวลา {appointment.slot.startTime}-{appointment.slot.endTime}</p></div> : null}{content.preferredTime ? <div><p className="text-xs text-slate-500">ช่วงเวลาที่สะดวก</p><p className="mt-1">{content.preferredTime}</p></div> : null}</div>{appointment.reviewNote ? <div className="mt-4 border-t border-gray-100 pt-4 text-sm"><p className="text-xs text-slate-500">หมายเหตุ/เหตุผลล่าสุด</p><p className="mt-1 whitespace-pre-wrap break-words text-slate-700">{appointment.reviewNote}</p></div> : null}{latest ? <div className="mt-4 border-t border-gray-100 pt-4 text-sm"><p className="text-xs text-slate-500">ผู้ดำเนินการล่าสุด</p><p className="mt-1">{latestName ?? "ระบบ"}{latestRole ? ` (${latestRole})` : ""} · {formatThaiDateTime(latest.createdAt)}</p></div> : null}</section>{!terminal && (canPropose || canReject || canCancel) ? <SuperAdminAppointmentActions villageId={villageId} appointmentId={appointment.id} canPropose={canPropose} canReject={canReject} canCancel={canCancel} /> : null}<section className="rounded-xl border border-gray-200 bg-white p-5 sm:p-6"><h3 className="font-semibold">ประวัติการดำเนินการ</h3><AppointmentTimeline entries={appointment.timeline} villageId={villageId} /></section></div>;
}
