import Link from "next/link";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { prisma } from "@/lib/prisma";
import { requireSuperAdminPageSession } from "@/lib/superadmin";
import { changeSuperAdminAppointmentStageAction, proposeSuperAdminAppointmentTimeAction } from "../../operational-actions";

export default async function Page({ params }: { params: Promise<{ villageId: string; appointmentId: string }> }) {
  await requireSuperAdminPageSession(); const { villageId, appointmentId } = await params;
  const row = await prisma.appointment.findFirst({ where: { id: appointmentId, villageId }, include: { user: { select: { name: true, phoneNumber: true } }, slot: true, timeline: { orderBy: { createdAt: "desc" } } } });
  if (!row) notFound(); const base = `/superadmin/villages/${villageId}/appointments`;
  return <div className="mx-auto max-w-4xl space-y-4"><Link href={base} className="text-sm text-slate-500">← กลับรายการนัดหมาย</Link><section className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-semibold">{row.title}</h2><p className="mt-2 text-sm text-slate-600">{row.description || "-"}</p></div><Badge variant="outline">{row.stage}</Badge></div><dl className="mt-5 grid gap-3 border-t pt-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-400">ผู้ขอนัด</dt><dd>{row.user.name}</dd></div><div><dt className="text-slate-400">โทรศัพท์</dt><dd>{row.user.phoneNumber}</dd></div><div><dt className="text-slate-400">เวลานัด</dt><dd>{row.slot ? `${row.slot.date.toLocaleDateString("th-TH")} ${row.slot.startTime}` : "ยังไม่กำหนด"}</dd></div><div><dt className="text-slate-400">เหตุผลล่าสุด</dt><dd>{row.reviewNote ?? "-"}</dd></div></dl></section>{row.stage === "PENDING_APPROVAL" ? <section className="rounded-xl border bg-white p-5"><h3 className="font-semibold">เสนอวันเวลา</h3><form action={proposeSuperAdminAppointmentTimeAction.bind(null, villageId, row.id)} className="mt-3 grid gap-3 sm:grid-cols-2"><input type="date" name="date" required className="min-h-10 rounded-lg border px-3" /><input type="time" name="startTime" required className="min-h-10 rounded-lg border px-3" /><input name="supportReason" required minLength={5} placeholder="เหตุผลในการดำเนินการ" className="min-h-10 rounded-lg border px-3 sm:col-span-2" /><button className="min-h-10 rounded-lg bg-slate-900 px-4 text-sm text-white sm:col-span-2">เสนอเวลา</button></form><form action={changeSuperAdminAppointmentStageAction.bind(null, villageId, row.id)} className="mt-4 grid gap-3"><input type="hidden" name="action" value="REJECT" /><input name="supportReason" required minLength={5} placeholder="เหตุผลในการปฏิเสธ" className="min-h-10 rounded-lg border px-3" /><button className="min-h-10 rounded-lg border border-rose-300 px-4 text-sm text-rose-700">ปฏิเสธคำขอ</button></form></section> : null}{row.stage === "TIME_SUGGESTED" || row.stage === "APPROVED" ? <section className="rounded-xl border bg-white p-5"><h3 className="font-semibold">ยกเลิกนัดหมาย</h3><form action={changeSuperAdminAppointmentStageAction.bind(null, villageId, row.id)} className="mt-3 grid gap-3"><input type="hidden" name="action" value="CANCEL" /><input name="supportReason" required minLength={5} placeholder="เหตุผลในการยกเลิก" className="min-h-10 rounded-lg border px-3" /><button className="min-h-10 rounded-lg border border-rose-300 px-4 text-sm text-rose-700">ยกเลิกนัดหมาย</button></form></section> : null}<section className="rounded-xl border bg-white p-5"><h3 className="font-semibold">ประวัติ</h3><div className="mt-3 divide-y">{row.timeline.map(item => <div key={item.id} className="py-3 text-sm"><p>{item.action}</p><p className="mt-1 text-xs text-slate-400">{item.createdAt.toLocaleString("th-TH")}</p></div>)}</div></section></div>;
}
