"use client";

import { useState } from "react";
import { CalendarClock, XCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { changeSuperAdminAppointmentStageAction, proposeSuperAdminAppointmentTimeAction } from "../../operational-actions";

type Mode = "PROPOSE" | "REJECT" | "CANCEL" | null;
type Props = { villageId: string; appointmentId: string; canPropose: boolean; canReject: boolean; canCancel: boolean };
export function SuperAdminAppointmentActions({ villageId, appointmentId, canPropose, canReject, canCancel }: Props) {
  const router = useRouter(); const { pushToast } = useToast(); const [mode, setMode] = useState<Mode>(null); const [reasonOpen, setReasonOpen] = useState(false); const [date, setDate] = useState(""); const [startTime, setStartTime] = useState(""); const [businessReason, setBusinessReason] = useState(""); const [supportReason, setSupportReason] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const closeAction = () => { if (!pending) { setMode(null); setError(""); } };
  const validateAction = (event: React.FormEvent) => { event.preventDefault(); if (mode === "PROPOSE" && (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !/^([01]\d|2[0-3]):[0-5]\d$/.test(startTime) || Number(startTime.slice(0, 2)) >= 23)) { setError("กรุณาระบุวันและเวลาเริ่มต้นที่ถูกต้อง (ไม่เกิน 22:59 น.)"); return; } if ((mode === "REJECT" || mode === "CANCEL") && (businessReason.trim().length < 5 || businessReason.trim().length > 500)) { setError("กรุณาระบุเหตุผล 5–500 ตัวอักษร"); return; } setError(""); setSupportReason(""); setReasonOpen(true); };
  const submit = async () => { if (!mode || pending || supportReason.trim().length < 5 || supportReason.trim().length > 500) return; setPending(true); setError(""); const formData = new FormData(); formData.set("supportReason", supportReason.trim()); if (mode === "PROPOSE") { formData.set("date", date); formData.set("startTime", startTime); } else { formData.set("action", mode); formData.set("businessReason", businessReason.trim()); } const result = mode === "PROPOSE" ? await proposeSuperAdminAppointmentTimeAction(villageId, appointmentId, formData) : await changeSuperAdminAppointmentStageAction(villageId, appointmentId, formData); setPending(false); if (!result.success) { setError(result.error); pushToast({ tone: "error", title: "ดำเนินการไม่สำเร็จ", description: result.error }); return; } setReasonOpen(false); setMode(null); setBusinessReason(""); setSupportReason(""); pushToast({ tone: "success", title: result.message }); router.refresh(); };
  const actionTitle = mode === "PROPOSE" ? "เสนอวันเวลา" : mode === "REJECT" ? "ปฏิเสธคำขอนัดหมาย" : "ยกเลิกนัดหมาย"; const actionSubmit = mode === "PROPOSE" ? "ดำเนินการต่อ" : mode === "REJECT" ? "ดำเนินการต่อเพื่อปฏิเสธ" : "ดำเนินการต่อเพื่อยกเลิก"; const reasonInvalid = supportReason.trim().length < 5 || supportReason.trim().length > 500;
  return <><section className="flex flex-wrap justify-end gap-2">{canPropose ? <Button type="button" onClick={() => { setMode("PROPOSE"); setError(""); }}><CalendarClock className="mr-1.5 h-4 w-4" />เสนอวันเวลา</Button> : null}{canReject ? <Button type="button" variant="danger" onClick={() => { setMode("REJECT"); setError(""); }}>ปฏิเสธคำขอ</Button> : null}{canCancel ? <Button type="button" variant="danger" onClick={() => { setMode("CANCEL"); setError(""); }}><XCircle className="mr-1.5 h-4 w-4" />ยกเลิกนัดหมาย</Button> : null}</section><Dialog open={Boolean(mode)} onClose={closeAction} closeOnBackdrop={false} closeOnEscape={!pending} title={actionTitle} footer={<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" disabled={pending} onClick={closeAction}>ยกเลิก</Button><Button type="submit" form="superadmin-appointment-action" disabled={pending}>{actionSubmit}</Button></div>}><form id="superadmin-appointment-action" onSubmit={validateAction} className="space-y-4">{mode === "PROPOSE" ? <div className="grid gap-4 sm:grid-cols-2"><Input label="วันที่นัดหมาย" type="date" value={date} onChange={(event) => setDate(event.target.value)} required disabled={pending} /><Input label="เวลาเริ่มต้น" type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} required max="22:59" disabled={pending} /></div> : <Textarea label={mode === "REJECT" ? "เหตุผลที่ปฏิเสธคำขอนัดหมาย" : "เหตุผลที่ยกเลิกนัดหมาย"} value={businessReason} onChange={(event) => setBusinessReason(event.target.value)} required minLength={5} maxLength={500} rows={4} helperText="เหตุผลนี้จะแสดงแก่ผู้ขอนัดหมาย" disabled={pending} />}{error && !reasonOpen ? <p className="text-sm text-red-600">{error}</p> : null}</form></Dialog><ConfirmDialog open={reasonOpen} title={`ยืนยัน${actionTitle}`} description="การดำเนินการแทนผู้ดูแลหมู่บ้านจะถูกบันทึกใน Audit Log และแจ้งผู้ดูแลหมู่บ้าน" confirmLabel="ยืนยันการดำเนินการ" pending={pending} confirmDisabled={reasonInvalid} onClose={() => { if (!pending) { setReasonOpen(false); setError(""); } }} onConfirm={submit}><Textarea label="เหตุผลในการดำเนินการ" required value={supportReason} onChange={(event) => { setSupportReason(event.target.value); setError(""); }} error={error || (supportReason.length > 0 && reasonInvalid ? "กรุณาระบุ 5–500 ตัวอักษร" : undefined)} helperText="ระบุเหตุผลที่ผู้ดูแลระบบระดับสูงดำเนินการแทนผู้ดูแลหมู่บ้าน" minLength={5} maxLength={500} rows={4} autoFocus disabled={pending} /></ConfirmDialog></>;
}
