"use client";

import Link from "next/link";
import { FilePlus2, ListChecks } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NewsFilterChip } from "@/components/news/news-toolbar";
import { ResidentPageToolbar } from "@/components/resident/resident-page-toolbar";
type Props = { keyword: string; category: string; sort: string; categories: string[]; canSubmit: boolean };
function href(keyword: string, category = "", sort = "default") { const query = new URLSearchParams(); if (keyword.trim()) query.set("q", keyword.trim()); if (category) query.set("category", category); if (sort !== "default") query.set("sort", sort); return query.size ? `/resident/contacts?${query}` : "/resident/contacts"; }
export function ResidentContactsToolbar({ keyword, category, sort, categories, canSubmit }: Props) { return <ResidentPageToolbar namespace="resident-contacts" title="รายชื่อผู้ติดต่อ" description="ช่องทางติดต่อหน่วยงานและผู้ประสานงานในหมู่บ้าน" search={{ keyword, placeholder: "ค้นหาชื่อหรือเบอร์โทรศัพท์", label: "ค้นหาผู้ติดต่อ" }} activeFilterCount={Number(Boolean(category)) + Number(sort !== "default")} actions={canSubmit ? <><Link href="/resident/contacts/requests" aria-label="ติดตามคำขอผู้ติดต่อ"><Button size="sm" variant="outline" className="h-10 px-2 sm:px-3"><ListChecks className="h-4 w-4" /><span className="hidden sm:ml-1.5 sm:inline">คำขอของฉัน</span></Button></Link><Link href="/resident/contacts/new"><Button size="sm" className="h-10 px-2 sm:px-3"><FilePlus2 className="h-4 w-4" /><span className="hidden min-[390px]:ml-1 min-[390px]:inline">ขอเพิ่มผู้ติดต่อ</span></Button></Link></> : undefined} filters={<>{categories.length ? <><span className="text-xs font-semibold text-gray-500">ประเภท</span><NewsFilterChip href={href(keyword, "", sort)} active={!category}>ทั้งหมด</NewsFilterChip>{categories.map((item) => <NewsFilterChip key={item} href={href(keyword, item, sort)} active={category === item}>{item}</NewsFilterChip>)}</> : null}<span className="ml-1 text-xs font-semibold text-gray-500">เรียง</span><NewsFilterChip href={href(keyword, category, "default")} active={sort === "default"}>ลำดับที่กำหนด</NewsFilterChip><NewsFilterChip href={href(keyword, category, "name")} active={sort === "name"}>ชื่อ ก-ฮ</NewsFilterChip><NewsFilterChip href="/resident/contacts" active={false}>ล้างตัวกรอง</NewsFilterChip></>} />; }
