"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Switch } from "@/components/ui/switch";
import { useToast } from "@/components/ui/toast";
import type { SystemSettingsInput } from "@/lib/system-settings-update";

type SettingsView = Required<SystemSettingsInput>;
type Props = { initialSettings: SettingsView; onSave: (input: SystemSettingsInput) => Promise<void> };
function SwitchRow({ id, title, helper, checked, disabled, onChange }: { id: string; title: string; helper: string; checked: boolean; disabled: boolean; onChange: (value: boolean) => void }) {
  return <div className="flex flex-col gap-3 rounded-xl border border-slate-200 px-4 py-4 sm:flex-row sm:items-start sm:justify-between"><div><label htmlFor={id} className="text-sm font-semibold text-slate-900">{title}</label><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">{helper}</p><p className="mt-2 text-xs font-medium text-slate-500">สถานะ: {checked ? "เปิดใช้งาน" : "ปิดใช้งาน"}</p></div><Switch id={id} aria-label={title} checked={checked} disabled={disabled} onCheckedChange={onChange} /></div>;
}

export function SystemSettingsForm({ initialSettings, onSave }: Props) {
  const [settings, setSettings] = useState(initialSettings); const [pending, setPending] = useState(false); const [confirmation, setConfirmation] = useState<"maintenance" | "registration" | null>(null); const { success, error } = useToast();
  const save = async (next: SystemSettingsInput) => { setPending(true); try { await onSave(next); setSettings((current) => ({ ...current, ...next })); success("บันทึกการตั้งค่าระบบแล้ว"); } catch (cause) { error("บันทึกการตั้งค่าไม่สำเร็จ", cause instanceof Error ? cause.message : "กรุณาลองใหม่อีกครั้ง"); } finally { setPending(false); setConfirmation(null); } };
  const requestToggle = (field: "maintenanceMode" | "registrationEnabled", value: boolean) => { const next = { [field]: value }; if ((field === "maintenanceMode" && value) || (field === "registrationEnabled" && !value)) { setConfirmation(field === "maintenanceMode" ? "maintenance" : "registration"); return; } void save(next); };
  return <div className="mx-auto w-full max-w-4xl space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-lg font-semibold text-slate-900">สถานะระบบ</h2><p className="mt-1 text-sm text-slate-600">ควบคุมการเข้าถึงพื้นที่ปฏิบัติงานระหว่างการบำรุงรักษา</p></div><div className="space-y-4"><SwitchRow id="maintenance-mode" title="โหมดปิดปรับปรุงระบบ" helper="ระหว่างปิดปรับปรุง งานปฏิบัติการทั่วไปจะถูกจำกัด แต่ผู้ใหญ่บ้านยังเข้าหน้านี้เพื่อปิดโหมดได้" checked={settings.maintenanceMode} disabled={pending} onChange={(value) => requestToggle("maintenanceMode", value)} /><label className="block text-sm font-semibold text-slate-900" htmlFor="maintenance-message">ข้อความขณะปิดปรับปรุง<textarea id="maintenance-message" value={settings.maintenanceMessage} maxLength={500} disabled={pending} onChange={(event) => setSettings({ ...settings, maintenanceMessage: event.target.value })} className="mt-2 min-h-28 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm font-normal text-slate-800 focus:border-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-100 disabled:bg-slate-50" /></label><div className="flex justify-end"><Button disabled={pending} isLoading={pending} onClick={() => void save({ maintenanceMode: settings.maintenanceMode, maintenanceMessage: settings.maintenanceMessage })}>บันทึกสถานะระบบ</Button></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-lg font-semibold text-slate-900">การสมัครสมาชิก</h2><p className="mt-1 text-sm text-slate-600">กำหนดบริการสาธารณะที่เปิดให้บุคคลทั่วไปใช้</p></div><div className="space-y-3"><SwitchRow id="registration-enabled" title="เปิดรับสมัครสมาชิกใหม่" helper="เมื่อปิด จะป้องกันการสมัครใหม่เท่านั้น บัญชีเดิมยังเข้าสู่ระบบได้" checked={settings.registrationEnabled} disabled={pending} onChange={(value) => requestToggle("registrationEnabled", value)} /><SwitchRow id="public-feedback-enabled" title="เปิดรับความคิดเห็นจากบุคคลทั่วไป" helper="เมื่อปิด จะหยุดรับข้อความใหม่โดยไม่ลบข้อความเดิม" checked={settings.publicFeedbackEnabled} disabled={pending} onChange={(value) => void save({ publicFeedbackEnabled: value })} /></div></section>
    <ConfirmDialog open={confirmation === "maintenance"} title="ยืนยันการเปิดโหมดปิดปรับปรุง" description="ลูกบ้านและงานปฏิบัติการของผู้ใหญ่บ้านจะใช้งานไม่ได้ชั่วคราว ผู้ใหญ่บ้านยังเข้าการตั้งค่าระบบเพื่อปิดโหมดนี้ได้" confirmLabel="เปิดโหมดปิดปรับปรุง" tone="danger" pending={pending} onClose={() => setConfirmation(null)} onConfirm={() => void save({ maintenanceMode: true, maintenanceMessage: settings.maintenanceMessage })} />
    <ConfirmDialog open={confirmation === "registration"} title="ยืนยันการปิดรับสมัครสมาชิกใหม่" description="ระบบจะไม่เริ่มหรือสร้างบัญชีใหม่จากขั้นตอนการสมัครจนกว่าจะเปิดรับสมัครอีกครั้ง บัญชีเดิมยังเข้าสู่ระบบได้ตามปกติ" confirmLabel="ปิดรับสมัคร" tone="danger" pending={pending} onClose={() => setConfirmation(null)} onConfirm={() => void save({ registrationEnabled: false })} />
  </div>;
}
