import { notFound } from "next/navigation";
import { AdminPageToolbar } from "@/components/ui/admin-page-toolbar";
import { requireVillagePagePermission } from "@/lib/admin-permission.server";
import { prisma } from "@/lib/prisma";
import { cancelAdminVillageBroadcastAction, updateAdminVillageBroadcastAction } from "../actions";

export default async function AdminBroadcastDetail({ params }: { params: Promise<{ broadcastId: string }> }) {
  const context = await requireVillagePagePermission("broadcasts.manage", { callbackUrl: "/admin/broadcasts" }); const { broadcastId } = await params; const broadcast = await prisma.systemBroadcast.findFirst({ where: { id: broadcastId, villageId: context.villageId } }); if (!broadcast) notFound(); const active = broadcast.status === "ACTIVE" && (!broadcast.expiresAt || broadcast.expiresAt > new Date());
  return <div data-admin-compact-top className="space-y-4"><AdminPageToolbar compact sticky variant="detail" title="รายละเอียดประกาศส่วนกลาง" backHref="/admin/broadcasts" backLabel="กลับรายการประกาศ" backPlacement="header-end" /><article className="mx-auto max-w-3xl rounded-xl border border-gray-200 bg-white p-5 sm:p-8"><h1 className="break-words text-2xl font-bold">{broadcast.title}</h1><p className="mt-6 whitespace-pre-wrap break-words leading-7 text-gray-800">{broadcast.body}</p><dl className="mt-8 grid gap-3 border-t pt-5 text-sm sm:grid-cols-3"><div><dt className="text-gray-500">ผู้รับ</dt><dd>{broadcast.audienceCount.toLocaleString("th-TH")} คน</dd></div><div><dt className="text-gray-500">หมดอายุ</dt><dd>{broadcast.expiresAt?.toLocaleString("th-TH") ?? "ไม่กำหนด"}</dd></div><div><dt className="text-gray-500">สร้างเมื่อ</dt><dd>{broadcast.createdAt.toLocaleString("th-TH")}</dd></div></dl>{active ? <div className="mt-8 grid gap-5 border-t pt-5"><form action={updateAdminVillageBroadcastAction} className="grid gap-3"><input type="hidden" name="broadcastGroupId" value={broadcast.id} /><h2 className="font-semibold">แก้ไขประกาศ</h2><label className="text-sm">หัวข้อ<input name="title" required defaultValue={broadcast.title} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm">เนื้อหา<textarea name="body" required rows={5} defaultValue={broadcast.body} className="mt-1 w-full rounded border p-2" /></label><input type="hidden" name="expiryMode" value="PRESERVE" /><button className="w-fit rounded bg-green-700 px-4 py-2 text-sm text-white">บันทึกการแก้ไข</button></form><form action={cancelAdminVillageBroadcastAction}><input type="hidden" name="broadcastGroupId" value={broadcast.id} /><button className="rounded border border-red-300 px-4 py-2 text-sm text-red-700">ยกเลิกประกาศ</button></form></div> : null}</article></div>;
}
