import { notFound } from "next/navigation";
import { AdminPageToolbar } from "@/components/ui/admin-page-toolbar";
import { requireVillagePagePermission } from "@/lib/admin-permission.server";
import { prisma } from "@/lib/prisma";
import { cancelAdminVillageBroadcastAction, updateAdminVillageBroadcastAction } from "../actions";
import { CancelBroadcastButton } from "../cancel-broadcast-button";
import { broadcastExpiryLabel, broadcastStatusClassName, broadcastStatusLabels, type BroadcastDisplayStatus } from "../broadcast-presentation";
import { BroadcastEditForm } from "../broadcast-edit-form";

export default async function AdminBroadcastDetail({ params }: { params: Promise<{ broadcastId: string }> }) {
  const context = await requireVillagePagePermission("broadcasts.manage", { callbackUrl: "/admin/broadcasts" });
  const { broadcastId } = await params;
  const broadcast = await prisma.systemBroadcast.findFirst({ where: { id: broadcastId, villageId: context.villageId }, include: { createdBy: { select: { name: true } } } });
  if (!broadcast) notFound();
  const active = broadcast.status === "ACTIVE" && (!broadcast.expiresAt || broadcast.expiresAt > new Date());
  const state: BroadcastDisplayStatus = broadcast.status === "CANCELLED" ? "CANCELLED" : active ? "ACTIVE" : "EXPIRED";
  const statusHint = state === "ACTIVE" ? "ประกาศนี้กำลังแสดงให้สมาชิกในหมู่บ้าน" : state === "EXPIRED" ? "ประกาศนี้หมดอายุแล้ว" : "ประกาศนี้ถูกยกเลิกแล้ว";

  return <div data-admin-compact-top className="space-y-4"><AdminPageToolbar compact sticky variant="detail" title="รายละเอียดประกาศ" backHref="/admin/broadcasts" backLabel="กลับรายการประกาศ" backPlacement="header-start" /><main className="mx-auto w-full max-w-4xl space-y-4"><article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100 sm:p-8"><header><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${broadcastStatusClassName(state)}`}>{broadcastStatusLabels[state]}</span><h1 className="mt-4 break-words text-2xl font-bold tracking-tight text-gray-950">{broadcast.title}</h1><p className="mt-5 whitespace-pre-wrap break-words text-base leading-8 text-gray-800">{broadcast.body}</p><p className="mt-5 text-sm text-gray-500">{statusHint}</p></header><dl className="mt-8 grid gap-4 rounded-xl bg-gray-50 p-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-gray-500">ผู้รับ</dt><dd className="mt-1 font-medium text-gray-900">{broadcast.audienceCount.toLocaleString("th-TH")} คน</dd></div><div><dt className="text-xs text-gray-500">สร้างโดย</dt><dd className="mt-1 break-words font-medium text-gray-900">{broadcast.createdBy?.name || "ไม่ระบุ"}</dd></div><div><dt className="text-xs text-gray-500">สร้างเมื่อ</dt><dd className="mt-1 break-words font-medium text-gray-900">{broadcast.createdAt.toLocaleString("th-TH")}</dd></div><div><dt className="text-xs text-gray-500">หมดอายุ</dt><dd className="mt-1 break-words font-medium text-gray-900">{broadcastExpiryLabel(broadcast.expiresAt)}</dd></div>{broadcast.cancelledAt ? <div><dt className="text-xs text-gray-500">ยกเลิกเมื่อ</dt><dd className="mt-1 break-words font-medium text-gray-900">{broadcast.cancelledAt.toLocaleString("th-TH")}</dd></div> : null}</dl></article>{active ? <><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100 sm:p-6" aria-labelledby="edit-broadcast"><h2 id="edit-broadcast" className="text-base font-semibold text-gray-900">แก้ไขประกาศ</h2><p className="mt-1 text-sm text-gray-500">การแก้ไขจะอัปเดตข้อความในประกาศที่ส่งให้สมาชิกแล้ว</p><BroadcastEditForm action={updateAdminVillageBroadcastAction} broadcastId={broadcast.id} title={broadcast.title} body={broadcast.body} /></section><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100 sm:p-6" aria-labelledby="broadcast-management"><h2 id="broadcast-management" className="text-base font-semibold text-gray-900">การจัดการประกาศ</h2><p className="mt-1 text-sm text-gray-500">เมื่อยกเลิก ประกาศจะหยุดแสดงและการแจ้งเตือนที่ยังใช้งานอยู่จะถูกจัดเก็บ</p><div className="mt-4"><CancelBroadcastButton action={cancelAdminVillageBroadcastAction} broadcastId={broadcast.id} /></div></section></> : null}</main></div>;
}
